<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 7 Introdução à Teoria das Probabilidades | Introdução à Bioestatística usando o R</title>
  <meta name="description" content="Capítulo 7 Introdução à Teoria das Probabilidades | Introdução à Bioestatística usando o R" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 7 Introdução à Teoria das Probabilidades | Introdução à Bioestatística usando o R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 7 Introdução à Teoria das Probabilidades | Introdução à Bioestatística usando o R" />
  
  
  

<meta name="author" content="Petrônio Fagundes de Oliveira Filho" />


<meta name="date" content="2023-05-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="descrevendo-os-dados.html"/>
<link rel="next" href="assimetria-e-curtose.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">bookR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introdução</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#importância-da-bioestatística"><i class="fa fa-check"></i><b>1.1</b> Importância da Bioestatística</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#sec-historia"><i class="fa fa-check"></i><b>1.2</b> Pílulas históricas da Estatística</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#história-resumida-do-r"><i class="fa fa-check"></i><b>1.3</b> História resumida do R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html"><i class="fa fa-check"></i><b>2</b> Natureza dos Dados</a>
<ul>
<li class="chapter" data-level="2.1" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#variáveis-e-dados"><i class="fa fa-check"></i><b>2.1</b> Variáveis e Dados</a></li>
<li class="chapter" data-level="2.2" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#população-e-amostra"><i class="fa fa-check"></i><b>2.2</b> População e Amostra</a></li>
<li class="chapter" data-level="2.3" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#estimativas-e-parâmetros"><i class="fa fa-check"></i><b>2.3</b> Estimativas e Parâmetros</a></li>
<li class="chapter" data-level="2.4" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escalas-de-medição"><i class="fa fa-check"></i><b>2.4</b> Escalas de medição</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-nominal"><i class="fa fa-check"></i><b>2.4.1</b> Escala Nominal</a></li>
<li class="chapter" data-level="2.4.2" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-ordinal"><i class="fa fa-check"></i><b>2.4.2</b> Escala Ordinal</a></li>
<li class="chapter" data-level="2.4.3" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-intervalar"><i class="fa fa-check"></i><b>2.4.3</b> Escala Intervalar</a></li>
<li class="chapter" data-level="2.4.4" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-de-razão"><i class="fa fa-check"></i><b>2.4.4</b> Escala de Razão</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#tipos-de-variáveis"><i class="fa fa-check"></i><b>2.5</b> Tipos de Variáveis</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#variáveis-numéricas"><i class="fa fa-check"></i><b>2.5.1</b> Variáveis Numéricas</a></li>
<li class="chapter" data-level="2.5.2" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#variáveis-categóricas"><i class="fa fa-check"></i><b>2.5.2</b> Variáveis Categóricas</a></li>
<li class="chapter" data-level="2.5.3" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#como-identificar-o-tipo-da-variável"><i class="fa fa-check"></i><b>2.5.3</b> Como identificar o tipo da variável?</a></li>
<li class="chapter" data-level="2.5.4" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#variáveis-dependentes-e-independentes"><i class="fa fa-check"></i><b>2.5.4</b> Variáveis Dependentes e Independentes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html"><i class="fa fa-check"></i><b>3</b> Produção dos Dados</a>
<ul>
<li class="chapter" data-level="3.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#processo-de-pesquisa"><i class="fa fa-check"></i><b>3.1</b> Processo de Pesquisa</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#questão-de-pesquisa"><i class="fa fa-check"></i><b>3.1.1</b> Questão de Pesquisa</a></li>
<li class="chapter" data-level="3.1.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#hipótese-de-pesquisa"><i class="fa fa-check"></i><b>3.1.2</b> Hipótese de Pesquisa</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#processo-de-amostragem"><i class="fa fa-check"></i><b>3.2</b> Processo de Amostragem</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#amostras-probabilística"><i class="fa fa-check"></i><b>3.2.1</b> Amostras probabilística</a></li>
<li class="chapter" data-level="3.2.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#amostras-não-probabilísticas"><i class="fa fa-check"></i><b>3.2.2</b> Amostras não probabilísticas</a></li>
<li class="chapter" data-level="3.2.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#tamanho-amostral"><i class="fa fa-check"></i><b>3.2.3</b> Tamanho amostral</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#principais-delineamentos-de-pesquisa"><i class="fa fa-check"></i><b>3.3</b> Principais Delineamentos de Pesquisa</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#elementos-básicos-de-um-delineamento-de-pesquisa"><i class="fa fa-check"></i><b>3.3.1</b> Elementos básicos de um delineamento de pesquisa</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-observacionais"><i class="fa fa-check"></i><b>3.4</b> Estudos Observacionais</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#relato-de-caso-ou-série-de-casos"><i class="fa fa-check"></i><b>3.4.1</b> Relato de Caso ou Série de casos</a></li>
<li class="chapter" data-level="3.4.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-transversais-ou-seccionais"><i class="fa fa-check"></i><b>3.4.2</b> Estudos Transversais ou Seccionais</a></li>
<li class="chapter" data-level="3.4.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-caso-controle"><i class="fa fa-check"></i><b>3.4.3</b> Estudos Caso-Controle</a></li>
<li class="chapter" data-level="3.4.4" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-de-coorte"><i class="fa fa-check"></i><b>3.4.4</b> Estudos de Coorte</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#ensaios-clínicos"><i class="fa fa-check"></i><b>3.5</b> Ensaios Clínicos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#características-de-um-ensaio-clínico"><i class="fa fa-check"></i><b>3.5.1</b> Características de um ensaio clínico</a></li>
<li class="chapter" data-level="3.5.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#elementos-básicos-de-um-ensaio-clínico"><i class="fa fa-check"></i><b>3.5.2</b> Elementos básicos de um ensaio clínico</a></li>
<li class="chapter" data-level="3.5.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#ensaios-clínicos-de-equivalência-e-não-inferioridade"><i class="fa fa-check"></i><b>3.5.3</b> Ensaios clínicos de equivalência e não inferioridade</a></li>
<li class="chapter" data-level="3.5.4" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#outros-tipos-de-ensaios-clínicos"><i class="fa fa-check"></i><b>3.5.4</b> Outros tipos de ensaios clínicos</a></li>
<li class="chapter" data-level="3.5.5" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#fases-de-um-ensaio-clínico"><i class="fa fa-check"></i><b>3.5.5</b> Fases de um ensaio clínico</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html"><i class="fa fa-check"></i><b>4</b> Ambiente do <em>R</em></a>
<ul>
<li class="chapter" data-level="4.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalação-do-r-básico"><i class="fa fa-check"></i><b>4.1</b> Instalação do <em>R</em> básico</a></li>
<li class="chapter" data-level="4.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#rstudio"><i class="fa fa-check"></i><b>4.2</b> <em>RStudio</em></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalação-do-r-studio"><i class="fa fa-check"></i><b>4.2.1</b> Instalação do <em>R Studio</em></a></li>
<li class="chapter" data-level="4.2.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#iniciando-o-rstudio"><i class="fa fa-check"></i><b>4.2.2</b> Iniciando o <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#pacotes"><i class="fa fa-check"></i><b>4.3</b> Pacotes</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#repositório-de-pacotes"><i class="fa fa-check"></i><b>4.3.1</b> Repositório de pacotes</a></li>
<li class="chapter" data-level="4.3.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalação-de-um-novo-pacote"><i class="fa fa-check"></i><b>4.3.2</b> Instalação de um novo pacote</a></li>
<li class="chapter" data-level="4.3.3" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#atualização-dos-pacotes"><i class="fa fa-check"></i><b>4.3.3</b> Atualização dos pacotes</a></li>
<li class="chapter" data-level="4.3.4" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalando-e-carregando-mais-de-um-pacote"><i class="fa fa-check"></i><b>4.3.4</b> Instalando e carregando mais de um pacote</a></li>
<li class="chapter" data-level="4.3.5" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#citação-de-pacotes-em-publicações"><i class="fa fa-check"></i><b>4.3.5</b> Citação de pacotes em publicações</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#diretório-de-trabalho"><i class="fa fa-check"></i><b>4.4</b> Diretório de trabalho</a></li>
<li class="chapter" data-level="4.5" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#projeto"><i class="fa fa-check"></i><b>4.5</b> Projeto</a></li>
<li class="chapter" data-level="4.6" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#o-r-como-calculadora"><i class="fa fa-check"></i><b>4.6</b> O <em>R</em> como calculadora</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#operadores"><i class="fa fa-check"></i><b>4.6.1</b> Operadores</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-objetos"><i class="fa fa-check"></i><b>4.7</b> Objetos</a></li>
<li class="chapter" data-level="4.8" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#funções"><i class="fa fa-check"></i><b>4.8</b> Funções</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#criando-funções"><i class="fa fa-check"></i><b>4.8.1</b> Criando funções</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#classes"><i class="fa fa-check"></i><b>4.9</b> Classes</a></li>
<li class="chapter" data-level="4.10" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-vetores"><i class="fa fa-check"></i><b>4.10</b> Vetores</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#tipos-de-vetores"><i class="fa fa-check"></i><b>4.10.1</b> Tipos de vetores</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-dataframes"><i class="fa fa-check"></i><b>4.11</b> Dataframes</a></li>
<li class="chapter" data-level="4.12" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-fatores"><i class="fa fa-check"></i><b>4.12</b> Fatores</a>
<ul>
<li class="chapter" data-level="4.12.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#criando-fatores"><i class="fa fa-check"></i><b>4.12.1</b> Criando fatores</a></li>
<li class="chapter" data-level="4.12.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#salvando-o-dataframe-criado"><i class="fa fa-check"></i><b>4.12.2</b> Salvando o dataframe criado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html"><i class="fa fa-check"></i><b>5</b> Manipulando os dados no <em>R Studio</em></a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#importando-dados-de-outros-softwares"><i class="fa fa-check"></i><b>5.1</b> Importando dados de outros <em>softwares</em></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-csv"><i class="fa fa-check"></i><b>5.1.1</b> Importando dados de um arquivo CSV</a></li>
<li class="chapter" data-level="5.1.2" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-xlsx"><i class="fa fa-check"></i><b>5.1.2</b> Importando um arquivo do Excel</a></li>
<li class="chapter" data-level="5.1.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#importando-arquivos-com-o-rstudio"><i class="fa fa-check"></i><b>5.1.3</b> Importando arquivos com o RStudio</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-tibble"><i class="fa fa-check"></i><b>5.2</b> Tibble</a></li>
<li class="chapter" data-level="5.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-mater"><i class="fa fa-check"></i><b>5.3</b> Pacote <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-select"><i class="fa fa-check"></i><b>5.3.1</b> Função <code>select()</code></a></li>
<li class="chapter" data-level="5.3.2" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-filter"><i class="fa fa-check"></i><b>5.3.2</b> Função <code>filter()</code></a></li>
<li class="chapter" data-level="5.3.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-mutate"><i class="fa fa-check"></i><b>5.3.3</b> Função <code>mutate()</code></a></li>
<li class="chapter" data-level="5.3.4" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-sample_n"><i class="fa fa-check"></i><b>5.3.4</b> Função <code>sample_n()</code></a></li>
<li class="chapter" data-level="5.3.5" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-slice"><i class="fa fa-check"></i><b>5.3.5</b> Função <code>slice()</code></a></li>
<li class="chapter" data-level="5.3.6" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-arrange"><i class="fa fa-check"></i><b>5.3.6</b> Função <code>arrange()</code></a></li>
<li class="chapter" data-level="5.3.7" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#função-count"><i class="fa fa-check"></i><b>5.3.7</b> Função <code>count()</code></a></li>
<li class="chapter" data-level="5.3.8" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#operador-pipe"><i class="fa fa-check"></i><b>5.3.8</b> Operador pipe %&gt;%</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#manipulação-de-datas"><i class="fa fa-check"></i><b>5.4</b> Manipulação de datas</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#operações-com-datas"><i class="fa fa-check"></i><b>5.4.1</b> Operações com datas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html"><i class="fa fa-check"></i><b>6</b> Descrevendo os dados</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#dados-brutos"><i class="fa fa-check"></i><b>6.1</b> Dados brutos</a></li>
<li class="chapter" data-level="6.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#medidas-resumidoras"><i class="fa fa-check"></i><b>6.2</b> Medidas resumidoras</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#medidas-de-tendência-central"><i class="fa fa-check"></i><b>6.2.1</b> Medidas de tendência central</a></li>
<li class="chapter" data-level="6.2.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#medidas-de-dispersão"><i class="fa fa-check"></i><b>6.2.2</b> Medidas de Dispersão</a></li>
<li class="chapter" data-level="6.2.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#escolha-da-medida-resumidora"><i class="fa fa-check"></i><b>6.2.3</b> Escolha da medida resumidora</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#tabelas"><i class="fa fa-check"></i><b>6.3</b> Tabelas</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-freq"><i class="fa fa-check"></i><b>6.3.1</b> Tabelas de Frequência</a></li>
<li class="chapter" data-level="6.3.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#tabelas-de-contingência"><i class="fa fa-check"></i><b>6.3.2</b> Tabelas de contingência</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#gráficos"><i class="fa fa-check"></i><b>6.4</b> Gráficos</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#gráfico-de-setores"><i class="fa fa-check"></i><b>6.4.1</b> Gráfico de setores</a></li>
<li class="chapter" data-level="6.4.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#gráfico-de-barras"><i class="fa fa-check"></i><b>6.4.2</b> Gráfico de barras</a></li>
<li class="chapter" data-level="6.4.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#gráfico-de-barra-de-erro"><i class="fa fa-check"></i><b>6.4.3</b> Gráfico de barra de erro</a></li>
<li class="chapter" data-level="6.4.4" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#histograma"><i class="fa fa-check"></i><b>6.4.4</b> Histograma</a></li>
<li class="chapter" data-level="6.4.5" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#boxplot"><i class="fa fa-check"></i><b>6.4.5</b> Boxplot</a></li>
<li class="chapter" data-level="6.4.6" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#gráfico-de-dispersão"><i class="fa fa-check"></i><b>6.4.6</b> Gráfico de Dispersão</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#introdução-ao-ggplot2"><i class="fa fa-check"></i><b>6.5</b> Introdução ao <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#dados"><i class="fa fa-check"></i><b>6.5.1</b> Dados</a></li>
<li class="chapter" data-level="6.5.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#ggplot"><i class="fa fa-check"></i><b>6.5.2</b> <code>ggplot</code></a></li>
<li class="chapter" data-level="6.5.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#tipos-de-geoms"><i class="fa fa-check"></i><b>6.5.3</b> Tipos de <code>geoms</code></a></li>
<li class="chapter" data-level="6.5.4" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#modificando-argumentos-do-geom"><i class="fa fa-check"></i><b>6.5.4</b> Modificando argumentos do <code>geom</code></a></li>
<li class="chapter" data-level="6.5.5" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#reta-de-ajuste-em-um-gráfico-de-dispersão"><i class="fa fa-check"></i><b>6.5.5</b> Reta de ajuste em um gráfico de dispersão</a></li>
<li class="chapter" data-level="6.5.6" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#filtrando-dados-para-o-gráfico"><i class="fa fa-check"></i><b>6.5.6</b> Filtrando dados para o gráfico</a></li>
<li class="chapter" data-level="6.5.7" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#resumo-dos-dados-usando-o-geom"><i class="fa fa-check"></i><b>6.5.7</b> Resumo dos dados usando o geom</a></li>
<li class="chapter" data-level="6.5.8" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#incluindo-barras-de-erro"><i class="fa fa-check"></i><b>6.5.8</b> Incluindo barras de erro</a></li>
<li class="chapter" data-level="6.5.9" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#incluindo-mais-de-um-grupo-no-gráfico"><i class="fa fa-check"></i><b>6.5.9</b> Incluindo mais de um grupo no gráfico</a></li>
<li class="chapter" data-level="6.5.10" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#modificando-o-tema"><i class="fa fa-check"></i><b>6.5.10</b> Modificando o tema</a></li>
<li class="chapter" data-level="6.5.11" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#trabalhando-com-os-eixos"><i class="fa fa-check"></i><b>6.5.11</b> Trabalhando com os eixos</a></li>
<li class="chapter" data-level="6.5.12" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#modificação-das-cores"><i class="fa fa-check"></i><b>6.5.12</b> Modificação das cores</a></li>
<li class="chapter" data-level="6.5.13" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#exemplo-final-gráfico-de-barra-de-erro-com-colunas"><i class="fa fa-check"></i><b>6.5.13</b> Exemplo final: Gráfico de barra de erro com colunas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html"><i class="fa fa-check"></i><b>7</b> Introdução à Teoria das Probabilidades</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#introdução-1"><i class="fa fa-check"></i><b>7.1</b> Introdução</a></li>
<li class="chapter" data-level="7.2" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#processo-aleatório"><i class="fa fa-check"></i><b>7.2</b> Processo aleatório</a></li>
<li class="chapter" data-level="7.3" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#definição-frequentista-de-probabilidade"><i class="fa fa-check"></i><b>7.3</b> Definição frequentista de probabilidade</a></li>
<li class="chapter" data-level="7.4" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#propriedades-das-probabilidades"><i class="fa fa-check"></i><b>7.4</b> Propriedades das probabilidades</a></li>
<li class="chapter" data-level="7.5" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#distribuição-de-probabilidades"><i class="fa fa-check"></i><b>7.5</b> Distribuição de Probabilidades</a></li>
<li class="chapter" data-level="7.6" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#distribuição-normal"><i class="fa fa-check"></i><b>7.6</b> Distribuição Normal</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#características-da-distribuição-normal"><i class="fa fa-check"></i><b>7.6.1</b> Características da distribuição normal</a></li>
<li class="chapter" data-level="7.6.2" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#sec-dnp"><i class="fa fa-check"></i><b>7.6.2</b> Distribuição normal padronizada</a></li>
<li class="chapter" data-level="7.6.3" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#regra-empírica-68-95-99.7"><i class="fa fa-check"></i><b>7.6.3</b> Regra Empírica 68-95-99.7</a></li>
<li class="chapter" data-level="7.6.4" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#exercitando-o-raciocínio-com-a-curva-normal"><i class="fa fa-check"></i><b>7.6.4</b> Exercitando o raciocínio com a curva normal</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#distribuição-binomial"><i class="fa fa-check"></i><b>7.7</b> Distribuição Binomial</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#média-e-desvio-padrão-da-distribuição-binomial"><i class="fa fa-check"></i><b>7.7.1</b> Média e desvio padrão da distribuição binomial</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#distribuição-de-poisson"><i class="fa fa-check"></i><b>7.8</b> Distribuição de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html"><i class="fa fa-check"></i><b>8</b> Assimetria e Curtose</a>
<ul>
<li class="chapter" data-level="8.1" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#assimetria"><i class="fa fa-check"></i><b>8.1</b> Assimetria</a></li>
<li class="chapter" data-level="8.2" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#curtose"><i class="fa fa-check"></i><b>8.2</b> Curtose</a></li>
<li class="chapter" data-level="8.3" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#testando-o-raciocínio"><i class="fa fa-check"></i><b>8.3</b> Testando o raciocínio</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html"><i class="fa fa-check"></i><b>9</b> Distribuições Amostrais</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#pacotes-necessários-para-este-capítulo"><i class="fa fa-check"></i><b>9.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="9.2" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#distribuições-populacional-e-amostral"><i class="fa fa-check"></i><b>9.2</b> Distribuições populacional e amostral</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#distribuição-populacional"><i class="fa fa-check"></i><b>9.2.1</b> Distribuição populacional</a></li>
<li class="chapter" data-level="9.2.2" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#distribuição-amostral"><i class="fa fa-check"></i><b>9.2.2</b> Distribuição amostral</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#erros-amostrais-e-não-amostrais"><i class="fa fa-check"></i><b>9.3</b> Erros amostrais e não amostrais</a></li>
<li class="chapter" data-level="9.4" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#média-e-desvio-padrão-da-média"><i class="fa fa-check"></i><b>9.4</b> Média e desvio padrão da média</a></li>
<li class="chapter" data-level="9.5" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#teorema-do-limite-central"><i class="fa fa-check"></i><b>9.5</b> Teorema do Limite Central</a></li>
<li class="chapter" data-level="9.6" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#proporções-populacional-e-amostral"><i class="fa fa-check"></i><b>9.6</b> Proporções populacional e amostral</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html#distribuição-amostral-da-proporção-amostral"><i class="fa fa-check"></i><b>9.6.1</b> Distribuição amostral da proporção amostral</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="estimação.html"><a href="estimação.html"><i class="fa fa-check"></i><b>10</b> Estimação</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estimação.html"><a href="estimação.html#introdução-2"><i class="fa fa-check"></i><b>10.1</b> Introdução</a></li>
<li class="chapter" data-level="10.2" data-path="estimação.html"><a href="estimação.html#pacotes-necessários-para-este-capítulo-1"><i class="fa fa-check"></i><b>10.2</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="10.3" data-path="estimação.html"><a href="estimação.html#estimativa-pontual-e-intervalo-de-confiança"><i class="fa fa-check"></i><b>10.3</b> Estimativa Pontual e Intervalo de Confiança</a></li>
<li class="chapter" data-level="10.4" data-path="estimação.html"><a href="estimação.html#estimação-da-média-populacional-sigma-conhecido"><i class="fa fa-check"></i><b>10.4</b> Estimação da média populacional: <span class="math inline">\(\sigma\)</span> conhecido</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="estimação.html"><a href="estimação.html#interpretação-do-intervalo-de-confiança"><i class="fa fa-check"></i><b>10.4.1</b> Interpretação do intervalo de confiança</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="estimação.html"><a href="estimação.html#estimação-da-média-populacional-sigma-desconhecido"><i class="fa fa-check"></i><b>10.5</b> Estimação da média populacional: <span class="math inline">\(\sigma\)</span> desconhecido</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="estimação.html"><a href="estimação.html#distribuição-t"><i class="fa fa-check"></i><b>10.5.1</b> Distribuição <em>t</em></a></li>
<li class="chapter" data-level="10.5.2" data-path="estimação.html"><a href="estimação.html#cálculo-do-intervalo-de-confiança-com-sigma-desconhecido"><i class="fa fa-check"></i><b>10.5.2</b> Cálculo do intervalo de confiança com <span class="math inline">\(\sigma\)</span> desconhecido</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="estimação.html"><a href="estimação.html#intervalo-de-confiança-para-uma-proporção-populacional"><i class="fa fa-check"></i><b>10.6</b> Intervalo de Confiança para uma proporção populacional</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="estimação.html"><a href="estimação.html#dados-para-estimar-a-proporção-populacional"><i class="fa fa-check"></i><b>10.6.1</b> Dados para estimar a proporção populacional</a></li>
<li class="chapter" data-level="10.6.2" data-path="estimação.html"><a href="estimação.html#cálculo-da-estimativa-pontual-da-proporção"><i class="fa fa-check"></i><b>10.6.2</b> Cálculo da estimativa pontual da proporção</a></li>
<li class="chapter" data-level="10.6.3" data-path="estimação.html"><a href="estimação.html#cálculo-do-intervalo-de-confiança-para-a-proporção"><i class="fa fa-check"></i><b>10.6.3</b> Cálculo do intervalo de confiança para a proporção</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html"><i class="fa fa-check"></i><b>11</b> Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="11.1" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#pacotes-necessários-para-este-capítulo-2"><i class="fa fa-check"></i><b>11.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="11.2" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#exemplo"><i class="fa fa-check"></i><b>11.2</b> Exemplo</a></li>
<li class="chapter" data-level="11.3" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#hipótese-nula-e-alternativa"><i class="fa fa-check"></i><b>11.3</b> Hipótese nula e alternativa</a></li>
<li class="chapter" data-level="11.4" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#escolha-do-teste-estatítico-e-regra-de-decisão"><i class="fa fa-check"></i><b>11.4</b> Escolha do teste estatítico e regra de decisão</a></li>
<li class="chapter" data-level="11.5" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#valor-p"><i class="fa fa-check"></i><b>11.5</b> Valor <em>P</em></a></li>
<li class="chapter" data-level="11.6" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#poder-do-teste"><i class="fa fa-check"></i><b>11.6</b> Poder do teste</a></li>
<li class="chapter" data-level="11.7" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#resumo-do-teste-de-hipóteses-passos-principais"><i class="fa fa-check"></i><b>11.7</b> Resumo do teste de hipóteses: Passos principais</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#primeiro-passo-dados"><i class="fa fa-check"></i><b>11.7.1</b> Primeiro Passo: Dados</a></li>
<li class="chapter" data-level="11.7.2" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#segundo-passo-estabelecer-as-hipóteses-estatísticas"><i class="fa fa-check"></i><b>11.7.2</b> Segundo Passo: Estabelecer as hipóteses estatísticas</a></li>
<li class="chapter" data-level="11.7.3" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#terceiro-passo-escolha-do-teste-estatístico-e-regra-de-decisão"><i class="fa fa-check"></i><b>11.7.3</b> Terceiro passo: Escolha do teste estatístico e regra de decisão</a></li>
<li class="chapter" data-level="11.7.4" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#quarto-passo-conclusão"><i class="fa fa-check"></i><b>11.7.4</b> Quarto passo: Conclusão</a></li>
<li class="chapter" data-level="11.7.5" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#quinto-passo-valor-p"><i class="fa fa-check"></i><b>11.7.5</b> Quinto passo: Valor <em>P</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html"><i class="fa fa-check"></i><b>12</b> Comparação entre duas médias</a>
<ul>
<li class="chapter" data-level="12.1" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#pacotes-necessários-para-este-capítulo-3"><i class="fa fa-check"></i><b>12.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="12.2" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#teste-t-para-comparar-amostras-independentes"><i class="fa fa-check"></i><b>12.2</b> Teste <em>t</em> para comparar amostras independentes</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#dados-do-exemplo"><i class="fa fa-check"></i><b>12.2.1</b> Dados do exemplo</a></li>
<li class="chapter" data-level="12.2.2" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#definição-das-hipóteses-estatísticas"><i class="fa fa-check"></i><b>12.2.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="12.2.3" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#definição-da-regra-de-decisão"><i class="fa fa-check"></i><b>12.2.3</b> Definição da regra de decisão</a></li>
<li class="chapter" data-level="12.2.4" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#teste-estatístico"><i class="fa fa-check"></i><b>12.2.4</b> Teste estatístico</a></li>
<li class="chapter" data-level="12.2.5" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#conclusão"><i class="fa fa-check"></i><b>12.2.5</b> Conclusão</a></li>
<li class="chapter" data-level="12.2.6" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#tamanho-do-efeito"><i class="fa fa-check"></i><b>12.2.6</b> Tamanho do Efeito</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#teste-t-para-grupos-pareados"><i class="fa fa-check"></i><b>12.3</b> Teste <em>t</em> para grupos pareados</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#dados-do-exemplo-1"><i class="fa fa-check"></i><b>12.3.1</b> Dados do exemplo</a></li>
<li class="chapter" data-level="12.3.2" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#definição-das-hipóteses-estatísticas-1"><i class="fa fa-check"></i><b>12.3.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="12.3.3" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#regra-de-decisão"><i class="fa fa-check"></i><b>12.3.3</b> Regra de decisão</a></li>
<li class="chapter" data-level="12.3.4" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#teste-estatístico-1"><i class="fa fa-check"></i><b>12.3.4</b> Teste estatístico</a></li>
<li class="chapter" data-level="12.3.5" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#conclusão-1"><i class="fa fa-check"></i><b>12.3.5</b> Conclusão</a></li>
<li class="chapter" data-level="12.3.6" data-path="comparação-entre-duas-médias.html"><a href="comparação-entre-duas-médias.html#tamanho-do-efeito-1"><i class="fa fa-check"></i><b>12.3.6</b> Tamanho do Efeito</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="análise-de-variância.html"><a href="análise-de-variância.html"><i class="fa fa-check"></i><b>13</b> Análise de Variância</a>
<ul>
<li class="chapter" data-level="13.1" data-path="análise-de-variância.html"><a href="análise-de-variância.html#pacotes-necessários-para-este-capítulo-4"><i class="fa fa-check"></i><b>13.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="13.2" data-path="análise-de-variância.html"><a href="análise-de-variância.html#anova-de-um-fator"><i class="fa fa-check"></i><b>13.2</b> ANOVA de um fator</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="análise-de-variância.html"><a href="análise-de-variância.html#por-que-realizar-uma-anova"><i class="fa fa-check"></i><b>13.2.1</b> Por que realizar uma ANOVA?</a></li>
<li class="chapter" data-level="13.2.2" data-path="análise-de-variância.html"><a href="análise-de-variância.html#lógica-do-modelo-da-anova"><i class="fa fa-check"></i><b>13.2.2</b> Lógica do Modelo da ANOVA</a></li>
<li class="chapter" data-level="13.2.3" data-path="análise-de-variância.html"><a href="análise-de-variância.html#distribuição-f"><i class="fa fa-check"></i><b>13.2.3</b> Distribuição <em>F</em></a></li>
<li class="chapter" data-level="13.2.4" data-path="análise-de-variância.html"><a href="análise-de-variância.html#dados-do-exemplo-2"><i class="fa fa-check"></i><b>13.2.4</b> Dados do exemplo</a></li>
<li class="chapter" data-level="13.2.5" data-path="análise-de-variância.html"><a href="análise-de-variância.html#definição-das-hipóteses-estatísticas-2"><i class="fa fa-check"></i><b>13.2.5</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="13.2.6" data-path="análise-de-variância.html"><a href="análise-de-variância.html#definição-da-regra-de-decisão-1"><i class="fa fa-check"></i><b>13.2.6</b> Definição da regra de decisão</a></li>
<li class="chapter" data-level="13.2.7" data-path="análise-de-variância.html"><a href="análise-de-variância.html#teste-estatístico-2"><i class="fa fa-check"></i><b>13.2.7</b> Teste Estatístico</a></li>
<li class="chapter" data-level="13.2.8" data-path="análise-de-variância.html"><a href="análise-de-variância.html#testes-post-hoc"><i class="fa fa-check"></i><b>13.2.8</b> Testes <em>post-hoc</em></a></li>
<li class="chapter" data-level="13.2.9" data-path="análise-de-variância.html"><a href="análise-de-variância.html#tamanho-do-efeito-2"><i class="fa fa-check"></i><b>13.2.9</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="13.2.10" data-path="análise-de-variância.html"><a href="análise-de-variância.html#conclusão-2"><i class="fa fa-check"></i><b>13.2.10</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="análise-de-variância.html"><a href="análise-de-variância.html#anova-de-dois-fatores"><i class="fa fa-check"></i><b>13.3</b> ANOVA de dois fatores</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="análise-de-variância.html"><a href="análise-de-variância.html#dados-do-exemplo-3"><i class="fa fa-check"></i><b>13.3.1</b> Dados do exemplo</a></li>
<li class="chapter" data-level="13.3.2" data-path="análise-de-variância.html"><a href="análise-de-variância.html#hipóteses-estatísticas"><i class="fa fa-check"></i><b>13.3.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="13.3.3" data-path="análise-de-variância.html"><a href="análise-de-variância.html#pressupostos-do-modelo"><i class="fa fa-check"></i><b>13.3.3</b> Pressupostos do modelo</a></li>
<li class="chapter" data-level="13.3.4" data-path="análise-de-variância.html"><a href="análise-de-variância.html#verificação-dos-pressupostos-nos-dados-brutos"><i class="fa fa-check"></i><b>13.3.4</b> Verificação dos pressupostos nos dados brutos</a></li>
<li class="chapter" data-level="13.3.5" data-path="análise-de-variância.html"><a href="análise-de-variância.html#verificação-dos-pressupostos-nos-resíduos"><i class="fa fa-check"></i><b>13.3.5</b> Verificação dos pressupostos nos resíduos</a></li>
<li class="chapter" data-level="13.3.6" data-path="análise-de-variância.html"><a href="análise-de-variância.html#realização-do-teste-de-anova-de-dois-fatores"><i class="fa fa-check"></i><b>13.3.6</b> Realização do teste de ANOVA de dois fatores</a></li>
<li class="chapter" data-level="13.3.7" data-path="análise-de-variância.html"><a href="análise-de-variância.html#testes-post-hoc-1"><i class="fa fa-check"></i><b>13.3.7</b> Testes post-hoc</a></li>
<li class="chapter" data-level="13.3.8" data-path="análise-de-variância.html"><a href="análise-de-variância.html#relatando-os-resultados-de-uma-anova-de-dois-fatores"><i class="fa fa-check"></i><b>13.3.8</b> Relatando os resultados de uma ANOVA de dois fatores</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html"><i class="fa fa-check"></i><b>14</b> ANOVA de medidas repetidas</a>
<ul>
<li class="chapter" data-level="14.1" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#anova-de-medidas-repetidas-de-um-fator"><i class="fa fa-check"></i><b>14.1</b> ANOVA de medidas repetidas de um fator</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#pacotes-necessários"><i class="fa fa-check"></i><b>14.1.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="14.1.2" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#preparação-dos-dados"><i class="fa fa-check"></i><b>14.1.2</b> Preparação dos dados</a></li>
<li class="chapter" data-level="14.1.3" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#sumarização-dos-dados"><i class="fa fa-check"></i><b>14.1.3</b> Sumarização dos dados</a></li>
<li class="chapter" data-level="14.1.4" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#visualização-dos-dados-1"><i class="fa fa-check"></i><b>14.1.4</b> Visualização dos dados</a></li>
<li class="chapter" data-level="14.1.5" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#avaliação-dos-pressupostos"><i class="fa fa-check"></i><b>14.1.5</b> Avaliação dos pressupostos</a></li>
<li class="chapter" data-level="14.1.6" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#cálculo-anova-de-medidas-repetidas"><i class="fa fa-check"></i><b>14.1.6</b> Cálculo ANOVA de medidas repetidas</a></li>
<li class="chapter" data-level="14.1.7" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#testes-post-hoc-2"><i class="fa fa-check"></i><b>14.1.7</b> Testes post hoc</a></li>
<li class="chapter" data-level="14.1.8" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial"><i class="fa fa-check"></i><b>14.1.8</b> Relatando os resultados da ANOVA de medidas repetidas unifatorial</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#anova-de-medidas-repetidas-de-dois-fatores"><i class="fa fa-check"></i><b>14.2</b> ANOVA de medidas repetidas de dois fatores</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#preparação-dos-dados-1"><i class="fa fa-check"></i><b>14.2.1</b> Preparação dos dados</a></li>
<li class="chapter" data-level="14.2.2" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#leitura-dos-dados-3"><i class="fa fa-check"></i><b>14.2.2</b> Leitura dos dados</a></li>
<li class="chapter" data-level="14.2.3" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#transformação-dos-dados"><i class="fa fa-check"></i><b>14.2.3</b> Transformação dos dados</a></li>
<li class="chapter" data-level="14.2.4" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#sumarização-dos-dados-1"><i class="fa fa-check"></i><b>14.2.4</b> Sumarização dos dados</a></li>
<li class="chapter" data-level="14.2.5" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#visualização-dos-dados-2"><i class="fa fa-check"></i><b>14.2.5</b> Visualização dos dados</a></li>
<li class="chapter" data-level="14.2.6" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#avaliação-dos-pressupostos-1"><i class="fa fa-check"></i><b>14.2.6</b> Avaliação dos pressupostos</a></li>
<li class="chapter" data-level="14.2.7" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#cálculo-da-anova-de-medidas-de-repetidas"><i class="fa fa-check"></i><b>14.2.7</b> Cálculo da ANOVA de medidas de repetidas</a></li>
<li class="chapter" data-level="14.2.8" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#teste-post-hoc"><i class="fa fa-check"></i><b>14.2.8</b> Teste post hoc</a></li>
<li class="chapter" data-level="14.2.9" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores"><i class="fa fa-check"></i><b>14.2.9</b> Relatando os resultados da ANOVA de medidas repetidas de dois fatores</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html"><i class="fa fa-check"></i><b>15</b> Correlação e Regressão</a>
<ul>
<li class="chapter" data-level="15.1" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#pacotes-necessários-1"><i class="fa fa-check"></i><b>15.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="15.2" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#correlação"><i class="fa fa-check"></i><b>15.2</b> Correlação</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#coeficiente-de-correlação-de-pearson"><i class="fa fa-check"></i><b>15.2.1</b> Coeficiente de correlação de Pearson</a></li>
<li class="chapter" data-level="15.2.2" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#dados-do-exemplo-4"><i class="fa fa-check"></i><b>15.2.2</b> Dados do exemplo</a></li>
<li class="chapter" data-level="15.2.3" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#pressupostos-da-correlação"><i class="fa fa-check"></i><b>15.2.3</b> Pressupostos da Correlação</a></li>
<li class="chapter" data-level="15.2.4" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#execução-do-teste-de-correlação"><i class="fa fa-check"></i><b>15.2.4</b> Execução do teste de correlação</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#regressão-linear-simples"><i class="fa fa-check"></i><b>15.3</b> Regressão Linear Simples</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#resíduos"><i class="fa fa-check"></i><b>15.3.1</b> Resíduos</a></li>
<li class="chapter" data-level="15.3.2" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#análise-dos-pressupostos-do-modelo-de-regressão"><i class="fa fa-check"></i><b>15.3.2</b> Análise dos pressupostos do modelo de regressão</a></li>
<li class="chapter" data-level="15.3.3" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#tamanho-amostral-na-regressão"><i class="fa fa-check"></i><b>15.3.3</b> Tamanho amostral na regressão</a></li>
<li class="chapter" data-level="15.3.4" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#realização-da-regressão-linear"><i class="fa fa-check"></i><b>15.3.4</b> Realização da regressão linear</a></li>
<li class="chapter" data-level="15.3.5" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#visualização-dos-resultados"><i class="fa fa-check"></i><b>15.3.5</b> Visualização dos resultados</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html"><i class="fa fa-check"></i><b>16</b> Análise de Dados Categóricos</a>
<ul>
<li class="chapter" data-level="16.1" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#pacotes-necessários-2"><i class="fa fa-check"></i><b>16.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="16.2" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#sec-qui"><i class="fa fa-check"></i><b>16.2</b> Qui-Quadrado</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#distribuição-qui-quadrado"><i class="fa fa-check"></i><b>16.2.1</b> Distribuição qui-quadrado</a></li>
<li class="chapter" data-level="16.2.2" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#estatística-do-qui-quadrado"><i class="fa fa-check"></i><b>16.2.2</b> Estatística do qui-quadrado</a></li>
<li class="chapter" data-level="16.2.3" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#qui-quadrado-de-independência-ou-associação"><i class="fa fa-check"></i><b>16.2.3</b> Qui-quadrado de independência ou associação</a></li>
<li class="chapter" data-level="16.2.4" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#teste-aderência-ou-do-melhor-ajuste"><i class="fa fa-check"></i><b>16.2.4</b> Teste Aderência ou do Melhor Ajuste</a></li>
<li class="chapter" data-level="16.2.5" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#qui-quadrado-de-pearson-para-tabelas-extensas"><i class="fa fa-check"></i><b>16.2.5</b> Qui-quadrado de Pearson para tabelas extensas</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#teste-exato-de-fisher"><i class="fa fa-check"></i><b>16.3</b> Teste exato de Fisher</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#dados-2"><i class="fa fa-check"></i><b>16.3.1</b> Dados</a></li>
<li class="chapter" data-level="16.3.2" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#entrando-com-os-dados"><i class="fa fa-check"></i><b>16.3.2</b> Entrando com os dados</a></li>
<li class="chapter" data-level="16.3.3" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#hipóteses-estatísticas-4"><i class="fa fa-check"></i><b>16.3.3</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="16.3.4" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#execução-do-teste-estatístico-2"><i class="fa fa-check"></i><b>16.3.4</b> Execução do teste estatístico</a></li>
<li class="chapter" data-level="16.3.5" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#conclusão-6"><i class="fa fa-check"></i><b>16.3.5</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#teste-de-macnemar"><i class="fa fa-check"></i><b>16.4</b> Teste de Macnemar</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#pressupostos-do-teste-de-mcnemar"><i class="fa fa-check"></i><b>16.4.1</b> Pressupostos do teste de McNemar</a></li>
<li class="chapter" data-level="16.4.2" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#dados-3"><i class="fa fa-check"></i><b>16.4.2</b> Dados</a></li>
<li class="chapter" data-level="16.4.3" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#hipóteses-estatísticas-5"><i class="fa fa-check"></i><b>16.4.3</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="16.4.4" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#lógica-do-teste-1"><i class="fa fa-check"></i><b>16.4.4</b> Lógica do teste</a></li>
<li class="chapter" data-level="16.4.5" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#cálculo-do-teste-de-mcnemar-no-r"><i class="fa fa-check"></i><b>16.4.5</b> Cálculo do teste de McNemar no R</a></li>
<li class="chapter" data-level="16.4.6" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#conclusão-7"><i class="fa fa-check"></i><b>16.4.6</b> Conclusão</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html"><i class="fa fa-check"></i><b>17</b> Métodos não paramétricos</a>
<ul>
<li class="chapter" data-level="17.1" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#pacotes-necessários-3"><i class="fa fa-check"></i><b>17.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="17.2" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#distribuição-livre"><i class="fa fa-check"></i><b>17.2</b> Distribuição livre</a></li>
<li class="chapter" data-level="17.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#postos"><i class="fa fa-check"></i><b>17.3</b> Postos</a></li>
<li class="chapter" data-level="17.4" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#teste-de-mann-whitney"><i class="fa fa-check"></i><b>17.4</b> Teste de Mann-Whitney</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#dados-4"><i class="fa fa-check"></i><b>17.4.1</b> Dados</a></li>
<li class="chapter" data-level="17.4.2" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#hipóteses-estatísticas-6"><i class="fa fa-check"></i><b>17.4.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="17.4.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#pressupostos-do-teste-de-mann_whitney"><i class="fa fa-check"></i><b>17.4.3</b> Pressupostos do teste de Mann_Whitney</a></li>
<li class="chapter" data-level="17.4.4" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#execução-do-teste-estatístico-3"><i class="fa fa-check"></i><b>17.4.4</b> Execução do teste estatístico</a></li>
<li class="chapter" data-level="17.4.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#tamanho-do-efeito-3"><i class="fa fa-check"></i><b>17.4.5</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="17.4.6" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#conclusão-8"><i class="fa fa-check"></i><b>17.4.6</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#teste-de-wilcoxon"><i class="fa fa-check"></i><b>17.5</b> Teste de Wilcoxon</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#dados-5"><i class="fa fa-check"></i><b>17.5.1</b> Dados</a></li>
<li class="chapter" data-level="17.5.2" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#definição-das-hipóteses-estatísticas-3"><i class="fa fa-check"></i><b>17.5.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="17.5.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#execução-do-teste-estatístico-4"><i class="fa fa-check"></i><b>17.5.3</b> Execução do teste estatístico</a></li>
<li class="chapter" data-level="17.5.4" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#tamanho-do-efeito-4"><i class="fa fa-check"></i><b>17.5.4</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="17.5.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#conclusão-9"><i class="fa fa-check"></i><b>17.5.5</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#teste-de-kruskal-wallis"><i class="fa fa-check"></i><b>17.6</b> Teste de Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="17.6.1" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#dados-6"><i class="fa fa-check"></i><b>17.6.1</b> Dados</a></li>
<li class="chapter" data-level="17.6.2" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#hipóteses-estatísticas-7"><i class="fa fa-check"></i><b>17.6.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="17.6.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#pressupostos-do-teste-2"><i class="fa fa-check"></i><b>17.6.3</b> Pressupostos do teste</a></li>
<li class="chapter" data-level="17.6.4" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#execução-do-teste-estatístico-5"><i class="fa fa-check"></i><b>17.6.4</b> Execução do teste estatístico</a></li>
<li class="chapter" data-level="17.6.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#tamanho-do-efeito-5"><i class="fa fa-check"></i><b>17.6.5</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="17.6.6" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#testes-post-hoc-3"><i class="fa fa-check"></i><b>17.6.6</b> Testes post hoc</a></li>
<li class="chapter" data-level="17.6.7" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#conclusão-10"><i class="fa fa-check"></i><b>17.6.7</b> Conclusão</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="sec-cap18.html"><a href="sec-cap18.html"><i class="fa fa-check"></i><b>18</b> Estatística em Epidemiologia</a>
<ul>
<li class="chapter" data-level="18.1" data-path="sec-cap18.html"><a href="sec-cap18.html#pacotes-necessários-4"><i class="fa fa-check"></i><b>18.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="18.2" data-path="sec-cap18.html"><a href="sec-cap18.html#sec-diagbayes"><i class="fa fa-check"></i><b>18.2</b> Raciocínio bayesiano no diagnóstico médico</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="sec-cap18.html"><a href="sec-cap18.html#sensibilidade-e-especificidade"><i class="fa fa-check"></i><b>18.2.1</b> Sensibilidade e Especificidade</a></li>
<li class="chapter" data-level="18.2.2" data-path="sec-cap18.html"><a href="sec-cap18.html#valor-preditivo"><i class="fa fa-check"></i><b>18.2.2</b> Valor Preditivo</a></li>
<li class="chapter" data-level="18.2.3" data-path="sec-cap18.html"><a href="sec-cap18.html#razão-de-probabilidade"><i class="fa fa-check"></i><b>18.2.3</b> Razão de Probabilidade</a></li>
<li class="chapter" data-level="18.2.4" data-path="sec-cap18.html"><a href="sec-cap18.html#curva-roc"><i class="fa fa-check"></i><b>18.2.4</b> Curva ROC</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="sec-cap18.html"><a href="sec-cap18.html#estatística-kappa"><i class="fa fa-check"></i><b>18.3</b> Estatística <em>kappa</em></a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="sec-cap18.html"><a href="sec-cap18.html#exemplo-3"><i class="fa fa-check"></i><b>18.3.1</b> Exemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="sec-cap18.html"><a href="sec-cap18.html#medidas-de-frequência"><i class="fa fa-check"></i><b>18.4</b> Medidas de frequência</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="sec-cap18.html"><a href="sec-cap18.html#prevalência"><i class="fa fa-check"></i><b>18.4.1</b> Prevalência</a></li>
<li class="chapter" data-level="18.4.2" data-path="sec-cap18.html"><a href="sec-cap18.html#incidência"><i class="fa fa-check"></i><b>18.4.2</b> Incidência</a></li>
<li class="chapter" data-level="18.4.3" data-path="sec-cap18.html"><a href="sec-cap18.html#relação-entre-prevalência-e-incidência"><i class="fa fa-check"></i><b>18.4.3</b> Relação entre prevalência e incidência</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="sec-cap18.html"><a href="sec-cap18.html#medidas-de-associação"><i class="fa fa-check"></i><b>18.5</b> Medidas de associação</a>
<ul>
<li class="chapter" data-level="18.5.1" data-path="sec-cap18.html"><a href="sec-cap18.html#sec-or"><i class="fa fa-check"></i><b>18.5.1</b> <em>Odds Ratio</em></a></li>
<li class="chapter" data-level="18.5.2" data-path="sec-cap18.html"><a href="sec-cap18.html#sec-rr"><i class="fa fa-check"></i><b>18.5.2</b> Risco Relativo</a></li>
<li class="chapter" data-level="18.5.3" data-path="sec-cap18.html"><a href="sec-cap18.html#odds-ratio-vs-risco-relativo"><i class="fa fa-check"></i><b>18.5.3</b> <em>Odds Ratio</em> vs Risco Relativo</a></li>
<li class="chapter" data-level="18.5.4" data-path="sec-cap18.html"><a href="sec-cap18.html#razão-de-prevalência"><i class="fa fa-check"></i><b>18.5.4</b> Razão de Prevalência</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="sec-cap18.html"><a href="sec-cap18.html#medidas-de-impacto"><i class="fa fa-check"></i><b>18.6</b> Medidas de impacto</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="sec-cap18.html"><a href="sec-cap18.html#risco-atribuível"><i class="fa fa-check"></i><b>18.6.1</b> Risco Atribuível</a></li>
<li class="chapter" data-level="18.6.2" data-path="sec-cap18.html"><a href="sec-cap18.html#redução-relativa-do-risco"><i class="fa fa-check"></i><b>18.6.2</b> Redução Relativa do Risco</a></li>
<li class="chapter" data-level="18.6.3" data-path="sec-cap18.html"><a href="sec-cap18.html#número-necessário-para-tratar"><i class="fa fa-check"></i><b>18.6.3</b> Número Necessário para Tratar</a></li>
<li class="chapter" data-level="18.6.4" data-path="sec-cap18.html"><a href="sec-cap18.html#número-necessário-para-causar-dano"><i class="fa fa-check"></i><b>18.6.4</b> Número Necessário para Causar Dano</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="sec-cap18.html"><a href="sec-cap18.html#análise-de-sobrevida"><i class="fa fa-check"></i><b>18.7</b> Análise de sobrevida</a>
<ul>
<li class="chapter" data-level="18.7.1" data-path="sec-cap18.html"><a href="sec-cap18.html#dados-censurados"><i class="fa fa-check"></i><b>18.7.1</b> Dados Censurados</a></li>
<li class="chapter" data-level="18.7.2" data-path="sec-cap18.html"><a href="sec-cap18.html#método-de-kaplan-meier"><i class="fa fa-check"></i><b>18.7.2</b> Método de Kaplan-Meier</a></li>
</ul></li>
<li class="chapter" data-level="18.8" data-path="sec-cap18.html"><a href="sec-cap18.html#regressão-logística-binária"><i class="fa fa-check"></i><b>18.8</b> Regressão logística binária</a>
<ul>
<li class="chapter" data-level="18.8.1" data-path="sec-cap18.html"><a href="sec-cap18.html#pressupostos-da-regressão-logística"><i class="fa fa-check"></i><b>18.8.1</b> Pressupostos da regressão logística</a></li>
<li class="chapter" data-level="18.8.2" data-path="sec-cap18.html"><a href="sec-cap18.html#dados-para-a-regressão-logística"><i class="fa fa-check"></i><b>18.8.2</b> Dados para a regressão logística</a></li>
<li class="chapter" data-level="18.8.3" data-path="sec-cap18.html"><a href="sec-cap18.html#preparação-dos-dados-2"><i class="fa fa-check"></i><b>18.8.3</b> Preparação dos dados</a></li>
<li class="chapter" data-level="18.8.4" data-path="sec-cap18.html"><a href="sec-cap18.html#criação-do-modelo-de-regressão-enter"><i class="fa fa-check"></i><b>18.8.4</b> Criação do modelo de regressão (<em>enter</em>)</a></li>
<li class="chapter" data-level="18.8.5" data-path="sec-cap18.html"><a href="sec-cap18.html#criação-do-modelo-passo-a-passo-stepwise"><i class="fa fa-check"></i><b>18.8.5</b> Criação do modelo passo-a-passo (<em>stepwise</em>)</a></li>
<li class="chapter" data-level="18.8.6" data-path="sec-cap18.html"><a href="sec-cap18.html#uso-do-modelo-para-fazer-predições"><i class="fa fa-check"></i><b>18.8.6</b> Uso do modelo para fazer predições</a></li>
<li class="chapter" data-level="18.8.7" data-path="sec-cap18.html"><a href="sec-cap18.html#avaliação-do-modelo"><i class="fa fa-check"></i><b>18.8.7</b> Avaliação do modelo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="referências.html"><a href="referências.html"><i class="fa fa-check"></i>Referências</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introdução à Bioestatística usando o R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introdução-à-teoria-das-probabilidades" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Capítulo 7</span> Introdução à Teoria das Probabilidades<a href="introdução-à-teoria-das-probabilidades.html#introdução-à-teoria-das-probabilidades" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introdução-1" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Introdução<a href="introdução-à-teoria-das-probabilidades.html#introdução-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A teoria das probabilidades é a base sobre a qual a estatística é desenvolvida. Os jogos de azar deram um grande impulso ao conhecimento da moderna teoria das probabilidades, principalmente, pelo trabalho de Blaise Pascal (1623-1662), em parceria com Pierre de Fermat (1601-1665). Eles foram estimulados por um escritor francês e matemático amador, Antoine Gombaud (1607-1684), conhecido como Chevalier de Méré, que era muito interessados em jogos de azar<span class="citation">(83)</span>.</p>
<p>A Teoria das probabilidades permite que seja possível modelar populações, experimentos ou qualquer situação que possa ser considerada aleatória. Estes modelos possibilitam fazer inferência sobre populações a partir da observação de uma amostra dessa população. Ao usar apenas uma parte da população, inevitavelmente, é cometido um erro o <em>erro amostral</em>. Este erro amostral pode ser dimensionado pela teoria das probabilidades.</p>
<p>Existem duas interpretações alternativas de probabilidades: a <em>frequentista</em> e a <em>bayesiana</em> <span class="citation">(84)</span>. Neste livro, será discutida, basicamente, a definição de probabilidade frequentista. O processo bayesiano de formulação de um modelo probabilístico faz uso do conhecimento subjetivo, estabelecendo uma especificação <em>a priori</em>, combinado com a informação objetiva ou empírica. A teoria bayesiana é a estrutura integradora dessas duas fontes de informação, derivando como resultado a distribuição <em>a posteriori</em> dos parâmetros de interesse. Na seção <a href="sec-cap18.html#sec-diagbayes">18.2</a>, sobre análise de testes diagnósticos, será abordado alguns aspectos relacionados a teoria bayesiana em medicina.</p>
</div>
<div id="processo-aleatório" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Processo aleatório<a href="introdução-à-teoria-das-probabilidades.html#processo-aleatório" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Um processo ou experimento é dito <em>aleatório</em> quando em uma situação se sabe quais os resultados que podem acontecer, mas não se sabe qual resultado particular irá acontecer. Por exemplo, quando uma moeda é lançada, se conhece que a probabilidade de o desfecho cara ocorrer é de 50%, mas se desconhece o que irá ocorrer até que a moeda esteja no chão.</p>
<p>O número de caras que podem surgir em vários lançamentos da moeda é chamado de <em>variável aleatória</em>, ou seja, uma variável que pode assumir mais de um valor com determinadas probabilidades <span class="citation">(85)</span>. Da mesma forma, um dado lançado pode mostrar seis faces, numeradas de um a seis, com igual probabilidade de 16,7%. Portanto, quando a probabilidade é associada a todos os conjuntos de valores possíveis de uma variável, diz-se que ela é aleatória. O conjunto de todos os possíveis resultados de um experimento aleatório é denominado <em>espaço amostral</em>.</p>
<p>Na área da saúde, trabalha-se com uma infinidade de variáveis aleatórias, por exemplo, o número de filhos de uma mulher, o número de mortos diários em uma epidemia, o número de vacinados em uma campanha, etc. Essas variáveis são a variáveis aleatórias discretas, pois apenas permitem ser quantificadas por processo de contagem. Por outro lado, o peso, a altura de uma mulher são ditos variáveis aleatórias contínuas, pois podem assumir qualquer valor real entre uma medida e outra, dependendo da precisão do aparelho usado.</p>
<p>Em geral, <em>variáveis aleatórias</em> são representadas por letras maiúsculas, como X, Y e Z e sua a probabilidade pode ser denotada por:</p>
<p><span class="math display">\[
P[X] \quad ou \quad P[X=x]
\]</span></p>
</div>
<div id="definição-frequentista-de-probabilidade" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Definição frequentista de probabilidade<a href="introdução-à-teoria-das-probabilidades.html#definição-frequentista-de-probabilidade" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A probabilidade se relaciona a eventos futuros ou que ainda não ocorreram, desta forma a probabilidade pode ser entendida como uma medida de incerteza em relação ao evento. A probabilidade de um evento ocorrer, em determinadas circunstâncias, pode ser definida como a proporção de vezes que o evento é observado quando o experimento é repetido um número infinitamente grande de vezes <span class="citation">(84)</span>.</p>
<p>A chamada <em>Lei dos Grandes Números</em> diz que à medida que múltiplas observações são coletadas, a proporção observada de ocorrências de um determinado desfecho, após <em>n</em> ensaios, converge para a probabilidade real <em>P</em> desse desfecho. Ou seja, quanto mais vezes for repetido uma experiência, a melhor estimativa de probabilidade tende a ocorrer.</p>
<p>O resultado dos comandos abaixo simulam 1000 lançamentos de uma moeda, mostrando que quando chega próximo de 300 lançamentos, a probabilidade se mantém praticamente constante em torno de 50% (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:coin">7.1</a>).</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="introdução-à-teoria-das-probabilidades.html#cb406-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span></span>
<span id="cb406-2"><a href="introdução-à-teoria-das-probabilidades.html#cb406-2" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span><span class="fu">cumsum</span> (<span class="fu">sample</span> (<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,<span class="dv">1000</span>, <span class="at">rep=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="introdução-à-teoria-das-probabilidades.html#cb407-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (x,y<span class="sc">/</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, </span>
<span id="cb407-2"><a href="introdução-à-teoria-das-probabilidades.html#cb407-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab=</span><span class="st">&quot;Probabilidade&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Lançamentos da moeda&quot;</span>,</span>
<span id="cb407-3"><a href="introdução-à-teoria-das-probabilidades.html#cb407-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylim=</span><span class="fu">c</span> (<span class="fl">0.3</span>,<span class="fl">0.8</span>), <span class="at">xlim=</span><span class="fu">c</span> (<span class="dv">0</span>,<span class="dv">1000</span>), </span>
<span id="cb407-4"><a href="introdução-à-teoria-das-probabilidades.html#cb407-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch=</span><span class="dv">16</span>, </span>
<span id="cb407-5"><a href="introdução-à-teoria-das-probabilidades.html#cb407-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">col=</span><span class="st">&quot;steelblue&quot;</span>)</span>
<span id="cb407-6"><a href="introdução-à-teoria-das-probabilidades.html#cb407-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.5</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:coin"></span>
<img src="bookdownproj_files/figure-html/coin-1.png" alt="Simulação do lançamento de 1000 moedas." width="70%" height="70%" />
<p class="caption">
Figure 7.1: Simulação do lançamento de 1000 moedas.
</p>
</div>
<p>A definição frequentista também pode ser aplicada a uma medida contínua como a altura de mulheres. No conjunto de dados <code>dadosMater.xlsx</code> (veja seção <a href="manipulando-os-dados-no-r-studio.html#sec-mater">5.3</a>), encontra-se o registro da altura de 1368 mulheres. Esssas alturas serão selecionadas e colocadass em um objeto <code>am</code> (<strong>a</strong>ltura das <strong>m</strong>ulheres*):</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="introdução-à-teoria-das-probabilidades.html#cb408-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb408-2"><a href="introdução-à-teoria-das-probabilidades.html#cb408-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb408-3"><a href="introdução-à-teoria-das-probabilidades.html#cb408-3" aria-hidden="true" tabindex="-1"></a>am <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Arquivos/dadosMater.xlsx&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb408-4"><a href="introdução-à-teoria-das-probabilidades.html#cb408-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(altura)</span>
<span id="cb408-5"><a href="introdução-à-teoria-das-probabilidades.html#cb408-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (am)</span></code></pre></div>
<pre><code>##      altura     
##  Min.   :1.400  
##  1st Qu.:1.550  
##  Median :1.600  
##  Mean   :1.598  
##  3rd Qu.:1.650  
##  Max.   :1.850</code></pre>
<p>A mediana da altura das gestantes é 1,60 m. Ou seja, metade dessas mulheres têm uma altura acima de 1,60 m. Em um longo conjunto de sorteios, a probabilidade de uma mulher ter altura acima de 1,60 m é 50%. O percentil 75 (3º quartil) é igual a 1,65 m, a probabilidade de estar acima deste valor, portanto, é 25%. É possível encontrar a probabilidade de a altura estar acima, abaixo ou entre quaisquer valores. Quando se faz a mensuração de uma variável contínua, fica-se limitado ao método usado, portanto, quando se diz que uma mulher tem 1,60 m, significa dizer que está entre 159,5 e 165,5 m, dependendo da precisão do instrumento de medição.</p>
<p>Logo, o interesse está na probabilidade de a variável aleatória assumir valores entre certos limites. A probabilidade de encontrar um valor exatamente de 1,60 m é quase igual a zero (na realidade, <span class="math inline">\(2.7 \times 10^{-124}\)</span>).</p>
<p>Como se verá adiante, isto pode ser facilmente calculado no R:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="introdução-à-teoria-das-probabilidades.html#cb410-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distância do valor de 1,60 e a média em desvios padrão (escores Z) </span></span>
<span id="cb410-2"><a href="introdução-à-teoria-das-probabilidades.html#cb410-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (<span class="fl">1.60</span> <span class="sc">-</span> <span class="fu">mean</span>(am<span class="sc">$</span>altura))<span class="sc">/</span><span class="fu">sd</span>(am<span class="sc">$</span>altura)</span>
<span id="cb410-3"><a href="introdução-à-teoria-das-probabilidades.html#cb410-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb410-4"><a href="introdução-à-teoria-das-probabilidades.html#cb410-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidade </span></span>
<span id="cb410-5"><a href="introdução-à-teoria-das-probabilidades.html#cb410-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span> (z, <span class="fu">mean</span>(am<span class="sc">$</span>altura),<span class="fu">sd</span>(am<span class="sc">$</span>altura))</span></code></pre></div>
<pre><code>## [1] 7.387473e-127</code></pre>
</div>
<div id="propriedades-das-probabilidades" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Propriedades das probabilidades<a href="introdução-à-teoria-das-probabilidades.html#propriedades-das-probabilidades" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As seguintes propriedades simples decorrem da definição de probabilidade.</p>
<p>Sendo <code>E</code> um evento aleatório, a <span class="math inline">\(P[E]\)</span> está entre 0 e 1, ou seja <span class="math inline">\(0\le P[E]\le 1\)</span>. Quando o evento certamente não ocorre, a probabilidade é 0, quando sempre ocorre a probabilidade é 1. Quando a probabilidade for igual a 0,50 tem-se máxima incerteza.</p>
<ol style="list-style-type: decimal">
<li><em>Regra de adição (regra do “ou”)</em></li>
</ol>
<p>Dois eventos A e B são mutuamente exclusivos, ou seja, quando A acontece, B não pode acontecer. Então, a probabilidade de que um ou outro aconteça é a soma de suas probabilidades. Por exemplo, um dado lançado pode mostrar um ou dois, mas não ambos. A probabilidade de mostrar um ou dois é igual a <span class="math inline">\(1/6 + 1/6 = 1/3\)</span>.</p>
<p><span class="math display">\[
P[A ou B]=P[A]+P[B]
\]</span>
Se A e B não são mutuamente exclusivos, ou seja, quando A acontece pode também ocorrer B. Por exemplo, o nascimento de uma menina pode ser concomitante com o fato de ser branca.</p>
<p><span class="math display">\[
P[A ou B]=P[A]+P[B]-P[A \space e \space B]
\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li><em>Regra de multiplicação (regra do “e”)</em></li>
</ol>
<p>Suponha que dois eventos (A e B) sejam independentes, ou seja, saber que um aconteceu não nos diz nada sobre se o outro aconteceu. Então, a probabilidade de que ambos aconteçam é o produto de suas probabilidades. Por exemplo, suponha que jogamos duas moedas. Uma moeda não influencia a outra, portanto os resultados dos dois lançamentos são independentes e a probabilidade de ocorrerem duas caras é 050 × 0,50 = 0,25.</p>
<p><span class="math display">\[
P[A \quad e\quad B]=P[A]×P[B]
\]</span></p>
<p>Se os eventos são dependentes, a probabilidade que ambos aconteçam é igual a:</p>
<p><span class="math display">\[
P[A \quad e \quad B]=P[A]×P[B \rvert A]
\]</span></p>
</div>
<div id="distribuição-de-probabilidades" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Distribuição de Probabilidades<a href="introdução-à-teoria-das-probabilidades.html#distribuição-de-probabilidades" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Um conjunto de eventos que são mutuamente excludentes e que inclui todos os eventos que podem acontecer, é chamado de exaustivo. A soma de suas probabilidades é 1. O conjunto dessas probabilidades constitui uma <em>distribuição de probabilidade</em>.</p>
<p>Existem diversos modelos probabilísticos que procuram descrever vários tipos de variáveis aleatórias discretas ou contínuas. Estas distribuições também são chamadas de <em>modelos probabilísticos estocástico</em> que são definidas por duas funções matemáticas: a <em>função de probabilidade</em> (fp) para variáveis discretas, que atribui a cada valor a sua probabilidade de ocorrência (<code>P(X=x</code>)) e <em>função densidade de probabilidade</em> (fdp) para variáveis contínuas.</p>
<p>A função de probabilidade é a função que atribui probabilidades a cada um dos possíveis valores da variável aleatória discreta, usando, em geral, as frequências relativas, apresentadas em uma tabela de frequência. O <em>modelo de Bernoulli</em> ou <em>Binomial</em> e o <em>modelo de Poisson</em> são exemplos de modelo probabilístico de variáveis discretas.</p>
<p>A função densidade de probabilidade é a função que atribui probabilidade a qualquer intervalo de número reais, ou seja, um conjunto de valores não enumerável (infinito). Não é possível atribuir probabilidades para um determinado valor, é possível apenas para um intervalo. Por exemplo, o peso dos recém-nascidos. Para atribuir probabilidade a intervalos de valores é utilizada uma função e as probabilidades são representadas por áreas. Existem diversos modelos contínuos de probabilidade, mas o mais importante deles, é o <em>modelo normal</em>, também conhecido como <em>modelo gaussiano</em>.</p>
</div>
<div id="distribuição-normal" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Distribuição Normal<a href="introdução-à-teoria-das-probabilidades.html#distribuição-normal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O <em>modelo probabilístico normal</em> ou <em>gaussiano</em> é extremamente importante em estatística, pois serve como um fundamento para técnicas de inferência. Variáveis como os pesos dos recém-nascidos a termo, as alturas das mulheres adultas, a renda familiar em reais e muitas outras variáveis, na natureza, se ajustam ao modelo da distribuição normal.</p>
<p>O modelo de distribuição normal sempre descreve uma curva simétrica, unimodal e em forma de sino (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:curvanormal">7.2</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:curvanormal"></span>
<img src="bookdownproj_files/figure-html/curvanormal-1.png" alt="Curva normal." width="70%" height="70%" />
<p class="caption">
Figure 7.2: Curva normal.
</p>
</div>
<p>No entanto, essas curvas podem parecer diferentes dependendo dos detalhes do modelo. Especificamente, o modelo de distribuição normal pode ser ajustado usando dois parâmetros: <em>média</em> e <em>desvio padrão</em>.</p>
<p>Como é fácil prever, alterar a média desloca a curva de sino para a esquerda ou para a direita, enquanto a alteração do desvio padrão estende ou achata a curva, ou seja, muda a dispersão da distribuição.</p>
<p>A Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:threecurves">7.3</a>, mostra a distribuição normal com média 0 e desvio padrão 1, na curva à direita, a distribuição normal com média 1.5 e desvio padrão 1. Sobrepondo-se à curva da esquerda observa-se uma curva mais achatada (verde) que tem média 0 e desvio padrão 1.5. Observa-se, como mencionado, que modificando os parâmetros da curva, altera-se a posição ou o formato da curva.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="introdução-à-teoria-das-probabilidades.html#cb412-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span> (<span class="fu">dnorm</span> (x, </span>
<span id="cb412-2"><a href="introdução-à-teoria-das-probabilidades.html#cb412-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">mean=</span><span class="dv">0</span>, </span>
<span id="cb412-3"><a href="introdução-à-teoria-das-probabilidades.html#cb412-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd=</span><span class="dv">1</span>), </span>
<span id="cb412-4"><a href="introdução-à-teoria-das-probabilidades.html#cb412-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">&quot;dodgerblue3&quot;</span>, </span>
<span id="cb412-5"><a href="introdução-à-teoria-das-probabilidades.html#cb412-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span>,</span>
<span id="cb412-6"><a href="introdução-à-teoria-das-probabilidades.html#cb412-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>,</span>
<span id="cb412-7"><a href="introdução-à-teoria-das-probabilidades.html#cb412-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>),</span>
<span id="cb412-8"><a href="introdução-à-teoria-das-probabilidades.html#cb412-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">4.5</span>, <span class="fl">4.5</span>),</span>
<span id="cb412-9"><a href="introdução-à-teoria-das-probabilidades.html#cb412-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Densidade&quot;</span>,</span>
<span id="cb412-10"><a href="introdução-à-teoria-das-probabilidades.html#cb412-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;X&quot;</span>,</span>
<span id="cb412-11"><a href="introdução-à-teoria-das-probabilidades.html#cb412-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb412-12"><a href="introdução-à-teoria-das-probabilidades.html#cb412-12" aria-hidden="true" tabindex="-1"></a><span class="fu">box</span>(<span class="at">bty =</span> <span class="st">&quot;L&quot;</span>)</span>
<span id="cb412-13"><a href="introdução-à-teoria-das-probabilidades.html#cb412-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (<span class="at">v=</span> <span class="dv">0</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;dodgerblue3&quot;</span>)</span>
<span id="cb412-14"><a href="introdução-à-teoria-das-probabilidades.html#cb412-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb412-15"><a href="introdução-à-teoria-das-probabilidades.html#cb412-15" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span> (<span class="fu">dnorm</span> (x, </span>
<span id="cb412-16"><a href="introdução-à-teoria-das-probabilidades.html#cb412-16" aria-hidden="true" tabindex="-1"></a>              <span class="at">mean=</span><span class="dv">0</span>, </span>
<span id="cb412-17"><a href="introdução-à-teoria-das-probabilidades.html#cb412-17" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd=</span><span class="fl">1.5</span>), </span>
<span id="cb412-18"><a href="introdução-à-teoria-das-probabilidades.html#cb412-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">&quot;darkolivegreen3&quot;</span>, </span>
<span id="cb412-19"><a href="introdução-à-teoria-das-probabilidades.html#cb412-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span>,</span>
<span id="cb412-20"><a href="introdução-à-teoria-das-probabilidades.html#cb412-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>,</span>
<span id="cb412-21"><a href="introdução-à-teoria-das-probabilidades.html#cb412-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">add=</span>T)</span>
<span id="cb412-22"><a href="introdução-à-teoria-das-probabilidades.html#cb412-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb412-23"><a href="introdução-à-teoria-das-probabilidades.html#cb412-23" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span> (<span class="fu">dnorm</span> (x, </span>
<span id="cb412-24"><a href="introdução-à-teoria-das-probabilidades.html#cb412-24" aria-hidden="true" tabindex="-1"></a>              <span class="at">mean=</span><span class="fl">1.5</span>, </span>
<span id="cb412-25"><a href="introdução-à-teoria-das-probabilidades.html#cb412-25" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd=</span><span class="dv">1</span>), </span>
<span id="cb412-26"><a href="introdução-à-teoria-das-probabilidades.html#cb412-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">&quot;firebrick3&quot;</span>, </span>
<span id="cb412-27"><a href="introdução-à-teoria-das-probabilidades.html#cb412-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span>,</span>
<span id="cb412-28"><a href="introdução-à-teoria-das-probabilidades.html#cb412-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>,</span>
<span id="cb412-29"><a href="introdução-à-teoria-das-probabilidades.html#cb412-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">add=</span>T)</span>
<span id="cb412-30"><a href="introdução-à-teoria-das-probabilidades.html#cb412-30" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (<span class="at">v=</span> <span class="dv">0</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;firebrick3&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:threecurves"></span>
<img src="bookdownproj_files/figure-html/threecurves-1.png" alt="Curvas normais com modificação dos parâmetros." width="70%" height="70%" />
<p class="caption">
Figure 7.3: Curvas normais com modificação dos parâmetros.
</p>
</div>
<div id="características-da-distribuição-normal" class="section level3 hasAnchor" number="7.6.1">
<h3><span class="header-section-number">7.6.1</span> Características da distribuição normal<a href="introdução-à-teoria-das-probabilidades.html#características-da-distribuição-normal" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A curva normal apresenta as seguintes características:</p>
<ul>
<li>A média e o desvio padrão descrevem exatamente uma distribuição normal, eles são chamados de parâmetros da distribuição. Se uma distribuição normal tem média <span class="math inline">\(\mu\)</span> e desvio padrão <span class="math inline">\(\sigma\)</span>, pode-se escrever a distribuição como <span class="math inline">\(N (\mu,\sigma)\)</span>. As três distribuições do gráfico anterior. podem ser escritas como:</li>
</ul>
<p><span class="math display">\[
N(\mu = 0,\sigma = 1) \quad, N(\mu = 0,\sigma = 1.5) \quad  e \quad  N(\mu = 1.5,\sigma = 1)
\]</span></p>
<ul>
<li>Na distribuição normal, a média, a mediana e a moda coincidem.</li>
<li>A curva normal é simétrica em torno da média (<span class="math inline">\(\mu\)</span>).</li>
<li>As extremidades da curva, em ambos os lados da média, se estendem cada vez mais próximas do eixo <em>x</em> (abscissa) sem jamais tocá-lo. É assintótica.</li>
<li>Os pontos de inflexão da curva são <span class="math inline">\(\mu - \sigma\)</span> e <span class="math inline">\(\mu + \sigma\)</span>.</li>
<li>A área total sob a curva é 1 ou 100%.</li>
</ul>
</div>
<div id="sec-dnp" class="section level3 hasAnchor" number="7.6.2">
<h3><span class="header-section-number">7.6.2</span> Distribuição normal padronizada<a href="introdução-à-teoria-das-probabilidades.html#sec-dnp" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cada variável aleatória contínua tem a sua média e seu desvio padrão e, portanto, a sua curva normal correspondente.</p>
<p>Para facilitar a comparação entre variáveis, foi criado o conceito de <strong>curva normal padronizada</strong>, que é uma curva normal com média 0 e desvio padrão 1. A distribuição normal padrão também pode ser chamada de <em>distribuição normal centrada</em> ou <em>reduzida</em>.</p>
<p>Para calcular probabilidades associadas a distribuição normal, costuma-se converter a variável aleatória original <em>X</em>, em unidades reduzidas ou padronizadas, denominadas de <strong>escore <em>Z</em></strong>.</p>
<p>Esta transformação é realizada pela equação que indica o número de desvios padrão envolvidos no afastamento do valor <em>x</em> em relação à média:</p>
<p><span class="math display">\[
z =\frac{x-\mu}{\sigma}
\]</span>
onde:</p>
<ul>
<li><em>z</em> <span class="math inline">\(\longrightarrow\)</span> escore z<br />
</li>
<li><em>x</em> <span class="math inline">\(\longrightarrow\)</span> valor qualquer da variável aleatória <em>X</em><br />
</li>
<li><em><span class="math inline">\(\mu\)</span></em> <span class="math inline">\(\longrightarrow\)</span> média da variável <em>X</em><br />
</li>
<li><em><span class="math inline">\(\sigma\)</span></em> <span class="math inline">\(\longrightarrow\)</span> desvio padrão da variável <em>X</em></li>
</ul>
<p>Qualquer distribuição de uma variável aleatória normal pode ser padronizada, usando o escore <em>z</em>. Isto permite que se calcule a probabilidade de se encontrar determinados intervalos de valores <span class="citation">(86)</span>.</p>
<p>A altura das puérperas do conjunto de dados <code>dadosMater.xlsx</code> tem as seguintes medidas resumidoras:</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="introdução-à-teoria-das-probabilidades.html#cb413-1" aria-hidden="true" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> am <span class="sc">%&gt;%</span> </span>
<span id="cb413-2"><a href="introdução-à-teoria-das-probabilidades.html#cb413-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb413-3"><a href="introdução-à-teoria-das-probabilidades.html#cb413-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">media =</span> <span class="fu">mean</span>(altura, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb413-4"><a href="introdução-à-teoria-das-probabilidades.html#cb413-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dp =</span> <span class="fu">sd</span>(altura, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb413-5"><a href="introdução-à-teoria-das-probabilidades.html#cb413-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">min =</span> <span class="fu">min</span>(altura, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb413-6"><a href="introdução-à-teoria-das-probabilidades.html#cb413-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">max =</span> <span class="fu">max</span>(altura, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb413-7"><a href="introdução-à-teoria-das-probabilidades.html#cb413-7" aria-hidden="true" tabindex="-1"></a>resumo                    </span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##       n media     dp   min   max
##   &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1368  1.60 0.0655   1.4  1.85</code></pre>
<p>Desta forma, pode-se verificar quantos desvios padrão uma mulher que mede 1,725m, pertencente a esta população, está afastada da média de 1.6m. Assim:</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="introdução-à-teoria-das-probabilidades.html#cb415-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (<span class="fl">1.725</span> <span class="sc">-</span> resumo<span class="sc">$</span>media)<span class="sc">/</span>resumo<span class="sc">$</span>dp</span>
<span id="cb415-2"><a href="introdução-à-teoria-das-probabilidades.html#cb415-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(z, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.94</code></pre>
<p>Esta mulher está distante praticamente 2 desvios padrão acima da média da sua população. Portanto, ela é considerada alta. Por que?</p>
<p>Para responder a essa pergunta, há necessidade de calcular a probabilidade de encontrar uma mulher com esta altura, nesta população.</p>
<p>No <em>R</em>, existem as funções <code>dnorm()</code>, <code>pnorm()</code> e <code>qnorm()</code>, que permitem calcular a <em>densidade de probabilidade</em>, <em>distribuição cumulativa</em> e <em>função quantílica da distribuição normal</em> para um conjunto de valores. Além disso, a função <code>rnorm()</code> permite obter observações aleatórias que seguem uma distribuição normal <span class="citation">(87)</span>.</p>
<p><strong>Função <code>pnorm()</code></strong></p>
<p>A função <code>pnorm()</code> fornece a <em>Função de Distribuição Cumulativa</em> (CDF) da distribuição Normal, que é a probabilidade de que a variável <em>X</em> contenha um valor menor ou igual a <em>x</em>.</p>
<ul>
<li><p><strong>Sintaxe</strong>:
<code>pnorm(q, mean = 0, sd = 1, lower.tail = TRUE)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>q</em> <span class="math inline">\(\longrightarrow\)</span> vetor de quantis</li>
<li><em>mean</em> <span class="math inline">\(\longrightarrow\)</span> média</li>
<li><em>sd</em> <span class="math inline">\(\longrightarrow\)</span> desvio padrão</li>
<li><em>lower.tail</em> <span class="math inline">\(\longrightarrow\)</span> Se <code>TRUE</code>, as probabilidades são (<span class="math inline">\(P \le x\)</span>), caso contrário <span class="math inline">\(P(X &gt; x)\)</span></li>
</ul></li>
</ul>
<p>Se for usado <span class="math inline">\(mean = 0\)</span> e <span class="math inline">\(sd = 1\)</span>, o valor de q = z, caso contrário, toma-se os valores da média, o desvio padrão da população e o valor de <em>x</em>.</p>
<p>Com esta função pode-se responder a pergunta feita anteriormente em relação a probabilidade de encontrar uma mulher com mais de 1,725m, equivalente a 1.94 desvios padrão acima da média, em uma população com média = 1.5979678 e desvio padrão = 0.0654787.</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="introdução-à-teoria-das-probabilidades.html#cb417-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb417-2"><a href="introdução-à-teoria-das-probabilidades.html#cb417-2" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>## [1] 0.02618654</code></pre>
<p>Ou, usando os valores:</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="introdução-à-teoria-das-probabilidades.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.725</span>, <span class="at">mean =</span> resumo<span class="sc">$</span>media, <span class="at">sd =</span> resumo<span class="sc">$</span>dp, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.02618654</code></pre>
<p>Observa-se que, nesta população, apenas 2.6% das mulheres têm acima de 1,725m, razão de considerar-se uma mulher acima deste valor como sendo alta. Ou seja, é pouco provável encontrar mulheres acima dessa altura, nesta população. A Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:prob1725">7.4</a> representa com clareza esta pequena probabilidade.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="introdução-à-teoria-das-probabilidades.html#cb421-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;Arquivos/normal_area.R&quot;</span>)</span>
<span id="cb421-2"><a href="introdução-à-teoria-das-probabilidades.html#cb421-2" aria-hidden="true" tabindex="-1"></a><span class="fu">normal_area</span>(<span class="at">media =</span> <span class="dv">0</span>, <span class="at">dp =</span> <span class="dv">1</span>, <span class="at">linf =</span> <span class="fl">1.94</span>, <span class="at">lsup =</span> <span class="dv">3</span>, <span class="at">cor =</span> <span class="st">&quot;tomato&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span> )</span>
<span id="cb421-3"><a href="introdução-à-teoria-das-probabilidades.html#cb421-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">2.6</span>, <span class="fl">0.05</span>, <span class="st">&quot;2.6%&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:prob1725"></span>
<img src="bookdownproj_files/figure-html/prob1725-1.png" alt="Probabilidade de encontrar mulheres com mais de 1,725m" width="70%" height="70%" />
<p class="caption">
Figure 7.4: Probabilidade de encontrar mulheres com mais de 1,725m
</p>
</div>
<p>A função <code>normal_area()</code> é uma função criada para desenhar a uma curva normal com a área da probabilidade desejada colorida. Ela pode ser obtida <a href="https://github.com/petronioliveira/Arquivos/blob/main/normal_area.R"><strong>aqui</strong></a> e baixada no seu diretório. Foi usada a função <code>text()</code> para escrever o valor da probabilidade.</p>
<p><strong>Função <code>qnorm()</code></strong></p>
<p>A função <code>qnorm()</code> permite encontrar o quantil (percentil) <em>q</em> para qualquer probabilidade <em>p</em>. Portanto, a função <code>qnorm</code> é o inverso da função pnorm. A sintaxe do qnorm é a seguinte:</p>
<ul>
<li><p><strong>Sintaxe</strong><br />
<code>qnorm(p, mean = 0, sd = 1, lower.tail = TRUE)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>p</em> <span class="math inline">\(\longrightarrow\)</span> vetor de probabilidades</li>
<li><em>mean</em> <span class="math inline">\(\longrightarrow\)</span> média</li>
<li><em>sd</em> <span class="math inline">\(\longrightarrow\)</span> desvio padrão</li>
<li><em>lower.tail</em> <span class="math inline">\(\longrightarrow\)</span> Se <code>TRUE</code>, as probabilidades são (<span class="math inline">\(P \le x\)</span>), caso contrário <span class="math inline">\(P(X &gt; x)\)</span></li>
</ul></li>
</ul>
<p>No exemplo anterior, a probabilidade de se encontrar mulheres, na maternidade, com mais de 1,725m foi de 2.6%. Poderia ser calculado com a função <code>qnorm()</code> qual o escore <em>z</em> correspondente:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="introdução-à-teoria-das-probabilidades.html#cb422-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(p, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.940054</code></pre>
<p>Outro exemplo, na mediana (p = 0,5), o escore z é igual a:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="introdução-à-teoria-das-probabilidades.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.50</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p><strong>Função <code>dnorm()</code></strong></p>
<p>Essa função retorna o valor da <code>função de densidade de probabilidade</code> (pdf) da distribuição normal dada uma certa variável aleatória X, uma média populacional <span class="math inline">\(\mu\)</span> e o desvio padrão populacional <span class="math inline">\(\sigma\)</span>.</p>
<ul>
<li><p><strong>Sintaxe</strong><br />
<code>dnorm(x, mean = 0, sd = 1)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>x</em> <span class="math inline">\(\longrightarrow\)</span> vetor de quantis</li>
<li><em>mean</em> <span class="math inline">\(\longrightarrow\)</span> média</li>
<li><em>sd</em> <span class="math inline">\(\longrightarrow\)</span> desvio padrão</li>
</ul></li>
</ul>
<p>Embora x represente a variável independente da pdf para a distribuição normal, também é útil pensar em <em>x</em> como um escore <em>z</em>. Por exemplo, a densidade de probabilidade quando <em>x</em> = 0 é igual:</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="introdução-à-teoria-das-probabilidades.html#cb426-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.3989423</code></pre>
<p>Agora, para melhor comprenssão, será mostrado o que foi dito, representando a função de densidade de probabilidade da distribuição normal com o <code>dnorm()</code>.</p>
<p>Inicialmente, será construído um vetor de escores <em>z</em>:</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="introdução-à-teoria-das-probabilidades.html#cb428-1" aria-hidden="true" tabindex="-1"></a>escores_z <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb428-2"><a href="introdução-à-teoria-das-probabilidades.html#cb428-2" aria-hidden="true" tabindex="-1"></a>escores_z</span></code></pre></div>
<pre><code>##  [1] -3.0 -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3 -2.2 -2.1 -2.0 -1.9 -1.8 -1.7 -1.6
## [16] -1.5 -1.4 -1.3 -1.2 -1.1 -1.0 -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1
## [31]  0.0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.0  1.1  1.2  1.3  1.4
## [46]  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
## [61]  3.0</code></pre>
<p>Um objeto, <code>valores_d</code>, receberá os valores das densidades de probabilidade gerados com a função <code>dnorm()</code>, usando os <code>escores_z</code>:</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="introdução-à-teoria-das-probabilidades.html#cb430-1" aria-hidden="true" tabindex="-1"></a>valores_d <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(escores_z, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Estes valores serão plotados para construir a curva normal (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:pdf">7.5</a>):</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="introdução-à-teoria-das-probabilidades.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(valores_d,</span>
<span id="cb431-2"><a href="introdução-à-teoria-das-probabilidades.html#cb431-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;l&quot;</span>,                          <span class="co"># Tipo de gráfico em linha</span></span>
<span id="cb431-3"><a href="introdução-à-teoria-das-probabilidades.html#cb431-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">2</span>,                             <span class="co"># Espessura da linha 2x padrão</span></span>
<span id="cb431-4"><a href="introdução-à-teoria-das-probabilidades.html#cb431-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;steelblue&quot;</span>,                   <span class="co"># Cor da linha</span></span>
<span id="cb431-5"><a href="introdução-à-teoria-das-probabilidades.html#cb431-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>,                          <span class="co"># Eixo x sem rótulos</span></span>
<span id="cb431-6"><a href="introdução-à-teoria-das-probabilidades.html#cb431-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Densidade de Probabilidade&quot;</span>,</span>
<span id="cb431-7"><a href="introdução-à-teoria-das-probabilidades.html#cb431-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Escores z&quot;</span>)</span>
<span id="cb431-8"><a href="introdução-à-teoria-das-probabilidades.html#cb431-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-9"><a href="introdução-à-teoria-das-probabilidades.html#cb431-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Rótulos do eixo x</span></span>
<span id="cb431-10"><a href="introdução-à-teoria-das-probabilidades.html#cb431-10" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">which</span>(valores_d <span class="sc">==</span> <span class="fu">dnorm</span>(<span class="dv">0</span>)), <span class="at">labels =</span> <span class="fu">c</span>(<span class="dv">0</span>))</span>
<span id="cb431-11"><a href="introdução-à-teoria-das-probabilidades.html#cb431-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="fu">which</span>(valores_d <span class="sc">==</span> <span class="fu">dnorm</span>(<span class="dv">1</span>)), <span class="at">labels=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb431-12"><a href="introdução-à-teoria-das-probabilidades.html#cb431-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="fu">which</span>(valores_d <span class="sc">==</span> <span class="fu">dnorm</span>(<span class="dv">2</span>)), <span class="at">labels=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb431-13"><a href="introdução-à-teoria-das-probabilidades.html#cb431-13" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="fu">which</span>(valores_d <span class="sc">==</span> <span class="fu">dnorm</span>(<span class="dv">3</span>)), <span class="at">labels=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:pdf"></span>
<img src="bookdownproj_files/figure-html/pdf-1.png" alt="Função densidade de probabilidade." width="70%" height="70%" />
<p class="caption">
Figure 7.5: Função densidade de probabilidade.
</p>
</div>
<p>Como se pode ver, <code>dnorm()</code> fornece a “altura” do pdf da distribuição normal em qualquer escore <em>z</em> que se forneça como argumento.</p>
<p><strong>Função <code>rnorm()</code></strong></p>
<p>A função <code>rnorm()</code> gera <em>n</em> números aleatórios com distribuição normal com média <span class="math inline">\(\mu\)</span> e desvio padrão <span class="math inline">\(\sigma\)</span>. A sintaxe da função <code>rnorm()</code> no R é a seguinte:</p>
<ul>
<li><p><strong>Sintaxe</strong>:<br />
<code>qnorm(n, mean = 0, sd = 1)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>n</em> <span class="math inline">\(\longrightarrow\)</span> número de observações a serem geradas</li>
<li><em>mean</em> <span class="math inline">\(\longrightarrow\)</span> média</li>
<li><em>sd</em> <span class="math inline">\(\longrightarrow\)</span> desvio padrão</li>
</ul></li>
</ul>
<p>Com esta função é possível, por exemplo, gerar 10 observações de uma distribuição normal:</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="introdução-à-teoria-das-probabilidades.html#cb432-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] -0.3710554 -1.2409204  1.4334948  1.1389462 -0.4894149 -1.2164892
##  [7] -0.2466062  1.0813703 -0.2994662  0.4487307</code></pre>
<p>No entanto, deve-se notar que, se não especificar uma “semente” (<code>seed</code>), a saída não será reproduzível:</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="introdução-à-teoria-das-probabilidades.html#cb434-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1]  0.10822297 -0.49303419 -0.26701880 -0.01995437  0.65751169 -0.18868463
##  [7]  0.55546443 -0.20136154 -1.04337133  1.45320697</code></pre>
<p>Pode-se usar a função <code>set.seed()</code> para tornar o código reproduzível. O valor da “semente” (número) não é importante desde que seja consistente na sua utilização. O que é verdadeiramente importante é que o código seja reproduzido fielmente.</p>
<p>Para ilustrar, será construído dois conjuntos de 10 números que serão recebidos pelos objetos <em>x</em> e <em>y</em>. Para gerar o conjunto de números <em>x</em>, sera usado o número <code>123</code> como “semente”. A “semente” funciona como uma espécie de marca. Para o <em>y</em> não será usado a <code>set.seed()</code>.</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="introdução-à-teoria-das-probabilidades.html#cb436-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb436-2"><a href="introdução-à-teoria-das-probabilidades.html#cb436-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb436-3"><a href="introdução-à-teoria-das-probabilidades.html#cb436-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">123</span>)</span>
<span id="cb436-4"><a href="introdução-à-teoria-das-probabilidades.html#cb436-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span> (n)</span>
<span id="cb436-5"><a href="introdução-à-teoria-das-probabilidades.html#cb436-5" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] -0.56047565 -0.23017749  1.55870831  0.07050839  0.12928774  1.71506499
##  [7]  0.46091621 -1.26506123 -0.68685285 -0.44566197</code></pre>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="introdução-à-teoria-das-probabilidades.html#cb438-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb438-2"><a href="introdução-à-teoria-das-probabilidades.html#cb438-2" aria-hidden="true" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>##  [1]  1.2240818  0.3598138  0.4007715  0.1106827 -0.5558411  1.7869131
##  [7]  0.4978505 -1.9666172  0.7013559 -0.4727914</code></pre>
<p>Comparando os conjuntos com a função <code>identical()</code> do R base, observa-se que os conjuntos são diferentes:</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="introdução-à-teoria-das-probabilidades.html#cb440-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(x, y)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Agora, repetindo os mesmos comandos, mas usando antes a mesma “semente”:</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="introdução-à-teoria-das-probabilidades.html#cb442-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">123</span>)</span>
<span id="cb442-2"><a href="introdução-à-teoria-das-probabilidades.html#cb442-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span> (n)</span>
<span id="cb442-3"><a href="introdução-à-teoria-das-probabilidades.html#cb442-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1] -0.56047565 -0.23017749  1.55870831  0.07050839  0.12928774  1.71506499
##  [7]  0.46091621 -1.26506123 -0.68685285 -0.44566197</code></pre>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="introdução-à-teoria-das-probabilidades.html#cb444-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">123</span>)</span>
<span id="cb444-2"><a href="introdução-à-teoria-das-probabilidades.html#cb444-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb444-3"><a href="introdução-à-teoria-das-probabilidades.html#cb444-3" aria-hidden="true" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>##  [1] -0.56047565 -0.23017749  1.55870831  0.07050839  0.12928774  1.71506499
##  [7]  0.46091621 -1.26506123 -0.68685285 -0.44566197</code></pre>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="introdução-à-teoria-das-probabilidades.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(x, y)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Observa-se que, agora, tem-se conjuntos idênticos.</p>
<p>Agora, para usar <code>rnorm()</code>, serão gerados três vetores diferentes de números aleatórios de uma distribuição normal.</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="introdução-à-teoria-das-probabilidades.html#cb448-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb448-2"><a href="introdução-à-teoria-das-probabilidades.html#cb448-2" aria-hidden="true" tabindex="-1"></a>n10 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb448-3"><a href="introdução-à-teoria-das-probabilidades.html#cb448-3" aria-hidden="true" tabindex="-1"></a>n100 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb448-4"><a href="introdução-à-teoria-das-probabilidades.html#cb448-4" aria-hidden="true" tabindex="-1"></a>n10000 <span class="ot">&lt;-</span>  <span class="fu">rnorm</span>(<span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>A seguir, serão construídos histogramas (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:pdf1">7.6</a>), onde se pode observar que, aumentando o número de observações, tem-se gráficos que irão progressivamente se aproximando da verdadeira função de densidade normal.</p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="introdução-à-teoria-das-probabilidades.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Este comando coloca os gráficos em uma mesma linha, o argumento mfrow(c(1,3)) diz ao R para construir uma linha e três colunas:</span></span>
<span id="cb449-2"><a href="introdução-à-teoria-das-probabilidades.html#cb449-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb449-3"><a href="introdução-à-teoria-das-probabilidades.html#cb449-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb449-4"><a href="introdução-à-teoria-das-probabilidades.html#cb449-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogramas</span></span>
<span id="cb449-5"><a href="introdução-à-teoria-das-probabilidades.html#cb449-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(n10, <span class="at">breaks =</span> <span class="dv">5</span>, <span class="at">main =</span> <span class="st">&quot;n =10&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Frequência&quot;</span>)</span>
<span id="cb449-6"><a href="introdução-à-teoria-das-probabilidades.html#cb449-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(n100, <span class="at">breaks =</span> <span class="dv">20</span>, <span class="at">main =</span> <span class="st">&quot;n =100&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Frequência&quot;</span>)</span>
<span id="cb449-7"><a href="introdução-à-teoria-das-probabilidades.html#cb449-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(n10000, <span class="at">breaks =</span> <span class="dv">50</span>, <span class="at">main =</span> <span class="st">&quot;n =10000&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Frequência&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:pdf1"></span>
<img src="bookdownproj_files/figure-html/pdf1-1.png" alt="Histogramas construídos com amostras geradas pela função rnorm." width="100%" height="70%" />
<p class="caption">
Figure 7.6: Histogramas construídos com amostras geradas pela função rnorm.
</p>
</div>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="introdução-à-teoria-das-probabilidades.html#cb450-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Restaura as configurações basais de plotagem</span></span>
<span id="cb450-2"><a href="introdução-à-teoria-das-probabilidades.html#cb450-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
</div>
<div id="regra-empírica-68-95-99.7" class="section level3 hasAnchor" number="7.6.3">
<h3><span class="header-section-number">7.6.3</span> Regra Empírica 68-95-99.7<a href="introdução-à-teoria-das-probabilidades.html#regra-empírica-68-95-99.7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A regra empírica diz que, se uma população de um conjunto de dados tem uma distribuição normal com média 0 e desvio padrão 1 (X ~ Norm (0,1)) pode-se afirmar que aproximadamente, 68%, 95% e 99,7% dos valores encontram-se, respectivamente, dentro de <span class="math inline">\(\pm\)</span> 1, 2 e 3 desvio padrão acima e abaixo média.</p>
<p>Esta regra pode ser usada para descrever uma população e ajudar a decidir se uma amostra de dados veio de uma distribuição normal. Se uma amostra é grande o suficiente e a observação do histograma tem um formato parecido com um sino, é possível verificar se os dados seguem as especificações 68-95-99,7%. Se sim, é razoável concluir que os dados vieram de uma distribuição normal.</p>
<p>Usando a amostra dos recém-nascidos a termo da maternidade-escola do Hospital Geral de Caxias do Sul e for observado o histograma com uma curva normal sobreposta, tem-se</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="introdução-à-teoria-das-probabilidades.html#cb451-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecionando os recém-nascidos a termo</span></span>
<span id="cb451-2"><a href="introdução-à-teoria-das-probabilidades.html#cb451-2" aria-hidden="true" tabindex="-1"></a>rnt <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">&quot;Arquivos/dadosMater.xlsx&quot;</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb451-3"><a href="introdução-à-teoria-das-probabilidades.html#cb451-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ig <span class="sc">&gt;=</span> <span class="dv">37</span> <span class="sc">&amp;</span> ig <span class="sc">&lt;</span> <span class="dv">42</span>)</span>
<span id="cb451-4"><a href="introdução-à-teoria-das-probabilidades.html#cb451-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb451-5"><a href="introdução-à-teoria-das-probabilidades.html#cb451-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Média dos pesos dos recém-nascidos a termo</span></span>
<span id="cb451-6"><a href="introdução-à-teoria-das-probabilidades.html#cb451-6" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span>  <span class="fu">mean</span>(rnt<span class="sc">$</span>pesoRN, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb451-7"><a href="introdução-à-teoria-das-probabilidades.html#cb451-7" aria-hidden="true" tabindex="-1"></a>media</span></code></pre></div>
<pre><code>## [1] 3216.316</code></pre>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="introdução-à-teoria-das-probabilidades.html#cb453-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio padrão dos pesos dos recém-nascidos a termo</span></span>
<span id="cb453-2"><a href="introdução-à-teoria-das-probabilidades.html#cb453-2" aria-hidden="true" tabindex="-1"></a>dp  <span class="ot">&lt;-</span>  <span class="fu">sd</span>(rnt<span class="sc">$</span>pesoRN, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb453-3"><a href="introdução-à-teoria-das-probabilidades.html#cb453-3" aria-hidden="true" tabindex="-1"></a>dp</span></code></pre></div>
<pre><code>## [1] 462.1205</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:prn"></span>
<img src="bookdownproj_files/figure-html/prn-1.png" alt="Histograma com curva normal sobreposta" width="70%" height="70%" />
<p class="caption">
Figure 7.7: Histograma com curva normal sobreposta
</p>
</div>
<p>Pode-se aceitar que a distribuição é aproximadamente normal (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:prn">7.7</a>). Consequentemente, 68% desses bebês pesam entre 2754.2 e 3678.4g (média <span class="math inline">\(\pm\)</span> 1 desvio padrão). As linhas verticais tracejadas são apenas para melhorar a visualização, pois não se necessita, praticamente, de nenhum cálculo.</p>
</div>
<div id="exercitando-o-raciocínio-com-a-curva-normal" class="section level3 hasAnchor" number="7.6.4">
<h3><span class="header-section-number">7.6.4</span> Exercitando o raciocínio com a curva normal<a href="introdução-à-teoria-das-probabilidades.html#exercitando-o-raciocínio-com-a-curva-normal" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Suponha-se que em uma determinada região existam duas populações etnicamente diferentes onde as mulheres têm as seguintes medidas de altura: <em>população 1</em> tem <span class="math inline">\(\mu\)</span> = 160 cm e <span class="math inline">\(\sigma\)</span> = 6,6 cm e a <em>população 2</em> tem <span class="math inline">\(\mu\)</span> = 139 cm e <span class="math inline">\(\sigma\)</span> = 6,6 cm. Essas duas populações vivem misturadas e têm o mesmo aspecto físico, podendo ser distinguidas apenas geneticamente.</p>
<ul>
<li>A qual população pertence uma mulher de 150 cm?</li>
</ul></li>
</ol>
<p><em>Probabilidade de pertencer à População 1</em></p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="introdução-à-teoria-das-probabilidades.html#cb455-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span>  <span class="dv">150</span></span>
<span id="cb455-2"><a href="introdução-à-teoria-das-probabilidades.html#cb455-2" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="dv">160</span></span>
<span id="cb455-3"><a href="introdução-à-teoria-das-probabilidades.html#cb455-3" aria-hidden="true" tabindex="-1"></a>sigma1 <span class="ot">&lt;-</span> <span class="fl">6.6</span></span>
<span id="cb455-4"><a href="introdução-à-teoria-das-probabilidades.html#cb455-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb455-5"><a href="introdução-à-teoria-das-probabilidades.html#cb455-5" aria-hidden="true" tabindex="-1"></a>z1 <span class="ot">&lt;-</span>  (x <span class="sc">-</span> mu1)<span class="sc">/</span>sigma1</span>
<span id="cb455-6"><a href="introdução-à-teoria-das-probabilidades.html#cb455-6" aria-hidden="true" tabindex="-1"></a>z1 </span></code></pre></div>
<pre><code>## [1] -1.515152</code></pre>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="introdução-à-teoria-das-probabilidades.html#cb457-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">pnorm</span> (z1)</span>
<span id="cb457-2"><a href="introdução-à-teoria-das-probabilidades.html#cb457-2" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<pre><code>## [1] 0.06486702</code></pre>
<p>Ou seja, na população 1, apenas 6.5% das mulheres tem altura abaixo de 1,50, 93.5% é mais alta do que este valor.</p>
<p><em>Probabilidade de pertencer à População 2</em></p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="introdução-à-teoria-das-probabilidades.html#cb459-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span>  <span class="dv">150</span></span>
<span id="cb459-2"><a href="introdução-à-teoria-das-probabilidades.html#cb459-2" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="dv">140</span></span>
<span id="cb459-3"><a href="introdução-à-teoria-das-probabilidades.html#cb459-3" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> <span class="fl">6.6</span></span>
<span id="cb459-4"><a href="introdução-à-teoria-das-probabilidades.html#cb459-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb459-5"><a href="introdução-à-teoria-das-probabilidades.html#cb459-5" aria-hidden="true" tabindex="-1"></a>z2 <span class="ot">&lt;-</span>  (x <span class="sc">-</span> mu2)<span class="sc">/</span>sigma2</span>
<span id="cb459-6"><a href="introdução-à-teoria-das-probabilidades.html#cb459-6" aria-hidden="true" tabindex="-1"></a>z2 </span></code></pre></div>
<pre><code>## [1] 1.515152</code></pre>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="introdução-à-teoria-das-probabilidades.html#cb461-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">pnorm</span> (z2)</span>
<span id="cb461-2"><a href="introdução-à-teoria-das-probabilidades.html#cb461-2" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div>
<pre><code>## [1] 0.935133</code></pre>
<p>Na população 2, 6.5% das mulheres têm altura acima de 150 cm. Este valor valor está 1.52 desvios padrão distante da média. Isto significa que se ela pertencesse a população 2, ela seria considerada alta, quer dizer, praticamente 93.5% das mulheres desta população são menores do que ela.</p>
<p>No gráfico abaixo, pode-se visualizar a posição de uma mulher de 1,50 m (linha vermelha tracejada) em relação às duas populações (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:woman">7.8</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:woman"></span>
<img src="bookdownproj_files/figure-html/woman-1.png" alt="Posição de uma mulher com 1,50m comparando duas populações" width="70%" height="70%" />
<p class="caption">
Figure 7.8: Posição de uma mulher com 1,50m comparando duas populações
</p>
</div>
<p>Concluindo, ela pode pertencer a qualquer uma das populações. Pode ser uma mulher alta da população 2 ou uma “baixinha” da população 1!</p>
<ol start="2" style="list-style-type: decimal">
<li>Usando as populações do exercício 1, qual a probabilidade de se encontrar mulheres, em qualquer das populações, abaixo do escore <em>z</em> -1.96?</li>
</ol>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="introdução-à-teoria-das-probabilidades.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span> (<span class="sc">-</span><span class="fl">1.96</span>)</span></code></pre></div>
<pre><code>## [1] 0.0249979</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Usando as populações do exercício 1, qual a probabilidade de se encontrar mulheres, em qualquer das populações, acima do escore <em>z</em> 1.96?</li>
</ol>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="introdução-à-teoria-das-probabilidades.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span> (<span class="fl">1.96</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.0249979</code></pre>
<p>Em outras palavras, se forem observadas as respostas das perguntas 2 e 3, chega-se a conclusão que entre os escores <em>z</em> -1,96 e 1,96 encontram-se 95% das mulheres de qualquer população cujo parametro tem distribuição normal. Na “regra empírica 68-95-99.7” usou-se o valor de 1,96 arredondado para 2.</p>
<ol start="4" style="list-style-type: decimal">
<li>Qual é o escore <em>z</em> do 50º percentil da distribuição normal?</li>
</ol>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="introdução-à-teoria-das-probabilidades.html#cb467-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span> (<span class="fl">0.50</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Qual o escore <em>z</em> para o 97,5º percentil da distribuição normal?</li>
</ol>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="introdução-à-teoria-das-probabilidades.html#cb469-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span> (<span class="fl">0.975</span>)</span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
</div>
</div>
<div id="distribuição-binomial" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> Distribuição Binomial<a href="introdução-à-teoria-das-probabilidades.html#distribuição-binomial" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A distribuição normal padrão é apenas um dos exemplos de distribuição de probabilidade. Uma boa parte das situações se ajustam a ela. Entretanto, diversas situações reais muitas vezes se aproximam de outras distribuições estocásticas definidas por algumas hipóteses. Daí a importância de se conhecer e manipular algumas destas distribuições. Entre elas, a <strong>distribuição binomial</strong>.</p>
<p>Quando um experimento aleatório resulta em um de dois, mutuamente exclusivos, desfechos, tais como vivo/morto, positivo/negativo, sim/não, masculino/feminino é denominado de <em>Ensaio de Bernoulli</em>. Recebeu esta denominação em homenagem ao matemático suíço, Jacob Bernoulli (1654-1705), considerado fundador do cálculo e da teoria da probabilidade <span class="citation">(88)</span>.</p>
<p>A distribuição de frequências que descreve as proporções de um ensaio de Bernoulli, chama-se <em>Distribuição Binomial</em>. A probabilidade binomial dá a probabilidade de determinado desfecho ocorrer em determinado número de ensaios independentes. Uma sequência de ensaios de Bernoulli forma um <em>Processo de Bernoulli</em>.</p>
<p>A distribuição binomial é importante para variáveis discretas. Existem poucas condições que precisam ser atendidas antes se considere uma variável aleatória para distribuição binomial:</p>
<ul>
<li>Cada ensaio resulta em um de dois desfechos, mutuamente exclusivos, denominados, arbitrariamente, de sucesso e fracasso;
<ul>
<li>A probabilidade de sucesso é fixa, igual a <em>p</em>, constante em cada ensaio, e a probabilidade de fracasso é igual a <em>1 – p</em>;<br />
</li>
<li>O número de repetições <em>n</em> em um ensaio é fixo.</li>
</ul></li>
<li>Os ensaios são independentes</li>
</ul>
<p>A distribuição binomial é na verdade uma família de distribuições, cujos membros são definidos pelos valores de <em>n</em> e <em>p</em> (parâmetros da distribuição binomial).</p>
<p>A probabilidade de sucesso <a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a>, em uma distribuição binomial, é dada pela fórmula:
<span class="math display">\[
P(X = x)= C \times p^x \times (1 - p)^{n-x}
\]</span>
onde <em>n</em> = ensaios, <em>x</em> = sucessos, <em>p</em> = probabilidade de um sucesso e <em>C</em> representa o número possível de combinações em um ensaio.</p>
<p>O número de combinações, <em>C</em> de <em>x</em> sucessos entre <em>n</em> repetições podem ser computado pela fórmula:</p>
<p><span class="math display">\[
C = \frac{n!}{x!(n - x)!}
\]</span>
ou, no R, com a função <code>choose (n, x)</code>.</p>
<p>O modelo de distribuição binomial trata de encontrar a probabilidade de sucesso de um evento que tem apenas dois resultados possíveis em uma série de experimentos. Usando dados de uma distribuição binomial, é possível calcular os valores esperados de uma variável aleatória conforme ela passa por tentativas independentes.</p>
<p>Em outras palavras, é possível prever o número exato de caras ou coroas que se deve esperar ao jogar uma moeda um certo número de vezes.</p>
<p>Também, pode-se usar a probabilidade binomial cumulativa para encontrar a probabilidade de obter um determinado intervalo de resultados. Por exemplo, saber a probabilidade do nascimento de até três meninos em 10 nascimentos consecutivos quando a probabilidade de nascer um menino é 0,50.</p>
<p>O R tem quatro funções embutidas para gerar distribuição binomial. Ela são descritas a seguir.</p>
<p><strong>Função <code>pbinom()</code></strong></p>
<p>Esta função retorna o valor da <em>função de densidade cumulativa</em> (cdf) da distribuição binomial dada uma certa variável aleatória q, número de tentativas (size) e probabilidade de sucesso em cada tentativa (prob).</p>
<ul>
<li><p><strong>Sintaxe</strong>:<br />
<code>pbinom(q, size, prob, lower.tail = TRUE)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>q</em> <span class="math inline">\(\longrightarrow\)</span> vetor de quantis</li>
<li><em>size</em> <span class="math inline">\(\longrightarrow\)</span> numero de ensaios</li>
<li><em>prob</em> <span class="math inline">\(\longrightarrow\)</span> probabilidade de sucesso em cada ensaio</li>
<li><em>lower.tail</em> <span class="math inline">\(\longrightarrow\)</span> Se <code>TRUE</code>, as probabilidades são (<span class="math inline">\(P \le x\)</span>), caso contrário <span class="math inline">\(P(X &gt; x)\)</span></li>
</ul></li>
</ul>
<p>Por exemplo, qual é a probabilidade de nascer até três meninos em cinco nascimentos, sabendo que a probabiliade de nascer um menino é igual a 0.50?</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="introdução-à-teoria-das-probabilidades.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span> (<span class="dv">3</span>, <span class="dv">5</span>, <span class="fl">0.50</span>)</span></code></pre></div>
<pre><code>## [1] 0.8125</code></pre>
<p>Isso corresponde a soma das probabilidades de nascer nenhum menino, um menino, dois meninos e três meninos (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:menino3">7.9</a>). Isto é calculado pela equação <span class="math inline">\(P(X = x)\)</span>, vista anteriormente:</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="introdução-à-teoria-das-probabilidades.html#cb473-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb473-2"><a href="introdução-à-teoria-das-probabilidades.html#cb473-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fl">0.50</span></span>
<span id="cb473-3"><a href="introdução-à-teoria-das-probabilidades.html#cb473-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb473-4"><a href="introdução-à-teoria-das-probabilidades.html#cb473-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades de meninos </span></span>
<span id="cb473-5"><a href="introdução-à-teoria-das-probabilidades.html#cb473-5" aria-hidden="true" tabindex="-1"></a>Fx <span class="ot">&lt;-</span> (<span class="fu">factorial</span>(n)<span class="sc">/</span>(<span class="fu">factorial</span>(x)<span class="sc">*</span><span class="fu">factorial</span>(n<span class="sc">-</span>x)))<span class="sc">*</span> p<span class="sc">^</span>x <span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p)<span class="sc">^</span>(n<span class="sc">-</span>x)</span>
<span id="cb473-6"><a href="introdução-à-teoria-das-probabilidades.html#cb473-6" aria-hidden="true" tabindex="-1"></a>Fx</span></code></pre></div>
<pre><code>## [1] 0.03125 0.15625 0.31250 0.31250 0.15625 0.03125</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:menino3"></span>
<img src="bookdownproj_files/figure-html/menino3-1.png" alt="Distribuição binomial, mostrando a P (x &lt; 4) com n = 5 e p = 0.50 " width="70%" height="70%" />
<p class="caption">
Figure 7.9: Distribuição binomial, mostrando a P (x &lt; 4) com n = 5 e p = 0.50
</p>
</div>
<pre><code>## [1] 0.8125</code></pre>
<p><strong>Função <code>qbinom()</code></strong></p>
<p>Esta função retorna o valor da função de densidade cumulativa inversa (cdf) da distribuição binomial dada uma certa variável aleatória <em>q</em>, número de tentativas (<em>size</em>) e probabilidade de sucesso em cada tentativa (<em>prob</em>). Com o uso desta função, podemos descobrir o quantil da distribuição binomial.</p>
<ul>
<li><p><strong>Sintaxe</strong>: <code>qbinom(p, size, prob, lower.tail = TRUE)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>p</em> <span class="math inline">\(\longrightarrow\)</span> probabilidade ou vetor de probabilidades</li>
<li><em>size</em> <span class="math inline">\(\longrightarrow\)</span> numero de ensaios</li>
<li><em>prob</em> <span class="math inline">\(\longrightarrow\)</span> probabilidade de sucesso em cada ensaio</li>
<li><em>lower.tail</em> <span class="math inline">\(\longrightarrow\)</span> Se <code>TRUE</code>, as probabilidades são (<span class="math inline">\(P \le x\)</span>), caso contrário <span class="math inline">\(P(X &gt; x)\)</span></li>
</ul></li>
</ul>
<p>Por exemplo, quantos meninos nascerão em 5 partos com 81.25% de probabilidade cumulativa?</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="introdução-à-teoria-das-probabilidades.html#cb476-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span> (<span class="fl">0.8125</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">prob =</span> <span class="fl">0.50</span>)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p><strong>Função <code>rbinom()</code></strong></p>
<p>A função <code>rbinom()</code> permite extrair <em>n</em> observações aleatórias de uma distribuição binomial. Os argumentos da função são descritos abaixo:</p>
<ul>
<li><p><strong>Sintaxe</strong>:<br />
<code>qbinom(n, size, prob)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>n</em> <span class="math inline">\(\longrightarrow\)</span> número de observações aleatórias a ser gerado</li>
<li><em>size</em> <span class="math inline">\(\longrightarrow\)</span> numero de ensaios</li>
<li><em>prob</em> <span class="math inline">\(\longrightarrow\)</span> probabilidade de sucesso em cada ensaio</li>
</ul></li>
</ul>
<p>Se há necessidade de fazer uma simulação de 1000 amostras aleatoriamente, de tamanho 5 e a probabilidade de nascer menino (0,50):</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="introdução-à-teoria-das-probabilidades.html#cb478-1" aria-hidden="true" tabindex="-1"></a>menino <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb478-2"><a href="introdução-à-teoria-das-probabilidades.html#cb478-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(menino)</span></code></pre></div>
<pre><code>## [1] 2.536</code></pre>
<p>No entanto, se não for especificado uma “semente” (<code>seed</code>) antes de executar a função, será obtido um conjunto diferente de observações aleatórias a cada execução e , portanto, a média a cada execução será diferente. Para tornar a saída reproduzível, pode-se definir uma “semente” da seguinte maneira:</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="introdução-à-teoria-das-probabilidades.html#cb480-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">23</span>)</span>
<span id="cb480-2"><a href="introdução-à-teoria-das-probabilidades.html#cb480-2" aria-hidden="true" tabindex="-1"></a>menino <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb480-3"><a href="introdução-à-teoria-das-probabilidades.html#cb480-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(menino)</span></code></pre></div>
<pre><code>## [1] 2.515</code></pre>
<p>Quanto maior o número de variáveis aleatória criadas, mais próximo a média do número de sucessos estará do número esperado de sucessos que é igual ao número de sucessos vezes a probabilidade de sucesso em cada ensaio (2.5)</p>
<p><strong>Função <code>dbinom()</code></strong></p>
<p>Essa função retorna o valor da função de densidade de probabilidade (pdf) da distribuição binomial dada uma determinada variável aleatória X, número de tentativas (<em>size</em>) e probabilidade de sucesso em cada tentativa (<em>prob</em>). A função tem a seguinte sintaxe:</p>
<ul>
<li><p><strong>Sintaxe</strong>:<br />
<code>dbinom(x, size, prob)</code></p></li>
<li><p><strong>Argumentos</strong>:</p>
<ul>
<li><em>x</em> <span class="math inline">\(\longrightarrow\)</span> vetor de números</li>
<li><em>size</em> <span class="math inline">\(\longrightarrow\)</span> numero de ensaios</li>
<li><em>prob</em> <span class="math inline">\(\longrightarrow\)</span> probabilidade de sucesso em cada ensaio</li>
</ul></li>
</ul>
<p>A função é usada para encontrar a probabilidade de um determinado valor para dados que seguem a distribuição binomial, ou seja, encontra P(X=x), probabilidade de x sucessos em tentativas de tamanho (size) n quando a probabilidade (p) de sucesso é prob. Obtém o mesmo resultado da fórmula:</p>
<p><span class="math display">\[
P(X = x)= C \times p^x \times (1 - p)^{n-x}
\]</span>
Por exemplo, no nascimento de uma criança, as duas possibilidades, menino ou menina, são mutuamente excludentes e esses são os únicos eventos que podem acontecer. A probabilidade de nascimento de menino, como visto, é 0,50, qual seria a probabilidade de nascerem 4 meninos em 5 partos consecutivos (Figura <a href="introdução-à-teoria-das-probabilidades.html#fig:menino5">7.10</a>)?</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="introdução-à-teoria-das-probabilidades.html#cb482-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">4</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">prob =</span> <span class="fl">0.50</span>)</span></code></pre></div>
<pre><code>## [1] 0.15625</code></pre>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="introdução-à-teoria-das-probabilidades.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades de nascer meninos em 5 nascimentos  </span></span>
<span id="cb484-2"><a href="introdução-à-teoria-das-probabilidades.html#cb484-2" aria-hidden="true" tabindex="-1"></a>Fx <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="fl">0.50</span>)</span>
<span id="cb484-3"><a href="introdução-à-teoria-das-probabilidades.html#cb484-3" aria-hidden="true" tabindex="-1"></a>Fx</span></code></pre></div>
<pre><code>## [1] 0.03125 0.15625 0.31250 0.31250 0.15625 0.03125</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:menino5"></span>
<img src="bookdownproj_files/figure-html/menino5-1.png" alt="Distribuição binomial para P (x = 4) com n = 5 e p = 0,50" width="70%" height="70%" />
<p class="caption">
Figure 7.10: Distribuição binomial para P (x = 4) com n = 5 e p = 0,50
</p>
</div>
<div id="média-e-desvio-padrão-da-distribuição-binomial" class="section level3 hasAnchor" number="7.7.1">
<h3><span class="header-section-number">7.7.1</span> Média e desvio padrão da distribuição binomial<a href="introdução-à-teoria-das-probabilidades.html#média-e-desvio-padrão-da-distribuição-binomial" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Quando o número de repetições é grande, geralmente há necessidade de resumir as probabilidades. A distribuição binomial pode ser descrita por sua <em>média</em> e <em>variância</em>.</p>
<p>A média é o valor médio da variável aleatória em um longo número de repetições. É também chamada de <em>valor esperado</em> ou <em>expectativa</em>. A expectativa de uma variável aleatória X, geralmente, é denotada por <span class="math inline">\(E(X)\)</span> e obtida pela multiplicação do número de ensaios independentes (<em>n</em>) pela probabilidade (<em>p</em>) de sucesso em cada ensaio:
<span class="math display">\[
\mu = E(X) = n \times p
\]</span>
Portanto, a expectativa (esperança) de nascimento de meninos em 5 partos é <span class="math inline">\(E(X)=5 \times 0,50 = 2,5\)</span>, como visto na função <code>rbinom()</code>. Observe que o valor esperado de uma variável aleatória discreta não tem um valor que a variável aleatória pode realmente assumir.</p>
<p>Por exemplo, para o número médio de meninos em um parto, ou não se tem menino ou se tem 1 menino, cada uma possibilidade com probabilidade de 0,50 e o valor esperado é (0 × 0,50) + (1 × 0,50) = 0,50. O número de meninos deve ser 0 ou 1, mas o valor esperado é a metade, a média que se obteria no longo prazo.</p>
<p>A variância de uma variável aleatória discreta <em>X</em> é igual a</p>
<p><span class="math display">\[
\sigma^2=var(X) = n\times p \times (1-p)
\]</span></p>
<p>Consequentemente, o desvio padrão é igual a</p>
<p><span class="math display">\[
\sigma = \sqrt{var(X)} = \sqrt{n\times p \times (1-p)}
\]</span>
Para o exemplo de 5 nascimentos, a média foi de 2,5 meninos e o desvio padrão</p>
<p><span class="math display">\[
\sigma =\sqrt{5\times 0.50 \times (1-0.50)}=\sqrt{2.5 \times 0.50}= 1.12
\]</span>
Portanto, se espera que ocorram em média 2,5 (<span class="math inline">\(\sigma\)</span> = 1,12) nascimentos de meninos em 5 partos.</p>
</div>
</div>
<div id="distribuição-de-poisson" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> Distribuição de Poisson<a href="introdução-à-teoria-das-probabilidades.html#distribuição-de-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A distribuição de Poisson é utilizada para descrever a probabilidade do número de ocorrências em um intervalo contínuo (de tempo ou espaço). No caso da distribuição binomial, a variável de interesse é o número de sucessos em um intervalo discreto (<em>n</em> ensaios de Bernoulli).</p>
<p>A unidade de medida (tempo ou espaço) é uma variável contínua, mas a variável aleatória, o número de ocorrências, é discreta. Esta distribuição segue as mesmas premissas da distribuição binomial:</p>
<ul>
<li>as tentativas são independentes;</li>
<li>a variável aleatória é o número de eventos em cada amostra;</li>
<li>a probabilidade é constante em cada intervalo</li>
</ul>
<p>Ela é utilizada para modelar eventos discretos que ocorrem com pouca frequência no tempo ou espaço, por isso é algumas vezes denominada de <em>distribuição de eventos raros</em>. Pode-se usar a distribuição de Poisson como uma aproximação da distribuição Binomial quando <em>n</em>, o número de tentativas, for grande e <em>p</em> ou (1 – <em>p</em>) for pequeno (eventos raros).</p>
<p>Um bom princípio básico é usar a distribuição de Poisson quando <span class="math inline">\(n \ge 20\)</span> e <span class="math inline">\(n \times p\)</span> ou <span class="math inline">\(n \times (1- p)\)</span> &lt; 5% <span class="citation">(89)</span>. Nessas condições, a probabilidade que uma variável aleatória X adote um valor x é</p>
<p><span class="math display">\[
P(X = x) = \frac {e^{-\lambda} \times \lambda^x}{x!}
\]</span>
onde <span class="math inline">\(\lambda\)</span> (lambda) representa o número de ocorrências de um evento em um intervalo de tempo e é conhecida como parâmetro da distribuição de Poisson e é igual em média a <span class="math inline">\(n \times p\)</span>.</p>
<p>No <em>R</em>, essa probabilidade é dada pela função <code>dpois(x, lambda)</code>.</p>
<p><em>Exemplo</em>: Suponha que a probabilidade de uma puérpera ter infecção congênita (rubéola) seja igual a 0,0009. Qual seria a probabilidade, em uma população de 6000 gestantes, de que 5 estejam infectadas?</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="introdução-à-teoria-das-probabilidades.html#cb486-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.0009</span></span>
<span id="cb486-2"><a href="introdução-à-teoria-das-probabilidades.html#cb486-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb486-3"><a href="introdução-à-teoria-das-probabilidades.html#cb486-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">6000</span></span>
<span id="cb486-4"><a href="introdução-à-teoria-das-probabilidades.html#cb486-4" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> n <span class="sc">*</span> p</span>
<span id="cb486-5"><a href="introdução-à-teoria-das-probabilidades.html#cb486-5" aria-hidden="true" tabindex="-1"></a>P <span class="ot">&lt;-</span> <span class="fu">dpois</span>(x, lambda)</span>
<span id="cb486-6"><a href="introdução-à-teoria-das-probabilidades.html#cb486-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span> (P, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.173</code></pre>
<p>Portanto, a probabilidade de se encontrar 5 mulheres com infecção congênita é de aproximadamente 17%.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="11">
<li id="fn11"><p><em>Sucesso</em>, aqui, não está no sentido de vitória, êxito, triunfo, glória e sim como obter o desfecho esperado. Por exemplo, se uma moeda é lançada e se espera obter cara, sucesso significa um resultado igual a cara.<a href="introdução-à-teoria-das-probabilidades.html#fnref11" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="descrevendo-os-dados.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="assimetria-e-curtose.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/petronioliveira/bookR/edit/main/07-probabilidades.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/petronioliveira/bookR/blob/main/07-probabilidades.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
