<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 17 Métodos não paramétricos | Bioestatística Usando o R</title>
  <meta name="description" content="Capítulo 17 Métodos não paramétricos | Bioestatística Usando o R" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 17 Métodos não paramétricos | Bioestatística Usando o R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 17 Métodos não paramétricos | Bioestatística Usando o R" />
  
  
  

<meta name="author" content="Petrônio Fagundes de Oliveira Filho" />


<meta name="date" content="2025-05-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análise-de-dados-categóricos.html"/>
<link rel="next" href="sec-cap18.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">bookR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="17-testes_naoParametricos.html"><a href="#introdu%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>1</b> Introdução</a>
<ul>
<li class="chapter" data-level="1.1" data-path="17-testes_naoParametricos.html"><a href="#import%C3%A2ncia-da-bioestat%C3%ADstica"><i class="fa fa-check"></i><b>1.1</b> Importância da Bioestatística</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1.2</b> Pílulas históricas da Estatística</a></li>
<li class="chapter" data-level="1.3" data-path="17-testes_naoParametricos.html"><a href="#hist%C3%B3ria-resumida-do-r"><i class="fa fa-check"></i><b>1.3</b> História resumida do R</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#sobre-o-autor"><i class="fa fa-check"></i><b>1.4</b> Sobre o autor</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html"><i class="fa fa-check"></i><b>2</b> Natureza dos Dados</a>
<ul>
<li class="chapter" data-level="2.1" data-path="17-testes_naoParametricos.html"><a href="#vari%C3%A1veis-e-dados"><i class="fa fa-check"></i><b>2.1</b> Variáveis e Dados</a></li>
<li class="chapter" data-level="2.2" data-path="17-testes_naoParametricos.html"><a href="#popula%C3%A7%C3%A3o-e-amostra"><i class="fa fa-check"></i><b>2.2</b> População e Amostra</a></li>
<li class="chapter" data-level="2.3" data-path="17-testes_naoParametricos.html"><a href="#estat%C3%ADstica-e-par%C3%A2metro"><i class="fa fa-check"></i><b>2.3</b> Estatística e Parâmetro</a></li>
<li class="chapter" data-level="2.4" data-path="17-testes_naoParametricos.html"><a href="#escalas-de-medi%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>2.4</b> Escalas de medição</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-nominal"><i class="fa fa-check"></i><b>2.4.1</b> Escala Nominal</a></li>
<li class="chapter" data-level="2.4.2" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-ordinal"><i class="fa fa-check"></i><b>2.4.2</b> Escala Ordinal</a></li>
<li class="chapter" data-level="2.4.3" data-path="natureza-dos-dados.html"><a href="natureza-dos-dados.html#escala-intervalar"><i class="fa fa-check"></i><b>2.4.3</b> Escala Intervalar</a></li>
<li class="chapter" data-level="2.4.4" data-path="17-testes_naoParametricos.html"><a href="#escala-de-raz%C3%A3o"><i class="fa fa-check"></i><b>2.4.4</b> Escala de Razão</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="17-testes_naoParametricos.html"><a href="#tipos-de-vari%C3%A1veis"><i class="fa fa-check"></i><b>2.5</b> Tipos de Variáveis</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="17-testes_naoParametricos.html"><a href="#vari%C3%A1veis-num%C3%A9ricas"><i class="fa fa-check"></i><b>2.5.1</b> Variáveis Numéricas</a></li>
<li class="chapter" data-level="2.5.2" data-path="17-testes_naoParametricos.html"><a href="#vari%C3%A1veis-categ%C3%B3ricas"><i class="fa fa-check"></i><b>2.5.2</b> Variáveis Categóricas</a></li>
<li class="chapter" data-level="2.5.3" data-path="17-testes_naoParametricos.html"><a href="#como-identificar-o-tipo-da-vari%C3%A1vel"><i class="fa fa-check"></i><b>2.5.3</b> Como identificar o tipo da variável?</a></li>
<li class="chapter" data-level="2.5.4" data-path="17-testes_naoParametricos.html"><a href="#vari%C3%A1veis-dependentes-e-independentes"><i class="fa fa-check"></i><b>2.5.4</b> Variáveis Dependentes e Independentes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="17-testes_naoParametricos.html"><a href="#produ%C3%A7%C3%A3o-dos-dados"><i class="fa fa-check"></i><b>3</b> Produção dos Dados</a>
<ul>
<li class="chapter" data-level="3.1" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html"><i class="fa fa-check"></i><b>3.1</b> Processo de Pesquisa</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="17-testes_naoParametricos.html"><a href="#quest%C3%A3o-de-pesquisa"><i class="fa fa-check"></i><b>3.1.1</b> Questão de Pesquisa</a></li>
<li class="chapter" data-level="3.1.2" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3tese-de-pesquisa"><i class="fa fa-check"></i><b>3.1.2</b> Hipótese de Pesquisa</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#processo-de-amostragem"><i class="fa fa-check"></i><b>3.2</b> Processo de Amostragem</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="17-testes_naoParametricos.html"><a href="#amostras-probabil%C3%ADstica"><i class="fa fa-check"></i><b>3.2.1</b> Amostras probabilística</a></li>
<li class="chapter" data-level="3.2.2" data-path="17-testes_naoParametricos.html"><a href="#amostras-n%C3%A3o-probabil%C3%ADsticas"><i class="fa fa-check"></i><b>3.2.2</b> Amostras não probabilísticas</a></li>
<li class="chapter" data-level="3.2.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#tamanho-amostral"><i class="fa fa-check"></i><b>3.2.3</b> Tamanho amostral</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#principais-delineamentos-de-pesquisa"><i class="fa fa-check"></i><b>3.3</b> Principais Delineamentos de Pesquisa</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="17-testes_naoParametricos.html"><a href="#elementos-b%C3%A1sicos-de-um-delineamento-de-pesquisa"><i class="fa fa-check"></i><b>3.3.1</b> Elementos básicos de um delineamento de pesquisa</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-observacionais"><i class="fa fa-check"></i><b>3.4</b> Estudos Observacionais</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="17-testes_naoParametricos.html"><a href="#relato-de-caso-ou-s%C3%A9rie-de-casos"><i class="fa fa-check"></i><b>3.4.1</b> Relato de Caso ou Série de casos</a></li>
<li class="chapter" data-level="3.4.2" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-transversais-ou-seccionais"><i class="fa fa-check"></i><b>3.4.2</b> Estudos Transversais ou Seccionais</a></li>
<li class="chapter" data-level="3.4.3" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-caso-controle"><i class="fa fa-check"></i><b>3.4.3</b> Estudos Caso-Controle</a></li>
<li class="chapter" data-level="3.4.4" data-path="produção-dos-dados.html"><a href="produção-dos-dados.html#estudos-de-coorte"><i class="fa fa-check"></i><b>3.4.4</b> Estudos de Coorte</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="17-testes_naoParametricos.html"><a href="#ensaios-cl%C3%ADnicos"><i class="fa fa-check"></i><b>3.5</b> Ensaios Clínicos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="17-testes_naoParametricos.html"><a href="#caracter%C3%ADsticas-de-um-ensaio-cl%C3%ADnico"><i class="fa fa-check"></i><b>3.5.1</b> Características de um ensaio clínico</a></li>
<li class="chapter" data-level="3.5.2" data-path="17-testes_naoParametricos.html"><a href="#elementos-b%C3%A1sicos-de-um-ensaio-cl%C3%ADnico"><i class="fa fa-check"></i><b>3.5.2</b> Elementos básicos de um ensaio clínico</a></li>
<li class="chapter" data-level="3.5.3" data-path="17-testes_naoParametricos.html"><a href="#ensaios-cl%C3%ADnicos-de-equival%C3%AAncia-e-n%C3%A3o-inferioridade"><i class="fa fa-check"></i><b>3.5.3</b> Ensaios clínicos de equivalência e não inferioridade</a></li>
<li class="chapter" data-level="3.5.4" data-path="17-testes_naoParametricos.html"><a href="#outros-tipos-de-ensaios-cl%C3%ADnicos"><i class="fa fa-check"></i><b>3.5.4</b> Outros tipos de ensaios clínicos</a></li>
<li class="chapter" data-level="3.5.5" data-path="17-testes_naoParametricos.html"><a href="#fases-de-um-ensaio-cl%C3%ADnico"><i class="fa fa-check"></i><b>3.5.5</b> Fases de um ensaio clínico</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html"><i class="fa fa-check"></i><b>4</b> Ambiente do <em>R</em></a>
<ul>
<li class="chapter" data-level="4.1" data-path="17-testes_naoParametricos.html"><a href="#instala%C3%A7%C3%A3o-do-r-b%C3%A1sico"><i class="fa fa-check"></i><b>4.1</b> Instalação do <em>R</em> básico</a></li>
<li class="chapter" data-level="4.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#rstudio"><i class="fa fa-check"></i><b>4.2</b> <em>RStudio</em></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="17-testes_naoParametricos.html"><a href="#instala%C3%A7%C3%A3o-do-r-studio"><i class="fa fa-check"></i><b>4.2.1</b> Instalação do <em>R Studio</em></a></li>
<li class="chapter" data-level="4.2.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#iniciando-o-rstudio"><i class="fa fa-check"></i><b>4.2.2</b> Iniciando o <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#pacotes"><i class="fa fa-check"></i><b>4.3</b> Pacotes</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="17-testes_naoParametricos.html"><a href="#reposit%C3%B3rio-de-pacotes"><i class="fa fa-check"></i><b>4.3.1</b> Repositório de pacotes</a></li>
<li class="chapter" data-level="4.3.2" data-path="17-testes_naoParametricos.html"><a href="#instala%C3%A7%C3%A3o-de-um-pacote-novo"><i class="fa fa-check"></i><b>4.3.2</b> Instalação de um pacote novo</a></li>
<li class="chapter" data-level="4.3.3" data-path="17-testes_naoParametricos.html"><a href="#atualiza%C3%A7%C3%A3o-dos-pacotes"><i class="fa fa-check"></i><b>4.3.3</b> Atualização dos pacotes</a></li>
<li class="chapter" data-level="4.3.4" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalando-e-carregando-mais-de-um-pacote"><i class="fa fa-check"></i><b>4.3.4</b> Instalando e carregando mais de um pacote</a></li>
<li class="chapter" data-level="4.3.5" data-path="17-testes_naoParametricos.html"><a href="#cita%C3%A7%C3%A3o-de-pacotes-em-publica%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>4.3.5</b> Citação de pacotes em publicações</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="17-testes_naoParametricos.html"><a href="#diret%C3%B3rio-de-trabalho"><i class="fa fa-check"></i><b>4.4</b> Diretório de trabalho</a></li>
<li class="chapter" data-level="4.5" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#projeto"><i class="fa fa-check"></i><b>4.5</b> Projeto</a></li>
<li class="chapter" data-level="4.6" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#o-r-como-calculadora"><i class="fa fa-check"></i><b>4.6</b> O <em>R</em> como calculadora</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#operadores"><i class="fa fa-check"></i><b>4.6.1</b> Operadores</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-objetos"><i class="fa fa-check"></i><b>4.7</b> Objetos</a></li>
<li class="chapter" data-level="4.8" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-funcoes"><i class="fa fa-check"></i><b>4.8</b> Funções</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-funcpropria"><i class="fa fa-check"></i><b>4.8.1</b> Criando funções</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#classes"><i class="fa fa-check"></i><b>4.9</b> Classes</a></li>
<li class="chapter" data-level="4.10" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-vetores"><i class="fa fa-check"></i><b>4.10</b> Vetores</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#tipos-de-vetores"><i class="fa fa-check"></i><b>4.10.1</b> Tipos de vetores</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-dataframes"><i class="fa fa-check"></i><b>4.11</b> Dataframes</a></li>
<li class="chapter" data-level="4.12" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#sec-fatores"><i class="fa fa-check"></i><b>4.12</b> Fatores</a>
<ul>
<li class="chapter" data-level="4.12.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#criando-fatores"><i class="fa fa-check"></i><b>4.12.1</b> Criando fatores</a></li>
<li class="chapter" data-level="4.12.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#salvando-o-dataframe-criado"><i class="fa fa-check"></i><b>4.12.2</b> Salvando o dataframe criado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html"><i class="fa fa-check"></i><b>5</b> Manipulando os dados no <em>R Studio</em></a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#importando-dados-de-outros-softwares"><i class="fa fa-check"></i><b>5.1</b> Importando dados de outros <em>softwares</em></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-csv"><i class="fa fa-check"></i><b>5.1.1</b> Importando dados de um arquivo CSV</a></li>
<li class="chapter" data-level="5.1.2" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-xlsx"><i class="fa fa-check"></i><b>5.1.2</b> Importando um arquivo do Excel</a></li>
<li class="chapter" data-level="5.1.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#importando-arquivos-com-o-rstudio"><i class="fa fa-check"></i><b>5.1.3</b> Importando arquivos com o RStudio</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-tibble"><i class="fa fa-check"></i><b>5.2</b> Tibble</a></li>
<li class="chapter" data-level="5.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-mater"><i class="fa fa-check"></i><b>5.3</b> Pacote <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-select"><i class="fa fa-check"></i><b>5.3.1</b> Função <code>select()</code></a></li>
<li class="chapter" data-level="5.3.2" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-filter"><i class="fa fa-check"></i><b>5.3.2</b> Função <code>filter()</code></a></li>
<li class="chapter" data-level="5.3.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#sec-mutate"><i class="fa fa-check"></i><b>5.3.3</b> Função <code>mutate()</code></a></li>
<li class="chapter" data-level="5.3.4" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-sample_n"><i class="fa fa-check"></i><b>5.3.4</b> Função <code>sample_n()</code></a></li>
<li class="chapter" data-level="5.3.5" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-slice"><i class="fa fa-check"></i><b>5.3.5</b> Função <code>slice()</code></a></li>
<li class="chapter" data-level="5.3.6" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-arrange"><i class="fa fa-check"></i><b>5.3.6</b> Função <code>arrange()</code></a></li>
<li class="chapter" data-level="5.3.7" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-count"><i class="fa fa-check"></i><b>5.3.7</b> Função <code>count()</code></a></li>
<li class="chapter" data-level="5.3.8" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#operador-pipe"><i class="fa fa-check"></i><b>5.3.8</b> Operador pipe %&gt;%</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="17-testes_naoParametricos.html"><a href="#manipula%C3%A7%C3%A3o-de-datas"><i class="fa fa-check"></i><b>5.4</b> Manipulação de datas</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#convertendo-strings-ou-caractere-para-data"><i class="fa fa-check"></i><b>5.4.1</b> Convertendo <em>strings</em> ou caractere para data</a></li>
<li class="chapter" data-level="5.4.2" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#juntando-componentes-de-datas"><i class="fa fa-check"></i><b>5.4.2</b> Juntando componentes de datas</a></li>
<li class="chapter" data-level="5.4.3" data-path="manipulando-os-dados-no-r-studio.html"><a href="manipulando-os-dados-no-r-studio.html#extraindo-componentes-de-datas"><i class="fa fa-check"></i><b>5.4.3</b> Extraindo componentes de datas</a></li>
<li class="chapter" data-level="5.4.4" data-path="17-testes_naoParametricos.html"><a href="#opera%C3%A7%C3%B5es-com-datas"><i class="fa fa-check"></i><b>5.4.4</b> Operações com datas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html"><i class="fa fa-check"></i><b>6</b> Descrevendo os dados</a>
<ul>
<li class="chapter" data-level="6.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo"><i class="fa fa-check"></i><b>6.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="6.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#dados-brutos"><i class="fa fa-check"></i><b>6.2</b> Dados brutos</a></li>
<li class="chapter" data-level="6.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#medidas-resumidoras"><i class="fa fa-check"></i><b>6.3</b> Medidas resumidoras</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>6.3.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="6.3.2" data-path="17-testes_naoParametricos.html"><a href="#introdu%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>6.3.2</b> Introdução</a></li>
<li class="chapter" data-level="6.3.3" data-path="17-testes_naoParametricos.html"><a href="#medidas-de-tend%C3%AAncia-central"><i class="fa fa-check"></i><b>6.3.3</b> Medidas de tendência central</a></li>
<li class="chapter" data-level="6.3.4" data-path="17-testes_naoParametricos.html"><a href="#medidas-de-dispers%C3%A3o"><i class="fa fa-check"></i><b>6.3.4</b> Medidas de Dispersão</a></li>
<li class="chapter" data-level="6.3.5" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#escolha-da-medida-resumidora"><i class="fa fa-check"></i><b>6.3.5</b> Escolha da medida resumidora</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-tabelas"><i class="fa fa-check"></i><b>6.4</b> Tabelas</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>6.4.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="6.4.2" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-freq"><i class="fa fa-check"></i><b>6.4.2</b> Tabelas de Frequência</a></li>
<li class="chapter" data-level="6.4.3" data-path="17-testes_naoParametricos.html"><a href="#tabelas-de-conting%C3%AAncia"><i class="fa fa-check"></i><b>6.4.3</b> Tabelas de contingência</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="17-testes_naoParametricos.html"><a href="#gr%C3%A1ficos"><i class="fa fa-check"></i><b>6.5</b> Gráficos</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="17-testes_naoParametricos.html"><a href="#gr%C3%A1fico-de-setores"><i class="fa fa-check"></i><b>6.5.1</b> Gráfico de setores</a></li>
<li class="chapter" data-level="6.5.2" data-path="17-testes_naoParametricos.html"><a href="#gr%C3%A1fico-de-barras"><i class="fa fa-check"></i><b>6.5.2</b> Gráfico de barras</a></li>
<li class="chapter" data-level="6.5.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-errorbar"><i class="fa fa-check"></i><b>6.5.3</b> Gráfico de barra de erro</a></li>
<li class="chapter" data-level="6.5.4" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-histograma"><i class="fa fa-check"></i><b>6.5.4</b> Histograma</a></li>
<li class="chapter" data-level="6.5.5" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-bxp"><i class="fa fa-check"></i><b>6.5.5</b> Boxplot</a></li>
<li class="chapter" data-level="6.5.6" data-path="17-testes_naoParametricos.html"><a href="#gr%C3%A1fico-de-dispers%C3%A3o"><i class="fa fa-check"></i><b>6.5.6</b> Gráfico de Dispersão</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-ggplot2"><i class="fa fa-check"></i><b>6.6</b> Introdução ao <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="17-testes_naoParametricos.html"><a href="#principais-gr%C3%A1ficos-usando-ggplot2"><i class="fa fa-check"></i><b>6.6.1</b> Principais gráficos usando <code>ggplot2</code></a></li>
<li class="chapter" data-level="6.6.2" data-path="17-testes_naoParametricos.html"><a href="#modifica%C3%A7%C3%A3o-dos-eixos-do-gr%C3%A1fico"><i class="fa fa-check"></i><b>6.6.2</b> Modificação dos eixos do gráfico</a></li>
<li class="chapter" data-level="6.6.3" data-path="descrevendo-os-dados.html"><a href="descrevendo-os-dados.html#sec-cores"><i class="fa fa-check"></i><b>6.6.3</b> Modificação das cores</a></li>
<li class="chapter" data-level="6.6.4" data-path="17-testes_naoParametricos.html"><a href="#mudan%C3%A7a-dos-temas"><i class="fa fa-check"></i><b>6.6.4</b> Mudança dos temas</a></li>
<li class="chapter" data-level="6.6.5" data-path="17-testes_naoParametricos.html"><a href="#estudo-de-caso-gr%C3%A1fico-de-barra-de-erro"><i class="fa fa-check"></i><b>6.6.5</b> Estudo de caso: Gráfico de barra de erro</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="17-testes_naoParametricos.html"><a href="#introdu%C3%A7%C3%A3o-%C3%A0-teoria-das-probabilidades"><i class="fa fa-check"></i><b>7</b> Introdução à Teoria das Probabilidades</a>
<ul>
<li class="chapter" data-level="7.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-1"><i class="fa fa-check"></i><b>7.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="7.2" data-path="17-testes_naoParametricos.html"><a href="#introdu%C3%A7%C3%A3o-2"><i class="fa fa-check"></i><b>7.2</b> Introdução</a></li>
<li class="chapter" data-level="7.3" data-path="17-testes_naoParametricos.html"><a href="#processo-aleat%C3%B3rio"><i class="fa fa-check"></i><b>7.3</b> Processo aleatório</a></li>
<li class="chapter" data-level="7.4" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-frequentista"><i class="fa fa-check"></i><b>7.4</b> Definição frequentista</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html"><i class="fa fa-check"></i><b>7.4.1</b> Aplicando a visão frequentista no dia a dia</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#propriedades-das-probabilidades"><i class="fa fa-check"></i><b>7.5</b> Propriedades das probabilidades</a></li>
<li class="chapter" data-level="7.6" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-de-probabilidades"><i class="fa fa-check"></i><b>7.6</b> Distribuição de Probabilidades</a></li>
<li class="chapter" data-level="7.7" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#sec-normal"><i class="fa fa-check"></i><b>7.7</b> Distribuição Normal</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="17-testes_naoParametricos.html"><a href="#caracter%C3%ADsticas-da-distribui%C3%A7%C3%A3o-normal"><i class="fa fa-check"></i><b>7.7.1</b> Características da distribuição normal</a></li>
<li class="chapter" data-level="7.7.2" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#sec-dnp"><i class="fa fa-check"></i><b>7.7.2</b> Distribuição normal padronizada</a></li>
<li class="chapter" data-level="7.7.3" data-path="17-testes_naoParametricos.html"><a href="#regra-emp%C3%ADrica-68-95-99.7"><i class="fa fa-check"></i><b>7.7.3</b> Regra Empírica 68-95-99.7</a></li>
<li class="chapter" data-level="7.7.4" data-path="17-testes_naoParametricos.html"><a href="#calculando-probabilidades-em-uma-distribui%C3%A7%C3%A3o-normal"><i class="fa fa-check"></i><b>7.7.4</b> Calculando probabilidades em uma distribuição normal</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-binomial"><i class="fa fa-check"></i><b>7.8</b> Distribuição Binomial</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%B5es-da-distribui%C3%A7%C3%A3o-binomial"><i class="fa fa-check"></i><b>7.8.1</b> Funções da distribuição binomial</a></li>
<li class="chapter" data-level="7.8.2" data-path="introdução-à-teoria-das-probabilidades.html"><a href="introdução-à-teoria-das-probabilidades.html#sec-mudpbinom"><i class="fa fa-check"></i><b>7.8.2</b> Média e desvio padrão da distribuição binomial</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-de-poisson"><i class="fa fa-check"></i><b>7.9</b> Distribuição de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html"><i class="fa fa-check"></i><b>8</b> Assimetria e Curtose</a>
<ul>
<li class="chapter" data-level="8.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-2"><i class="fa fa-check"></i><b>8.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="8.2" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#dados-1"><i class="fa fa-check"></i><b>8.2</b> Dados</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#sec-assimetria"><i class="fa fa-check"></i><b>8.2.1</b> Exploração dos dados</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#assimetria"><i class="fa fa-check"></i><b>8.3</b> Assimetria</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="17-testes_naoParametricos.html"><a href="#avalia%C3%A7%C3%A3o-da-assimetria"><i class="fa fa-check"></i><b>8.3.1</b> Avaliação da assimetria</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="assimetria-e-curtose.html"><a href="assimetria-e-curtose.html#curtose"><i class="fa fa-check"></i><b>8.4</b> Curtose</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="17-testes_naoParametricos.html"><a href="#avalia%C3%A7%C3%A3o-da-curtose"><i class="fa fa-check"></i><b>8.4.1</b> Avaliação da curtose</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="17-testes_naoParametricos.html"><a href="#exerc%C3%ADcio"><i class="fa fa-check"></i><b>8.5</b> Exercício</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="sec-cap9.html"><a href="sec-cap9.html"><i class="fa fa-check"></i><b>9</b> Distribuições Amostrais</a>
<ul>
<li class="chapter" data-level="9.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-para-este-cap%C3%ADtulo"><i class="fa fa-check"></i><b>9.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="9.2" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%B5es-populacional-e-amostral"><i class="fa fa-check"></i><b>9.2</b> Distribuições populacional e amostral</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-populacional"><i class="fa fa-check"></i><b>9.2.1</b> Distribuição populacional</a></li>
<li class="chapter" data-level="9.2.2" data-path="sec-cap9.html"><a href="sec-cap9.html#sec-dam"><i class="fa fa-check"></i><b>9.2.2</b> Distribuição amostral</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="17-testes_naoParametricos.html"><a href="#erros-amostrais-e-n%C3%A3o-amostrais"><i class="fa fa-check"></i><b>9.3</b> Erros amostrais e não amostrais</a></li>
<li class="chapter" data-level="9.4" data-path="17-testes_naoParametricos.html"><a href="#m%C3%A9dia-e-desvio-padr%C3%A3o-da-m%C3%A9dia"><i class="fa fa-check"></i><b>9.4</b> Média e desvio padrão da média</a></li>
<li class="chapter" data-level="9.5" data-path="sec-cap9.html"><a href="sec-cap9.html#teorema-do-limite-central"><i class="fa fa-check"></i><b>9.5</b> Teorema do Limite Central</a></li>
<li class="chapter" data-level="9.6" data-path="sec-cap9.html"><a href="sec-cap9.html#sec-popamostra"><i class="fa fa-check"></i><b>9.6</b> Proporções populacional e amostral</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sec-estimacao.html"><a href="sec-estimacao.html"><i class="fa fa-check"></i><b>10</b> Estimação</a>
<ul>
<li class="chapter" data-level="10.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-3"><i class="fa fa-check"></i><b>10.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="10.2" data-path="sec-estimacao.html"><a href="sec-estimacao.html#sec-dadoscap10"><i class="fa fa-check"></i><b>10.2</b> Dados</a></li>
<li class="chapter" data-level="10.3" data-path="17-testes_naoParametricos.html"><a href="#introdu%C3%A7%C3%A3o-3"><i class="fa fa-check"></i><b>10.3</b> Introdução</a></li>
<li class="chapter" data-level="10.4" data-path="17-testes_naoParametricos.html"><a href="#estimativa-pontual-e-intervalo-de-confian%C3%A7a"><i class="fa fa-check"></i><b>10.4</b> Estimativa Pontual e Intervalo de Confiança</a></li>
<li class="chapter" data-level="10.5" data-path="17-testes_naoParametricos.html"><a href="#estima%C3%A7%C3%A3o-da-m%C3%A9dia-populacional-sigma-conhecido"><i class="fa fa-check"></i><b>10.5</b> Estimação da média populacional: <span class="math inline">\(\sigma\)</span> conhecido</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-do-intervalo-de-confian%C3%A7a-com-sigma-conhecido"><i class="fa fa-check"></i><b>10.5.1</b> Cálculo do intervalo de confiança com <span class="math inline">\(\sigma\)</span> conhecido</a></li>
<li class="chapter" data-level="10.5.2" data-path="17-testes_naoParametricos.html"><a href="#fun%C3%A7%C3%A3o-para-calcular-ic-com-sigma-conhecido"><i class="fa fa-check"></i><b>10.5.2</b> Função para calcular IC com <span class="math inline">\(\sigma\)</span> conhecido</a></li>
<li class="chapter" data-level="10.5.3" data-path="17-testes_naoParametricos.html"><a href="#interpreta%C3%A7%C3%A3o-do-intervalo-de-confian%C3%A7a"><i class="fa fa-check"></i><b>10.5.3</b> Interpretação do intervalo de confiança</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="17-testes_naoParametricos.html"><a href="#estima%C3%A7%C3%A3o-da-m%C3%A9dia-populacional-sigma-desconhecido"><i class="fa fa-check"></i><b>10.6</b> Estimação da média populacional: <span class="math inline">\(\sigma\)</span> desconhecido</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-t"><i class="fa fa-check"></i><b>10.6.1</b> Distribuição <em>t</em></a></li>
<li class="chapter" data-level="10.6.2" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-do-intervalo-de-confian%C3%A7a-com-sigma-desconhecido"><i class="fa fa-check"></i><b>10.6.2</b> Cálculo do intervalo de confiança com <span class="math inline">\(\sigma\)</span> desconhecido</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="17-testes_naoParametricos.html"><a href="#intervalo-de-confian%C3%A7a-para-uma-propor%C3%A7%C3%A3o-populacional"><i class="fa fa-check"></i><b>10.7</b> Intervalo de Confiança para uma proporção populacional</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="17-testes_naoParametricos.html"><a href="#dados-para-estimar-a-propor%C3%A7%C3%A3o-populacional"><i class="fa fa-check"></i><b>10.7.1</b> Dados para estimar a proporção populacional</a></li>
<li class="chapter" data-level="10.7.2" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-da-estimativa-pontual-da-propor%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>10.7.2</b> Cálculo da estimativa pontual da proporção</a></li>
<li class="chapter" data-level="10.7.3" data-path="sec-estimacao.html"><a href="sec-estimacao.html#sec-ICproporcao"><i class="fa fa-check"></i><b>10.7.3</b> Cálculo do intervalo de confiança para a proporção</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="17-testes_naoParametricos.html"><a href="#teste-de-hip%C3%B3teses"><i class="fa fa-check"></i><b>11</b> Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="11.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-4"><i class="fa fa-check"></i><b>11.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="11.2" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html"><i class="fa fa-check"></i><b>11.2</b> Dados do exemplo</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="17-testes_naoParametricos.html"><a href="#explora%C3%A7%C3%A3o-e-transforma%C3%A7%C3%A3o-dos-dados"><i class="fa fa-check"></i><b>11.2.1</b> Exploração e transformação dos dados</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="17-testes_naoParametricos.html"><a href="#introdu%C3%A7%C3%A3o-4"><i class="fa fa-check"></i><b>11.3</b> Introdução</a></li>
<li class="chapter" data-level="11.4" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3tese-nula-e-alternativa"><i class="fa fa-check"></i><b>11.4</b> Hipótese nula e alternativa</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#sec-exeth"><i class="fa fa-check"></i><b>11.4.1</b> Exemplo</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="17-testes_naoParametricos.html"><a href="#escolha-do-teste-estat%C3%ADtico-e-regra-de-decis%C3%A3o"><i class="fa fa-check"></i><b>11.5</b> Escolha do teste estatítico e regra de decisão</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="17-testes_naoParametricos.html"><a href="#teste-estat%C3%ADstico"><i class="fa fa-check"></i><b>11.5.1</b> Teste estatístico</a></li>
<li class="chapter" data-level="11.5.2" data-path="17-testes_naoParametricos.html"><a href="#regra-de-decis%C3%A3o"><i class="fa fa-check"></i><b>11.5.2</b> Regra de decisão</a></li>
<li class="chapter" data-level="11.5.3" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#sec-exeth1"><i class="fa fa-check"></i><b>11.5.3</b> Exemplo (continuação)</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#sec-valorp"><i class="fa fa-check"></i><b>11.6</b> Valor <em>P</em> do teste</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="17-testes_naoParametricos.html"><a href="#exemplo-continua%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>11.6.1</b> Exemplo (continuação)</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="teste-de-hipóteses.html"><a href="teste-de-hipóteses.html#poder-do-teste"><i class="fa fa-check"></i><b>11.7</b> Poder do teste</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="17-testes_naoParametricos.html"><a href="#exemplo-continua%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>11.7.1</b> Exemplo (continuação)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="sec-testet.html"><a href="sec-testet.html"><i class="fa fa-check"></i><b>12</b> Comparação entre duas médias</a>
<ul>
<li class="chapter" data-level="12.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-para-este-cap%C3%ADtulo-1"><i class="fa fa-check"></i><b>12.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="12.2" data-path="sec-testet.html"><a href="sec-testet.html#teste-t-para-amostras-independentes"><i class="fa fa-check"></i><b>12.2</b> Teste <em>t</em> para amostras independentes</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-2"><i class="fa fa-check"></i><b>12.2.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="12.2.2" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-das-hip%C3%B3teses-estat%C3%ADsticas"><i class="fa fa-check"></i><b>12.2.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="12.2.3" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-da-regra-de-decis%C3%A3o"><i class="fa fa-check"></i><b>12.2.3</b> Definição da regra de decisão</a></li>
<li class="chapter" data-level="12.2.4" data-path="17-testes_naoParametricos.html"><a href="#teste-estat%C3%ADstico-1"><i class="fa fa-check"></i><b>12.2.4</b> Teste estatístico</a></li>
<li class="chapter" data-level="12.2.5" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o"><i class="fa fa-check"></i><b>12.2.5</b> Conclusão</a></li>
<li class="chapter" data-level="12.2.6" data-path="sec-testet.html"><a href="sec-testet.html#tamanho-do-efeito"><i class="fa fa-check"></i><b>12.2.6</b> Tamanho do Efeito</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="sec-testet.html"><a href="sec-testet.html#teste-t-para-grupos-pareados"><i class="fa fa-check"></i><b>12.3</b> Teste <em>t</em> para grupos pareados</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-3"><i class="fa fa-check"></i><b>12.3.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="12.3.2" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-das-hip%C3%B3teses-estat%C3%ADsticas-1"><i class="fa fa-check"></i><b>12.3.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="12.3.3" data-path="17-testes_naoParametricos.html"><a href="#regra-de-decis%C3%A3o-1"><i class="fa fa-check"></i><b>12.3.3</b> Regra de decisão</a></li>
<li class="chapter" data-level="12.3.4" data-path="17-testes_naoParametricos.html"><a href="#teste-estat%C3%ADstico-2"><i class="fa fa-check"></i><b>12.3.4</b> Teste estatístico</a></li>
<li class="chapter" data-level="12.3.5" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-1"><i class="fa fa-check"></i><b>12.3.5</b> Conclusão</a></li>
<li class="chapter" data-level="12.3.6" data-path="sec-testet.html"><a href="sec-testet.html#tamanho-do-efeito-1"><i class="fa fa-check"></i><b>12.3.6</b> Tamanho do Efeito</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="17-testes_naoParametricos.html"><a href="#an%C3%A1lise-de-vari%C3%A2ncia"><i class="fa fa-check"></i><b>13</b> Análise de Variância</a>
<ul>
<li class="chapter" data-level="13.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-para-este-cap%C3%ADtulo-2"><i class="fa fa-check"></i><b>13.1</b> Pacotes necessários para este capítulo</a></li>
<li class="chapter" data-level="13.2" data-path="análise-de-variância.html"><a href="análise-de-variância.html"><i class="fa fa-check"></i><b>13.2</b> Por que realizar uma ANOVA?</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="17-testes_naoParametricos.html"><a href="#l%C3%B3gica-do-modelo-da-anova"><i class="fa fa-check"></i><b>13.2.1</b> Lógica do Modelo da ANOVA</a></li>
<li class="chapter" data-level="13.2.2" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-f"><i class="fa fa-check"></i><b>13.2.2</b> Distribuição <em>F</em></a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="análise-de-variância.html"><a href="análise-de-variância.html#anova-de-um-fator"><i class="fa fa-check"></i><b>13.3</b> ANOVA de um fator</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="análise-de-variância.html"><a href="análise-de-variância.html#dados-do-exemplo"><i class="fa fa-check"></i><b>13.3.1</b> Dados do exemplo</a></li>
<li class="chapter" data-level="13.3.2" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-das-hip%C3%B3teses-estat%C3%ADsticas-2"><i class="fa fa-check"></i><b>13.3.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="13.3.3" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-da-regra-de-decis%C3%A3o-1"><i class="fa fa-check"></i><b>13.3.3</b> Definição da regra de decisão</a></li>
<li class="chapter" data-level="13.3.4" data-path="17-testes_naoParametricos.html"><a href="#teste-estat%C3%ADstico-3"><i class="fa fa-check"></i><b>13.3.4</b> Teste Estatístico</a></li>
<li class="chapter" data-level="13.3.5" data-path="análise-de-variância.html"><a href="análise-de-variância.html#testes-post-hoc"><i class="fa fa-check"></i><b>13.3.5</b> Testes <em>post-hoc</em></a></li>
<li class="chapter" data-level="13.3.6" data-path="análise-de-variância.html"><a href="análise-de-variância.html#tamanho-do-efeito-2"><i class="fa fa-check"></i><b>13.3.6</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="13.3.7" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-2"><i class="fa fa-check"></i><b>13.3.7</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="análise-de-variância.html"><a href="análise-de-variância.html#anova-de-dois-fatores"><i class="fa fa-check"></i><b>13.4</b> ANOVA de dois fatores</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-4"><i class="fa fa-check"></i><b>13.4.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="13.4.2" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3teses-estat%C3%ADsticas"><i class="fa fa-check"></i><b>13.4.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="13.4.3" data-path="análise-de-variância.html"><a href="análise-de-variância.html#pressupostos-do-modelo"><i class="fa fa-check"></i><b>13.4.3</b> Pressupostos do modelo</a></li>
<li class="chapter" data-level="13.4.4" data-path="17-testes_naoParametricos.html"><a href="#verifica%C3%A7%C3%A3o-dos-pressupostos-nos-dados-brutos"><i class="fa fa-check"></i><b>13.4.4</b> Verificação dos pressupostos nos dados brutos</a></li>
<li class="chapter" data-level="13.4.5" data-path="análise-de-variância.html"><a href="análise-de-variância.html#sec-preresiduos"><i class="fa fa-check"></i><b>13.4.5</b> Verificação dos pressupostos nos resíduos</a></li>
<li class="chapter" data-level="13.4.6" data-path="17-testes_naoParametricos.html"><a href="#realiza%C3%A7%C3%A3o-do-teste-de-anova-de-dois-fatores"><i class="fa fa-check"></i><b>13.4.6</b> Realização do teste de ANOVA de dois fatores</a></li>
<li class="chapter" data-level="13.4.7" data-path="análise-de-variância.html"><a href="análise-de-variância.html#testes-post-hoc-1"><i class="fa fa-check"></i><b>13.4.7</b> Testes <em>post hoc</em></a></li>
<li class="chapter" data-level="13.4.8" data-path="análise-de-variância.html"><a href="análise-de-variância.html#relatando-os-resultados-de-uma-anova-de-dois-fatores"><i class="fa fa-check"></i><b>13.4.8</b> Relatando os resultados de uma ANOVA de dois fatores</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html"><i class="fa fa-check"></i><b>14</b> ANOVA de medidas repetidas</a>
<ul>
<li class="chapter" data-level="14.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-5"><i class="fa fa-check"></i><b>14.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="14.2" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#anova-de-medidas-repetidas-de-um-fator"><i class="fa fa-check"></i><b>14.2</b> ANOVA de medidas repetidas de um fator</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-5"><i class="fa fa-check"></i><b>14.2.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="14.2.2" data-path="17-testes_naoParametricos.html"><a href="#visualiza%C3%A7%C3%A3o-dos-dados-1"><i class="fa fa-check"></i><b>14.2.2</b> Visualização dos dados</a></li>
<li class="chapter" data-level="14.2.3" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#sec-anova2pres"><i class="fa fa-check"></i><b>14.2.3</b> Avaliação dos pressupostos</a></li>
<li class="chapter" data-level="14.2.4" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-da-estat%C3%ADstica-do-teste"><i class="fa fa-check"></i><b>14.2.4</b> Cálculo da estatística do teste</a></li>
<li class="chapter" data-level="14.2.5" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#testes-post-hoc-2"><i class="fa fa-check"></i><b>14.2.5</b> Testes post hoc</a></li>
<li class="chapter" data-level="14.2.6" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#relatando-os-resultados-da-anova-de-medidas-repetidas-unifatorial"><i class="fa fa-check"></i><b>14.2.6</b> Relatando os resultados da ANOVA de medidas repetidas unifatorial</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#anova-de-medidas-repetidas-de-dois-fatores"><i class="fa fa-check"></i><b>14.3</b> ANOVA de medidas repetidas de dois fatores</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-6"><i class="fa fa-check"></i><b>14.3.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="14.3.2" data-path="17-testes_naoParametricos.html"><a href="#avalia%C3%A7%C3%A3o-dos-pressupostos"><i class="fa fa-check"></i><b>14.3.2</b> Avaliação dos pressupostos</a></li>
<li class="chapter" data-level="14.3.3" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-da-estat%C3%ADstica-do-teste-1"><i class="fa fa-check"></i><b>14.3.3</b> Cálculo da estatística do teste</a></li>
<li class="chapter" data-level="14.3.4" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#teste-post-hoc"><i class="fa fa-check"></i><b>14.3.4</b> Teste post hoc</a></li>
<li class="chapter" data-level="14.3.5" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#relatando-os-resultados-da-anova-de-medidas-repetidas-de-dois-fatores"><i class="fa fa-check"></i><b>14.3.5</b> Relatando os resultados da ANOVA de medidas repetidas de dois fatores</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="17-testes_naoParametricos.html"><a href="#correla%C3%A7%C3%A3o-e-regress%C3%A3o"><i class="fa fa-check"></i><b>15</b> Correlação e Regressão</a>
<ul>
<li class="chapter" data-level="15.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios"><i class="fa fa-check"></i><b>15.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="15.2" data-path="17-testes_naoParametricos.html"><a href="#correla%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>15.2</b> Correlação</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="17-testes_naoParametricos.html"><a href="#coeficiente-de-correla%C3%A7%C3%A3o-de-pearson"><i class="fa fa-check"></i><b>15.2.1</b> Coeficiente de correlação de Pearson</a></li>
<li class="chapter" data-level="15.2.2" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html"><i class="fa fa-check"></i><b>15.2.2</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="15.2.3" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#sec-corpre"><i class="fa fa-check"></i><b>15.2.3</b> Pressupostos da Correlação</a></li>
<li class="chapter" data-level="15.2.4" data-path="17-testes_naoParametricos.html"><a href="#execu%C3%A7%C3%A3o-do-teste-de-correla%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>15.2.4</b> Execução do teste de correlação</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="correlação-e-regressão.html"><a href="correlação-e-regressão.html#sec-rls"><i class="fa fa-check"></i><b>15.3</b> Regressão Linear Simples</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="17-testes_naoParametricos.html"><a href="#res%C3%ADduos"><i class="fa fa-check"></i><b>15.3.1</b> Resíduos</a></li>
<li class="chapter" data-level="15.3.2" data-path="17-testes_naoParametricos.html"><a href="#an%C3%A1lise-dos-pressupostos-do-modelo-de-regress%C3%A3o"><i class="fa fa-check"></i><b>15.3.2</b> Análise dos pressupostos do modelo de regressão</a></li>
<li class="chapter" data-level="15.3.3" data-path="17-testes_naoParametricos.html"><a href="#tamanho-amostral-na-regress%C3%A3o"><i class="fa fa-check"></i><b>15.3.3</b> Tamanho amostral na regressão</a></li>
<li class="chapter" data-level="15.3.4" data-path="17-testes_naoParametricos.html"><a href="#realiza%C3%A7%C3%A3o-da-regress%C3%A3o-linear"><i class="fa fa-check"></i><b>15.3.4</b> Realização da regressão linear</a></li>
<li class="chapter" data-level="15.3.5" data-path="17-testes_naoParametricos.html"><a href="#visualiza%C3%A7%C3%A3o-dos-resultados-1"><i class="fa fa-check"></i><b>15.3.5</b> Visualização dos resultados</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="17-testes_naoParametricos.html"><a href="#an%C3%A1lise-de-dados-categ%C3%B3ricos"><i class="fa fa-check"></i><b>16</b> Análise de Dados Categóricos</a>
<ul>
<li class="chapter" data-level="16.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-1"><i class="fa fa-check"></i><b>16.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="16.2" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html"><i class="fa fa-check"></i><b>16.2</b> Qui-Quadrado</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="17-testes_naoParametricos.html"><a href="#distribui%C3%A7%C3%A3o-qui-quadrado"><i class="fa fa-check"></i><b>16.2.1</b> Distribuição qui-quadrado</a></li>
<li class="chapter" data-level="16.2.2" data-path="17-testes_naoParametricos.html"><a href="#estat%C3%ADstica-do-qui-quadrado"><i class="fa fa-check"></i><b>16.2.2</b> Estatística do qui-quadrado</a></li>
<li class="chapter" data-level="16.2.3" data-path="17-testes_naoParametricos.html"><a href="#qui-quadrado-de-independ%C3%AAncia-ou-associa%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>16.2.3</b> Qui-quadrado de independência ou associação</a></li>
<li class="chapter" data-level="16.2.4" data-path="17-testes_naoParametricos.html"><a href="#teste-ader%C3%AAncia-ou-do-melhor-ajuste"><i class="fa fa-check"></i><b>16.2.4</b> Teste Aderência ou do Melhor Ajuste</a></li>
<li class="chapter" data-level="16.2.5" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#sec-tabextensas"><i class="fa fa-check"></i><b>16.2.5</b> Qui-quadrado de Pearson para tabelas extensas</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#teste-exato-de-fisher"><i class="fa fa-check"></i><b>16.3</b> Teste exato de Fisher</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-9"><i class="fa fa-check"></i><b>16.3.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="16.3.2" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3teses-estat%C3%ADsticas-4"><i class="fa fa-check"></i><b>16.3.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="16.3.3" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-da-estat%C3%ADstica-do-teste-4"><i class="fa fa-check"></i><b>16.3.3</b> Cálculo da estatística do teste</a></li>
<li class="chapter" data-level="16.3.4" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-5"><i class="fa fa-check"></i><b>16.3.4</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#teste-de-macnemar"><i class="fa fa-check"></i><b>16.4</b> Teste de Macnemar</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="análise-de-dados-categóricos.html"><a href="análise-de-dados-categóricos.html#pressupostos-do-teste-de-mcnemar"><i class="fa fa-check"></i><b>16.4.1</b> Pressupostos do teste de McNemar</a></li>
<li class="chapter" data-level="16.4.2" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-10"><i class="fa fa-check"></i><b>16.4.2</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="16.4.3" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3teses-estat%C3%ADsticas-5"><i class="fa fa-check"></i><b>16.4.3</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="16.4.4" data-path="17-testes_naoParametricos.html"><a href="#l%C3%B3gica-do-teste-1"><i class="fa fa-check"></i><b>16.4.4</b> Lógica do teste</a></li>
<li class="chapter" data-level="16.4.5" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-do-teste-de-mcnemar-no-r"><i class="fa fa-check"></i><b>16.4.5</b> Cálculo do teste de McNemar no R</a></li>
<li class="chapter" data-level="16.4.6" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-6"><i class="fa fa-check"></i><b>16.4.6</b> Conclusão</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="17-testes_naoParametricos.html"><a href="#m%C3%A9todos-n%C3%A3o-param%C3%A9tricos"><i class="fa fa-check"></i><b>17</b> Métodos não paramétricos</a>
<ul>
<li class="chapter" data-level="17.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-6"><i class="fa fa-check"></i><b>17.1</b> Pacotes necessários neste capítulo</a></li>
<li class="chapter" data-level="17.2" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html"><i class="fa fa-check"></i><b>17.2</b> Distribuição livre</a></li>
<li class="chapter" data-level="17.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#sec-postos"><i class="fa fa-check"></i><b>17.3</b> Postos</a></li>
<li class="chapter" data-level="17.4" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#teste-de-mann-whitney"><i class="fa fa-check"></i><b>17.4</b> Teste de Mann-Whitney</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-11"><i class="fa fa-check"></i><b>17.4.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="17.4.2" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3teses-estat%C3%ADsticas-6"><i class="fa fa-check"></i><b>17.4.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="17.4.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#pressupostos-do-teste-de-mann_whitney"><i class="fa fa-check"></i><b>17.4.3</b> Pressupostos do teste de Mann_Whitney</a></li>
<li class="chapter" data-level="17.4.4" data-path="17-testes_naoParametricos.html"><a href="#c%C3%A1lculo-da-estat%C3%ADstica-de-teste"><i class="fa fa-check"></i><b>17.4.4</b> Cálculo da estatística de teste</a></li>
<li class="chapter" data-level="17.4.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#sec-tefMW"><i class="fa fa-check"></i><b>17.4.5</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="17.4.6" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-7"><i class="fa fa-check"></i><b>17.4.6</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#teste-de-wilcoxon"><i class="fa fa-check"></i><b>17.5</b> Teste de Wilcoxon</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-12"><i class="fa fa-check"></i><b>17.5.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="17.5.2" data-path="17-testes_naoParametricos.html"><a href="#defini%C3%A7%C3%A3o-das-hip%C3%B3teses-estat%C3%ADsticas-3"><i class="fa fa-check"></i><b>17.5.2</b> Definição das hipóteses estatísticas</a></li>
<li class="chapter" data-level="17.5.3" data-path="17-testes_naoParametricos.html"><a href="#execu%C3%A7%C3%A3o-do-teste-estat%C3%ADstico-2"><i class="fa fa-check"></i><b>17.5.3</b> Execução do teste estatístico</a></li>
<li class="chapter" data-level="17.5.4" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#tamanho-do-efeito-3"><i class="fa fa-check"></i><b>17.5.4</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="17.5.5" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-8"><i class="fa fa-check"></i><b>17.5.5</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#sec-kuskalwallis"><i class="fa fa-check"></i><b>17.6</b> Teste de Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="17.6.1" data-path="17-testes_naoParametricos.html"><a href="#dados-usados-nesta-se%C3%A7%C3%A3o-13"><i class="fa fa-check"></i><b>17.6.1</b> Dados usados nesta seção</a></li>
<li class="chapter" data-level="17.6.2" data-path="17-testes_naoParametricos.html"><a href="#hip%C3%B3teses-estat%C3%ADsticas-7"><i class="fa fa-check"></i><b>17.6.2</b> Hipóteses estatísticas</a></li>
<li class="chapter" data-level="17.6.3" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#pressupostos-do-teste-1"><i class="fa fa-check"></i><b>17.6.3</b> Pressupostos do teste</a></li>
<li class="chapter" data-level="17.6.4" data-path="17-testes_naoParametricos.html"><a href="#execu%C3%A7%C3%A3o-do-teste-estat%C3%ADstico-3"><i class="fa fa-check"></i><b>17.6.4</b> Execução do teste estatístico</a></li>
<li class="chapter" data-level="17.6.5" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#tamanho-do-efeito-4"><i class="fa fa-check"></i><b>17.6.5</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="17.6.6" data-path="métodos-não-paramétricos.html"><a href="métodos-não-paramétricos.html#testes-post-hoc-3"><i class="fa fa-check"></i><b>17.6.6</b> Testes post hoc</a></li>
<li class="chapter" data-level="17.6.7" data-path="17-testes_naoParametricos.html"><a href="#conclus%C3%A3o-9"><i class="fa fa-check"></i><b>17.6.7</b> Conclusão</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="sec-cap18.html"><a href="sec-cap18.html"><i class="fa fa-check"></i><b>18</b> Estatística em Epidemiologia</a>
<ul>
<li class="chapter" data-level="18.1" data-path="17-testes_naoParametricos.html"><a href="#pacotes-necess%C3%A1rios-2"><i class="fa fa-check"></i><b>18.1</b> Pacotes necessários</a></li>
<li class="chapter" data-level="18.2" data-path="sec-cap18.html"><a href="sec-cap18.html#sec-diagbayes"><i class="fa fa-check"></i><b>18.2</b> Raciocínio bayesiano no diagnóstico médico</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="sec-cap18.html"><a href="sec-cap18.html#sensibilidade-e-especificidade"><i class="fa fa-check"></i><b>18.2.1</b> Sensibilidade e Especificidade</a></li>
<li class="chapter" data-level="18.2.2" data-path="sec-cap18.html"><a href="sec-cap18.html#valor-preditivo"><i class="fa fa-check"></i><b>18.2.2</b> Valor Preditivo</a></li>
<li class="chapter" data-level="18.2.3" data-path="17-testes_naoParametricos.html"><a href="#raz%C3%A3o-de-probabilidade"><i class="fa fa-check"></i><b>18.2.3</b> Razão de Probabilidade</a></li>
<li class="chapter" data-level="18.2.4" data-path="sec-cap18.html"><a href="sec-cap18.html#curva-roc"><i class="fa fa-check"></i><b>18.2.4</b> Curva ROC</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="17-testes_naoParametricos.html"><a href="#estat%C3%ADstica-kappa"><i class="fa fa-check"></i><b>18.3</b> Estatística <em>kappa</em></a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="sec-cap18.html"><a href="sec-cap18.html#exemplo-2"><i class="fa fa-check"></i><b>18.3.1</b> Exemplo</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="17-testes_naoParametricos.html"><a href="#medidas-de-frequ%C3%AAncia"><i class="fa fa-check"></i><b>18.4</b> Medidas de frequência</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="17-testes_naoParametricos.html"><a href="#preval%C3%AAncia"><i class="fa fa-check"></i><b>18.4.1</b> Prevalência</a></li>
<li class="chapter" data-level="18.4.2" data-path="17-testes_naoParametricos.html"><a href="#incid%C3%AAncia"><i class="fa fa-check"></i><b>18.4.2</b> Incidência</a></li>
<li class="chapter" data-level="18.4.3" data-path="17-testes_naoParametricos.html"><a href="#rela%C3%A7%C3%A3o-entre-preval%C3%AAncia-e-incid%C3%AAncia"><i class="fa fa-check"></i><b>18.4.3</b> Relação entre prevalência e incidência</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="17-testes_naoParametricos.html"><a href="#medidas-de-associa%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>18.5</b> Medidas de associação</a>
<ul>
<li class="chapter" data-level="18.5.1" data-path="sec-cap18.html"><a href="sec-cap18.html#sec-or"><i class="fa fa-check"></i><b>18.5.1</b> <em>Odds Ratio</em></a></li>
<li class="chapter" data-level="18.5.2" data-path="sec-cap18.html"><a href="sec-cap18.html#sec-rr"><i class="fa fa-check"></i><b>18.5.2</b> Risco Relativo</a></li>
<li class="chapter" data-level="18.5.3" data-path="sec-cap18.html"><a href="sec-cap18.html#odds-ratio-vs-risco-relativo"><i class="fa fa-check"></i><b>18.5.3</b> <em>Odds Ratio</em> vs Risco Relativo</a></li>
<li class="chapter" data-level="18.5.4" data-path="17-testes_naoParametricos.html"><a href="#raz%C3%A3o-de-preval%C3%AAncia"><i class="fa fa-check"></i><b>18.5.4</b> Razão de Prevalência</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="sec-cap18.html"><a href="sec-cap18.html#medidas-de-impacto"><i class="fa fa-check"></i><b>18.6</b> Medidas de impacto</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="17-testes_naoParametricos.html"><a href="#risco-atribu%C3%ADvel"><i class="fa fa-check"></i><b>18.6.1</b> Risco Atribuível</a></li>
<li class="chapter" data-level="18.6.2" data-path="17-testes_naoParametricos.html"><a href="#redu%C3%A7%C3%A3o-relativa-do-risco"><i class="fa fa-check"></i><b>18.6.2</b> Redução Relativa do Risco</a></li>
<li class="chapter" data-level="18.6.3" data-path="17-testes_naoParametricos.html"><a href="#n%C3%BAmero-necess%C3%A1rio-para-tratar"><i class="fa fa-check"></i><b>18.6.3</b> Número Necessário para Tratar</a></li>
<li class="chapter" data-level="18.6.4" data-path="17-testes_naoParametricos.html"><a href="#n%C3%BAmero-necess%C3%A1rio-para-causar-dano"><i class="fa fa-check"></i><b>18.6.4</b> Número Necessário para Causar Dano</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="17-testes_naoParametricos.html"><a href="#an%C3%A1lise-de-sobrevida"><i class="fa fa-check"></i><b>18.7</b> Análise de sobrevida</a>
<ul>
<li class="chapter" data-level="18.7.1" data-path="sec-cap18.html"><a href="sec-cap18.html#dados-censurados"><i class="fa fa-check"></i><b>18.7.1</b> Dados Censurados</a></li>
<li class="chapter" data-level="18.7.2" data-path="17-testes_naoParametricos.html"><a href="#m%C3%A9todo-de-kaplan-meier"><i class="fa fa-check"></i><b>18.7.2</b> Método de Kaplan-Meier</a></li>
</ul></li>
<li class="chapter" data-level="18.8" data-path="17-testes_naoParametricos.html"><a href="#regress%C3%A3o-log%C3%ADstica-bin%C3%A1ria"><i class="fa fa-check"></i><b>18.8</b> Regressão logística binária</a>
<ul>
<li class="chapter" data-level="18.8.1" data-path="17-testes_naoParametricos.html"><a href="#pressupostos-da-regress%C3%A3o-log%C3%ADstica"><i class="fa fa-check"></i><b>18.8.1</b> Pressupostos da regressão logística</a></li>
<li class="chapter" data-level="18.8.2" data-path="17-testes_naoParametricos.html"><a href="#dados-para-a-regress%C3%A3o-log%C3%ADstica"><i class="fa fa-check"></i><b>18.8.2</b> Dados para a regressão logística</a></li>
<li class="chapter" data-level="18.8.3" data-path="17-testes_naoParametricos.html"><a href="#prepara%C3%A7%C3%A3o-dos-dados"><i class="fa fa-check"></i><b>18.8.3</b> Preparação dos dados</a></li>
<li class="chapter" data-level="18.8.4" data-path="17-testes_naoParametricos.html"><a href="#cria%C3%A7%C3%A3o-do-modelo-de-regress%C3%A3o-enter"><i class="fa fa-check"></i><b>18.8.4</b> Criação do modelo de regressão (<em>enter</em>)</a></li>
<li class="chapter" data-level="18.8.5" data-path="17-testes_naoParametricos.html"><a href="#cria%C3%A7%C3%A3o-do-modelo-passo-a-passo-stepwise"><i class="fa fa-check"></i><b>18.8.5</b> Criação do modelo passo a passo (<em>stepwise</em>)</a></li>
<li class="chapter" data-level="18.8.6" data-path="17-testes_naoParametricos.html"><a href="#uso-do-modelo-para-fazer-predi%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>18.8.6</b> Uso do modelo para fazer predições</a></li>
<li class="chapter" data-level="18.8.7" data-path="17-testes_naoParametricos.html"><a href="#avalia%C3%A7%C3%A3o-do-modelo"><i class="fa fa-check"></i><b>18.8.7</b> Avaliação do modelo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#refer%C3%AAncias"><i class="fa fa-check"></i>Referências</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bioestatística Usando o R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="métodos-não-paramétricos" class="section level1 hasAnchor" number="17">
<h1><span class="header-section-number">Capítulo 17</span> Métodos não paramétricos<a href="#m%C3%A9todos-n%C3%A3o-param%C3%A9tricos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="pacotes-necessários-neste-capítulo-6" class="section level2 hasAnchor" number="17.1">
<h2><span class="header-section-number">17.1</span> Pacotes necessários neste capítulo<a href="#pacotes-necess%C3%A1rios-neste-cap%C3%ADtulo-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb974"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb974-1"><a href="métodos-não-paramétricos.html#cb974-1" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span> (coin,</span>
<span id="cb974-2"><a href="métodos-não-paramétricos.html#cb974-2" tabindex="-1"></a>                confintr,</span>
<span id="cb974-3"><a href="métodos-não-paramétricos.html#cb974-3" tabindex="-1"></a>                dplyr,</span>
<span id="cb974-4"><a href="métodos-não-paramétricos.html#cb974-4" tabindex="-1"></a>                ggplot2,</span>
<span id="cb974-5"><a href="métodos-não-paramétricos.html#cb974-5" tabindex="-1"></a>                ggpubr,</span>
<span id="cb974-6"><a href="métodos-não-paramétricos.html#cb974-6" tabindex="-1"></a>                ggsci,</span>
<span id="cb974-7"><a href="métodos-não-paramétricos.html#cb974-7" tabindex="-1"></a>                kableExtra,</span>
<span id="cb974-8"><a href="métodos-não-paramétricos.html#cb974-8" tabindex="-1"></a>                knitr,</span>
<span id="cb974-9"><a href="métodos-não-paramétricos.html#cb974-9" tabindex="-1"></a>                readxl,</span>
<span id="cb974-10"><a href="métodos-não-paramétricos.html#cb974-10" tabindex="-1"></a>                rstatix,</span>
<span id="cb974-11"><a href="métodos-não-paramétricos.html#cb974-11" tabindex="-1"></a>                tidyr) </span></code></pre></div>
</div>
<div id="sec-distlivre" class="section level2 hasAnchor" number="17.2">
<h2><span class="header-section-number">17.2</span> Distribuição livre<a href="métodos-não-paramétricos.html#sec-distlivre" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A maioria dos testes estatísticos que discutidos são testes paramétricos. Nestes, o interesse estava focado em estimar ou testar uma hipótese sobre um ou mais parâmetros populacionais. Além disso, o aspecto central desses procedimentos era o conhecimento da forma funcional da população da qual foram retiradas as amostras que forneceram a base para a inferência. Por exemplo, o teste <em>t</em> de Student para amostras independentes e a ANOVA são baseados no pressuposto de que os dados foram amostrados de populações que têm distribuição normal.</p>
<p>Os <strong>testes não paramétricos</strong> não fazem suposições em relação à distribuição da população. Não têm, portanto, os pressupostos restritivos, comuns nos testes paramétricos. Têm <em>distribuição livre</em>. São baseados em uma ideia simples de ordenação por postos, do valor mais baixo ao mais alto. Analisam somente os postos, ignorando os valores. Podem ser usados tanto com variáveis ordinais como quantitativas numéricas.</p>
</div>
<div id="sec-postos" class="section level2 hasAnchor" number="17.3">
<h2><span class="header-section-number">17.3</span> Postos<a href="métodos-não-paramétricos.html#sec-postos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Os métodos estatísticos não paramétricos não lidam diretamente com os valores observados. Em função disso, para poder usar a informação fornecida pelas observações, sem trabalhar diretamente com os valores observados, utiliza-se os postos das observações. Posto (<em>rank</em>) de uma observação é a sua posição em relação aos demais valores.</p>
<p>A atribuição dos postos de uma variável é realizada da seguinte maneira:</p>
<ol style="list-style-type: decimal">
<li>Colocam-se as observações em ordem crescente;</li>
<li>Associam-se valores, correspondendo às suas posições relativas na amostra. O primeiro elemento recebe o valor 1, o segundo o valor 2 e, assim por diante, até que a maior observação receba o valor <em>n</em>;</li>
<li>Se todas as observações são distintas, os postos são iguais aos valores associados às observações no passo anterior.</li>
<li>Para observações iguais (empates), associam-se postos iguais à média das suas posições relativas na amostra.</li>
</ol>
<p>Por exemplo, suponha uma amostra contendo os escores de Apgar no primeiro minuto de 10 recém-nascidos a termo (Tabela <a href="métodos-não-paramétricos.html#tab:apgar1">17.1</a>). Em primeiro lugar, os valores são colocados em ordem crescente e, após, atribui-se postos aos valores. Observe que os postos atribuídos aos valores das posições 3 e 4 são iguais e correspondentes a média de 3 e 4, que é igual a 3,5. O mesmo ocorreu com os outros valores onde houve empate. A soma dos postos, no exemplo, é igual a 55. Para verificar a correção do cálculo, haja ou não empates, a soma dos postos será sempre <span class="math inline">\(\frac {n\ \times \ (n+1)}{2}\)</span>. No exemplo, <em>n</em> = 10, logo <span class="math inline">\(\frac {10\ \times \ (10+1)}{2}=55\)</span>.</p>
<table class="table lightable-classic" style="width: auto !important; margin-left: auto; margin-right: auto; font-family: Cambria; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:apgar1">Tabela 17.1: </span><span id="tab:apgar1">Tabela 17.2: </span>Construção dos postos
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Apgar 1
</th>
<th style="text-align:center;font-weight: bold;">
Ordem
</th>
<th style="text-align:center;font-weight: bold;">
Posto
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 3cm; ">
4
</td>
<td style="text-align:center;width: 3cm; ">
1
</td>
<td style="text-align:center;width: 3cm; ">
1.0
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
5
</td>
<td style="text-align:center;width: 3cm; ">
2
</td>
<td style="text-align:center;width: 3cm; ">
2.0
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
7
</td>
<td style="text-align:center;width: 3cm; ">
3
</td>
<td style="text-align:center;width: 3cm; ">
3.0
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
8
</td>
<td style="text-align:center;width: 3cm; ">
4
</td>
<td style="text-align:center;width: 3cm; ">
5.0
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
8
</td>
<td style="text-align:center;width: 3cm; ">
5
</td>
<td style="text-align:center;width: 3cm; ">
5.0
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
8
</td>
<td style="text-align:center;width: 3cm; ">
6
</td>
<td style="text-align:center;width: 3cm; ">
5.0
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
9
</td>
<td style="text-align:center;width: 3cm; ">
7
</td>
<td style="text-align:center;width: 3cm; ">
7.5
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
9
</td>
<td style="text-align:center;width: 3cm; ">
8
</td>
<td style="text-align:center;width: 3cm; ">
7.5
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
10
</td>
<td style="text-align:center;width: 3cm; ">
9
</td>
<td style="text-align:center;width: 3cm; ">
9.5
</td>
</tr>
<tr>
<td style="text-align:center;width: 3cm; ">
10
</td>
<td style="text-align:center;width: 3cm; ">
10
</td>
<td style="text-align:center;width: 3cm; ">
9.5
</td>
</tr>
</tbody>
</table>
</div>
<div id="teste-de-mann-whitney" class="section level2 hasAnchor" number="17.4">
<h2><span class="header-section-number">17.4</span> Teste de Mann-Whitney<a href="métodos-não-paramétricos.html#teste-de-mann-whitney" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O <em>teste de Mann-Whitney</em> é usado para analisar a diferença na variável dependente (desfecho) para dois grupos independentes. O teste classifica todos os valores dependentes, ou seja, o valor mais baixo obtém o posto um e, em seguida, usa a soma dos postos de cada grupo no cálculo da estatística de teste.</p>
<p>É o substituto do teste <em>t</em> para amostras independentes quando os pressupostos deste teste são violados. Para a aplicação do teste de Mann-Whitney a variável de interesse deve ser ordinal ou numérica. Este teste é equivalente ao desenvolvido por Frank Wilcoxon (1892 – 1965), assim algumas vezes é denominado de <em>Wilcoxon Rank Sum Test</em>. O R usa esta denominação e é importante não confundir com o teste não paramétrico para amostra pareadas, discutido mais adiante.</p>
<div id="dados-usados-nesta-seção-11" class="section level3 hasAnchor" number="17.4.1">
<h3><span class="header-section-number">17.4.1</span> Dados usados nesta seção<a href="#dados-usados-nesta-se%C3%A7%C3%A3o-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O arquivo <code>dadosCirurgia.xlsx</code>, já usado na Seção <a href="análise-de-dados-categóricos.html#sec-dadosCirurgia">16.2.5.1</a>, fornecerá os dados para esta seção. Ele contém 144 recém-nascidos que foram submetidos a diferentes procedimentos cirúrgicos.
A questão de pesquisa a ser respondida é:</p>
<blockquote>
<p><font size=2>Existe diferença no tempo de hospitalização (<code>tempohosp</code>) dos recém-nascidos de acordo com a presença ou não de infecção (<code>infec</code>)?</font></p>
</blockquote>
<p>Essa pergunta foi respondida de outra maneira, na Seção <a href="análise-de-dados-categóricos.html#sec-tabextensas">16.2.5</a>. Agora, será usado o teste de Mann-Whitney.</p>
<div id="leitura-exploração-e-visualização-dos-dados" class="section level4 hasAnchor" number="17.4.1.1">
<h4><span class="header-section-number">17.4.1.1</span> Leitura, exploração e visualização dos dados<a href="#leitura-explora%C3%A7%C3%A3o-e-visualiza%C3%A7%C3%A3o-dos-dados" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Os dados serão lidos com a função <code>read_excel()</code> do pacote <code>readxl</code>:</p>
<div class="sourceCode" id="cb975"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb975-1"><a href="métodos-não-paramétricos.html#cb975-1" tabindex="-1"></a>cirurgia <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span> (<span class="st">&quot;Arquivos/dadosCirurgia.xlsx&quot;</span>)</span>
<span id="cb975-2"><a href="métodos-não-paramétricos.html#cb975-2" tabindex="-1"></a><span class="fu">str</span>(cirurgia)</span></code></pre></div>
<pre><code>## tibble [144 × 7] (S3: tbl_df/tbl/data.frame)
##  $ id       : num [1:144] 1 2 3 4 5 6 7 8 9 10 ...
##  $ sexo     : chr [1:144] &quot;masc&quot; &quot;masc&quot; &quot;masc&quot; &quot;masc&quot; ...
##  $ peso     : num [1:144] 2020 1850 2540 1150 2900 ...
##  $ ig       : num [1:144] 36 30 38 31 36 37 38 39 38 39 ...
##  $ tempohosp: num [1:144] 37 37 37 46 37 36 30 18 25 14 ...
##  $ infec    : chr [1:144] &quot;não&quot; &quot;não&quot; &quot;sim&quot; &quot;sim&quot; ...
##  $ cirurgia : chr [1:144] &quot;abdominal&quot; &quot;abdominal&quot; &quot;abdominal&quot; &quot;outra&quot; ...</code></pre>
<p>A variável <code>infec</code> aparece como caractere e será transformada como fator:</p>
<div class="sourceCode" id="cb977"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb977-1"><a href="métodos-não-paramétricos.html#cb977-1" tabindex="-1"></a>cirurgia<span class="sc">$</span>infec <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(cirurgia<span class="sc">$</span>infec)</span></code></pre></div>
<p>Os boxplots (Figura <a href="métodos-não-paramétricos.html#fig:bpapgar1">17.1</a>), construídos com a função <code>ggboxplot()</code> do pacote <code>ggpubr</code> com as cores da paleta do <em>New England Journal of Medicine (NEJM)</em>, são uma boa maneira de visualizar os dados:</p>
<div class="sourceCode" id="cb978"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb978-1"><a href="métodos-não-paramétricos.html#cb978-1" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span>(cirurgia,</span>
<span id="cb978-2"><a href="métodos-não-paramétricos.html#cb978-2" tabindex="-1"></a>                  <span class="at">x =</span> <span class="st">&quot;infec&quot;</span>,</span>
<span id="cb978-3"><a href="métodos-não-paramétricos.html#cb978-3" tabindex="-1"></a>                  <span class="at">y =</span> <span class="st">&quot;tempohosp&quot;</span>,</span>
<span id="cb978-4"><a href="métodos-não-paramétricos.html#cb978-4" tabindex="-1"></a>                  <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb978-5"><a href="métodos-não-paramétricos.html#cb978-5" tabindex="-1"></a>                  <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>,</span>
<span id="cb978-6"><a href="métodos-não-paramétricos.html#cb978-6" tabindex="-1"></a>                  <span class="at">fill =</span> <span class="st">&quot;infec&quot;</span>,</span>
<span id="cb978-7"><a href="métodos-não-paramétricos.html#cb978-7" tabindex="-1"></a>                  <span class="at">palette =</span> <span class="st">&quot;nejm&quot;</span>,</span>
<span id="cb978-8"><a href="métodos-não-paramétricos.html#cb978-8" tabindex="-1"></a>                  <span class="at">legend =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb978-9"><a href="métodos-não-paramétricos.html#cb978-9" tabindex="-1"></a>                  <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb978-10"><a href="métodos-não-paramétricos.html#cb978-10" tabindex="-1"></a>                  <span class="at">xlab =</span> <span class="st">&quot;Presença de infecção&quot;</span> ,</span>
<span id="cb978-11"><a href="métodos-não-paramétricos.html#cb978-11" tabindex="-1"></a>                  <span class="at">ylab =</span> <span class="st">&quot;Tempo de hospitalização (dias)&quot;</span>)   </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bpapgar1"></span>
<img src="bookdownproj_files/figure-html/bpapgar1-1.png" alt="Impacto da infecção no tempo de hopsitalização." width="70%" height="70%" />
<p class="caption">
Figura 17.1: Impacto da infecção no tempo de hopsitalização.
</p>
</div>
<p>Os boxplots exibem uma série de valores atípicos, indicando que existe uma assimetria em ambos os grupos. Essa assimetria também pode ser verificada usando o teste de Shapiro-Wilk, que mostrando valores <em>P</em> &lt; 0,05, confirma que os dados não seguem a distribuição normal. Este teste não é pré-requisito para o teste. Foi realizado como uma demonstração.</p>
<div class="sourceCode" id="cb979"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb979-1"><a href="métodos-não-paramétricos.html#cb979-1" tabindex="-1"></a>cirurgia <span class="sc">%&gt;%</span> </span>
<span id="cb979-2"><a href="métodos-não-paramétricos.html#cb979-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(infec) <span class="sc">%&gt;%</span> </span>
<span id="cb979-3"><a href="métodos-não-paramétricos.html#cb979-3" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">shapiro_test</span>(tempohosp)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   infec variable  statistic        p
##   &lt;fct&gt; &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;
## 1 não   tempohosp     0.565 9.87e-15
## 2 sim   tempohosp     0.692 1.47e- 9</code></pre>
</div>
<div id="sumarização-dos-dados-2" class="section level4 hasAnchor" number="17.4.1.2">
<h4><span class="header-section-number">17.4.1.2</span> Sumarização dos dados<a href="#sumariza%C3%A7%C3%A3o-dos-dados-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Como a variável <code>tempohosp</code> é assimétrica conforme mostrado acima, onde ambos os valores <em>P</em> são menores do que 0,05, será realizado um sumário numérico com a obtenção da mediana e IIQ. Isto será feito através da função <code>group_by()</code> e <code>summarise()</code>, incluídas no pacote <code>dplyr</code>.</p>
<div class="sourceCode" id="cb981"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb981-1"><a href="métodos-não-paramétricos.html#cb981-1" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> cirurgia <span class="sc">%&gt;%</span> </span>
<span id="cb981-2"><a href="métodos-não-paramétricos.html#cb981-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(infec) <span class="sc">%&gt;%</span> </span>
<span id="cb981-3"><a href="métodos-não-paramétricos.html#cb981-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb981-4"><a href="métodos-não-paramétricos.html#cb981-4" tabindex="-1"></a>                   <span class="at">mediana =</span> <span class="fu">median</span> (tempohosp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb981-5"><a href="métodos-não-paramétricos.html#cb981-5" tabindex="-1"></a>                   <span class="at">p25=</span><span class="fu">quantile</span>(tempohosp, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb981-6"><a href="métodos-não-paramétricos.html#cb981-6" tabindex="-1"></a>                   <span class="at">p75=</span><span class="fu">quantile</span>(tempohosp, <span class="at">probs =</span> <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb981-7"><a href="métodos-não-paramétricos.html#cb981-7" tabindex="-1"></a>resumo</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   infec     n mediana   p25   p75
##   &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 não      88      23  18      37
## 2 sim      56      37  22.8    49</code></pre>
<p>Os dados mostram que a mediana de tempo de internação dos neonatos infectados é bem maior do que os não infectados. A diferença mediana e os intervalos de confiança para essa diferença pode ser calculada com a função <code>ci_quantile_diff()</code> do pacote <code>confintr</code> <span class="citation">(145)</span>.</p>
<div class="sourceCode" id="cb983"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb983-1"><a href="métodos-não-paramétricos.html#cb983-1" tabindex="-1"></a>infectado <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(cirurgia, infec <span class="sc">==</span> <span class="st">&quot;sim&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb983-2"><a href="métodos-não-paramétricos.html#cb983-2" tabindex="-1"></a>  <span class="fu">select</span>(tempohosp)</span>
<span id="cb983-3"><a href="métodos-não-paramétricos.html#cb983-3" tabindex="-1"></a>sem_infec <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(cirurgia, infec <span class="sc">==</span> <span class="st">&quot;não&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb983-4"><a href="métodos-não-paramétricos.html#cb983-4" tabindex="-1"></a>  <span class="fu">select</span>(tempohosp)</span>
<span id="cb983-5"><a href="métodos-não-paramétricos.html#cb983-5" tabindex="-1"></a></span>
<span id="cb983-6"><a href="métodos-não-paramétricos.html#cb983-6" tabindex="-1"></a>dif_mediana <span class="ot">&lt;-</span> <span class="fu">median</span>(infectado<span class="sc">$</span>tempohosp)<span class="sc">-</span> <span class="fu">median</span>(sem_infec<span class="sc">$</span>tempohosp)</span>
<span id="cb983-7"><a href="métodos-não-paramétricos.html#cb983-7" tabindex="-1"></a>dif_mediana</span></code></pre></div>
<pre><code>## [1] 14</code></pre>
<div class="sourceCode" id="cb985"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb985-1"><a href="métodos-não-paramétricos.html#cb985-1" tabindex="-1"></a><span class="fu">ci_quantile_diff</span>(infectado, sem_infec)</span></code></pre></div>
<pre><code>## 
##  Two-sided 95% bootstrap confidence interval for the population value of
##  50% quantile(x) - 50% quantile(y) based on 9999 bootstrap replications
##  and the bca method
## 
## Sample estimate: 14 
## Confidence interval:
##  2.5% 97.5% 
##   4.5  19.5</code></pre>
<p>Dessa forma, a mediana da diferença entre os dois grupos foi de 14 dias (IC95%; 5 - 20).</p>
</div>
</div>
<div id="hipóteses-estatísticas-6" class="section level3 hasAnchor" number="17.4.2">
<h3><span class="header-section-number">17.4.2</span> Hipóteses estatísticas<a href="#hip%C3%B3teses-estat%C3%ADsticas-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Da mesma maneira que o teste <em>t</em>, as hipóteses estabelecidas comparam dois grupos independentes. Se não houver diferença entre os grupos, ou seja, os grupos são provenientes de uma mesma população, as somas dos postos em cada grupo devem ficar próximas. Desta forma,</p>
<blockquote>
<p><font size=2> <strong><span class="math inline">\(H_{0}\)</span></strong>: As duas populações são iguais.<br />
<strong><span class="math inline">\(H_{1}\)</span></strong>: As duas populações não são iguais. </font></p>
</blockquote>
<p>Não foi escrita a hipótese nula como sendo de que as médias (ou as medianas) são iguais, pois o teste não usa as medidas de posição tradicionais e sim os postos.</p>
</div>
<div id="pressupostos-do-teste-de-mann_whitney" class="section level3 hasAnchor" number="17.4.3">
<h3><span class="header-section-number">17.4.3</span> Pressupostos do teste de Mann_Whitney<a href="métodos-não-paramétricos.html#pressupostos-do-teste-de-mann_whitney" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O teste de Mann-Whitney é baseado nos seguintes pressupostos:</p>
<ol style="list-style-type: decimal">
<li>Os dados são aleatórios;</li>
<li>As amostras são de dois grupos independentes;</li>
<li>Um dos grupos é denominado de 1 e o outro de 2;</li>
<li>A variável a ser comparada nos grupos deve ser ordenável;</li>
<li>O grupo 1 será o grupo de menor tamanho e, se tiverem o mesmo tamanho, o grupo 1 é aquele cuja soma dos postos é a menor.</li>
</ol>
</div>
<div id="cálculo-da-estatística-de-teste" class="section level3 hasAnchor" number="17.4.4">
<h3><span class="header-section-number">17.4.4</span> Cálculo da estatística de teste<a href="#c%C3%A1lculo-da-estat%C3%ADstica-de-teste" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="lógica-do-teste-u-de-mann-whitney" class="section level4 hasAnchor" number="17.4.4.1">
<h4><span class="header-section-number">17.4.4.1</span> Lógica do teste U de Mann-Whitney<a href="#l%C3%B3gica-do-teste-u-de-mann-whitney" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>De acordo com as hipóteses estabelecidas, o teste é bicaudal. Se as observações nos dois grupos forem provenientes da mesma população, a soma dos postos em cada grupo devem ficar próximas.</p>
<p>Para calcular o teste, procede-se da seguinte maneira:</p>
<ol style="list-style-type: decimal">
<li><p>Deve haver uma variável que identifique o grupo a que pertence cada uma das observações. No exemplo proposto, a variável desfecho é <code>tempohosp</code> e a variável agrupadora é <code>infec</code>, categorizada como <code>sim</code> e <code>não</code>.</p></li>
<li><p>Ordenar de forma crescente todos os valores da variável <code>tempohosp</code>, sem levar em consideração a que grupo pertence. Para realizar este procedimento, será usada a função <code>rank()</code> do R base com o método para empates igual à média dos valores empatados (<code>ties.method="average</code>). Ao executar a função, será criada uma nova variável, denotada <code>postos</code>.</p></li>
</ol>
<div class="sourceCode" id="cb987"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb987-1"><a href="métodos-não-paramétricos.html#cb987-1" tabindex="-1"></a>cirurgia<span class="sc">$</span>postos <span class="ot">&lt;-</span> <span class="fu">rank</span>(cirurgia<span class="sc">$</span>tempohosp, <span class="at">ties.method =</span> <span class="st">&quot;average&quot;</span>) </span>
<span id="cb987-2"><a href="métodos-não-paramétricos.html#cb987-2" tabindex="-1"></a><span class="fu">head</span>(cirurgia)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 8
##      id sexo   peso    ig tempohosp infec cirurgia  postos
##   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt; &lt;chr&gt;      &lt;dbl&gt;
## 1     1 masc   2020    36        37 não   abdominal   94.5
## 2     2 masc   1850    30        37 não   abdominal   94.5
## 3     3 masc   2540    38        37 sim   abdominal   94.5
## 4     4 masc   1150    31        46 sim   outra      120  
## 5     5 masc   2900    36        37 não   abdominal   94.5
## 6     6 fem    2480    37        36 sim   abdominal   91</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Verificar o tamanho (<em>n</em>) de cada grupo (presença ou não de infecção) e somar os postos em cada um dos grupos, usando a função <code>group_by()</code> junto com a função <code>summarise()</code>,</li>
</ol>
<div class="sourceCode" id="cb989"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb989-1"><a href="métodos-não-paramétricos.html#cb989-1" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> cirurgia <span class="sc">%&gt;%</span> </span>
<span id="cb989-2"><a href="métodos-não-paramétricos.html#cb989-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(infec) <span class="sc">%&gt;%</span> </span>
<span id="cb989-3"><a href="métodos-não-paramétricos.html#cb989-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb989-4"><a href="métodos-não-paramétricos.html#cb989-4" tabindex="-1"></a>                   <span class="at">soma =</span> <span class="fu">sum</span>(postos))</span>
<span id="cb989-5"><a href="métodos-não-paramétricos.html#cb989-5" tabindex="-1"></a>resumo</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   infec     n  soma
##   &lt;fct&gt; &lt;int&gt; &lt;dbl&gt;
## 1 não      88 5564.
## 2 sim      56 4876.</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Denominar de <em>grupo_1</em> o grupo com menor soma:</li>
</ol>
<div class="sourceCode" id="cb991"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb991-1"><a href="métodos-não-paramétricos.html#cb991-1" tabindex="-1"></a>grupo_1 <span class="ot">&lt;-</span> <span class="fu">min</span>(resumo<span class="sc">$</span>soma)</span>
<span id="cb991-2"><a href="métodos-não-paramétricos.html#cb991-2" tabindex="-1"></a>grupo_1</span></code></pre></div>
<pre><code>## [1] 4875.5</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Denotar o <em>grupo_1</em> como T</li>
</ol>
<div class="sourceCode" id="cb993"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb993-1"><a href="métodos-não-paramétricos.html#cb993-1" tabindex="-1"></a>T <span class="ot">&lt;-</span> grupo_1</span></code></pre></div>
<p>Consequentemente,</p>
<div class="sourceCode" id="cb994"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb994-1"><a href="métodos-não-paramétricos.html#cb994-1" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="dv">56</span></span>
<span id="cb994-2"><a href="métodos-não-paramétricos.html#cb994-2" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">88</span></span></code></pre></div>
<ol start="6" style="list-style-type: decimal">
<li>Calcular a estística do teste, usando a fórmula preconizada por Altman <span class="citation">(146)</span>:</li>
</ol>
<p><span class="math display">\[
U =n_{1} \times n_{2} \ +\left [\frac{n_{1} \times \left (n_{1} + 1  \right )}{2}  \right ] - T
\]</span></p>
<div class="sourceCode" id="cb995"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb995-1"><a href="métodos-não-paramétricos.html#cb995-1" tabindex="-1"></a>U <span class="ot">&lt;-</span> (n1<span class="sc">*</span>n2 <span class="sc">+</span> ((n1<span class="sc">*</span>(n1 <span class="sc">+</span> <span class="dv">1</span>))<span class="sc">/</span><span class="dv">2</span>)) <span class="sc">-</span> T</span>
<span id="cb995-2"><a href="métodos-não-paramétricos.html#cb995-2" tabindex="-1"></a>U</span></code></pre></div>
<pre><code>## [1] 1648.5</code></pre>
<p><strong>Obs</strong>.: O U de Mann-Whitney aparece no teste de Wilcoxon como W, eles são iguais</p>
<ol start="7" style="list-style-type: decimal">
<li>Se <span class="math inline">\(n_{1}\)</span>, <span class="math inline">\(n_{2}\)</span> <span class="math inline">\(\ge\)</span> 10, a distribuição da estatística do teste pode ser aproximada por uma distribuição normal com média igual a</li>
</ol>
<p><span class="math display">\[
\mu_{U} =\left [\frac{n_{S} \times \left (n_{L} + 1  \right )}{2}  \right ]
\]</span></p>
<p>onde <span class="math inline">\(n_{S}\)</span> e <span class="math inline">\(n_{L}\)</span>, são, respectivamente, o grupo de menor e maior tamanho. No exemplo, <span class="math inline">\(n_{1}\)</span> e <span class="math inline">\(n_{2}\)</span>.</p>
<div class="sourceCode" id="cb997"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb997-1"><a href="métodos-não-paramétricos.html#cb997-1" tabindex="-1"></a>m_U <span class="ot">&lt;-</span> (n1<span class="sc">*</span>(n1<span class="sc">+</span>n2<span class="sc">+</span><span class="dv">1</span>))<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb997-2"><a href="métodos-não-paramétricos.html#cb997-2" tabindex="-1"></a>m_U</span></code></pre></div>
<pre><code>## [1] 4060</code></pre>
<p>E desvio padrão igual a</p>
<p><span class="math display">\[
\sigma_{U}= \sqrt {\frac{n_{L}\times \sigma_{U}}{6}}
\]</span></p>
<div class="sourceCode" id="cb999"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb999-1"><a href="métodos-não-paramétricos.html#cb999-1" tabindex="-1"></a>dp_U <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((n2<span class="sc">*</span>m_U)<span class="sc">/</span><span class="dv">6</span>)</span>
<span id="cb999-2"><a href="métodos-não-paramétricos.html#cb999-2" tabindex="-1"></a>dp_U</span></code></pre></div>
<pre><code>## [1] 244.0219</code></pre>
<p>Os resultados fornecem os dados para calcular a estatística <span class="math inline">\(Z_{U}\)</span> com correção de continuidade e, a partir dela, calcular o valor <em>P</em>.</p>
<p><span class="math display">\[
Z_{U}= \frac{(T -0,5) - \mu_{U}}{\sigma_{U}}
\]</span></p>
<div class="sourceCode" id="cb1001"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1001-1"><a href="métodos-não-paramétricos.html#cb1001-1" tabindex="-1"></a>Z_U <span class="ot">&lt;-</span> ((T <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">-</span> m_U)<span class="sc">/</span>dp_U</span>
<span id="cb1001-2"><a href="métodos-não-paramétricos.html#cb1001-2" tabindex="-1"></a><span class="fu">round</span>(Z_U, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 3.34</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Finalmente, calcula-se o valor <em>P</em>, usando a função <code>pnorm()</code>, multiplicada por 2, pois o teste é bicaudal.</li>
</ol>
<div class="sourceCode" id="cb1003"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1003-1"><a href="métodos-não-paramétricos.html#cb1003-1" tabindex="-1"></a>P <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(Z_U, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb1003-2"><a href="métodos-não-paramétricos.html#cb1003-2" tabindex="-1"></a><span class="fu">round</span>(P, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 8e-04</code></pre>
<p>Na prática, não há necessidade de fazer todos esses cálculos, pois o <em>R</em> calcula facilmente o teste. Os cálculos foram mostrados para melhorar o entendimento de como o teste de Mann-Whitney funciona.</p>
</div>
<div id="cálculo-do-u-de-mann-whitney-no-r" class="section level4 hasAnchor" number="17.4.4.2">
<h4><span class="header-section-number">17.4.4.2</span> Cálculo do U de Mann-Whitney no R<a href="#c%C3%A1lculo-do-u-de-mann-whitney-no-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>O teste pode ser realizado com a função <code>wilcox_test()</code> <a href="#fn66" class="footnote-ref" id="fnref66"><sup>66</sup></a> do pacote <code>rstatix</code>:</p>
<div class="sourceCode" id="cb1005"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1005-1"><a href="métodos-não-paramétricos.html#cb1005-1" tabindex="-1"></a>teste <span class="ot">&lt;-</span> rstatix<span class="sc">::</span><span class="fu">wilcox_test</span>(<span class="at">formula =</span> tempohosp <span class="sc">~</span> infec, <span class="at">data =</span> cirurgia)</span>
<span id="cb1005-2"><a href="métodos-não-paramétricos.html#cb1005-2" tabindex="-1"></a>teste</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.       group1 group2    n1    n2 statistic       p
## * &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 tempohosp não    sim       88    56     1648. 0.00083</code></pre>
<p>Assim como no cálculo manual, o teste no R, mostra uma diferença estatisticamente significativa (<em>P</em> = 0,00083) entre os tempos de hospitalização dos recém-nascidos que realizaram cirurgia no período neonatal que se infectaram ou não (diferença mediana = 14 dias; IC95% : 5,0 – 19,5).</p>
</div>
</div>
<div id="sec-tefMW" class="section level3 hasAnchor" number="17.4.5">
<h3><span class="header-section-number">17.4.5</span> Tamanho do efeito<a href="métodos-não-paramétricos.html#sec-tefMW" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>É interessante calcular o tamanho do efeito, a magnitude do efeito. O tamanho do efeito <em>r</em> é calculado como a estatística <span class="math inline">\(Z_{U}\)</span> dividida pela raiz quadrada do tamanho da amostra (<span class="math inline">\(n = n_{1} + n_{2}\)</span>).</p>
<p><span class="math display">\[
r = \frac {Z_{U}}{\sqrt{n}}
\]</span></p>
<p>O valor de <span class="math inline">\(Z_{U}\)</span> é igual a 3.3398648, logo</p>
<div class="sourceCode" id="cb1007"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1007-1"><a href="métodos-não-paramétricos.html#cb1007-1" tabindex="-1"></a>r <span class="ot">&lt;-</span> Z_U<span class="sc">/</span><span class="fu">sqrt</span>(n1<span class="sc">+</span>n2)</span>
<span id="cb1007-2"><a href="métodos-não-paramétricos.html#cb1007-2" tabindex="-1"></a><span class="fu">round</span>(r,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.278</code></pre>
<p>O R possui a função <code>wilcox_effsize()</code> do pacote <code>rstatix</code> e necessita também do pacote <code>coin</code> <span class="citation">(147)</span> , instalado para calcular a estatística <em>r</em>.<a href="#fn67" class="footnote-ref" id="fnref67"><sup>67</sup></a> A saída exibirá junto a magnitude o efeito, que no caso é pequena (veja Tabela <a href="métodos-não-paramétricos.html#tab:wilcoxef">17.3</a>).</p>
<div class="sourceCode" id="cb1009"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1009-1"><a href="métodos-não-paramétricos.html#cb1009-1" tabindex="-1"></a><span class="fu">wilcox_effsize</span>(cirurgia, tempohosp<span class="sc">~</span>infec)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.       group1 group2 effsize    n1    n2 magnitude
## * &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;ord&gt;    
## 1 tempohosp não    sim      0.279    88    56 small</code></pre>
<table class="table lightable-classic" style="width: auto !important; margin-left: auto; margin-right: auto; font-family: Cambria; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:wilcoxef">Tabela 17.3: </span><span id="tab:wilcoxef">Tabela 17.4: </span>Interpretação do valor r (sem considerar o sinal)
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Valor r
</th>
<th style="text-align:center;font-weight: bold;">
Magnitude
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 4cm; ">
0,10 &lt; 0,30
</td>
<td style="text-align:center;width: 4cm; ">
pequeno
</td>
</tr>
<tr>
<td style="text-align:center;width: 4cm; ">
0,30 &lt; 0,50
</td>
<td style="text-align:center;width: 4cm; ">
médio
</td>
</tr>
<tr>
<td style="text-align:center;width: 4cm; ">
&gt;= 0,50
</td>
<td style="text-align:center;width: 4cm; ">
grande
</td>
</tr>
</tbody>
</table>
</div>
<div id="conclusão-7" class="section level3 hasAnchor" number="17.4.6">
<h3><span class="header-section-number">17.4.6</span> Conclusão<a href="#conclus%C3%A3o-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O valor <span class="math inline">\(P&lt;0,0001\)</span>, bem abaixo do nível de significância estabelecido (<span class="math inline">\(\alpha = 0,05)\)</span>. Pode-se concluir que o tempo de hospitalização nos dois grupos é estatisticamente diferente. Entretanto, a magnitude dessa diferença é pequena.</p>
<p>Isto pode ser visualizado no gráfico (Figura <a href="métodos-não-paramétricos.html#fig:bpres">17.2</a>):</p>
<div class="sourceCode" id="cb1011"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1011-1"><a href="métodos-não-paramétricos.html#cb1011-1" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span>(cirurgia,</span>
<span id="cb1011-2"><a href="métodos-não-paramétricos.html#cb1011-2" tabindex="-1"></a>                   <span class="at">x =</span> <span class="st">&quot;infec&quot;</span>,</span>
<span id="cb1011-3"><a href="métodos-não-paramétricos.html#cb1011-3" tabindex="-1"></a>                   <span class="at">y =</span> <span class="st">&quot;tempohosp&quot;</span>,</span>
<span id="cb1011-4"><a href="métodos-não-paramétricos.html#cb1011-4" tabindex="-1"></a>                   <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1011-5"><a href="métodos-não-paramétricos.html#cb1011-5" tabindex="-1"></a>                   <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>,</span>
<span id="cb1011-6"><a href="métodos-não-paramétricos.html#cb1011-6" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">&quot;infec&quot;</span>,</span>
<span id="cb1011-7"><a href="métodos-não-paramétricos.html#cb1011-7" tabindex="-1"></a>                   <span class="at">palette =</span> <span class="st">&quot;nejm&quot;</span>,</span>
<span id="cb1011-8"><a href="métodos-não-paramétricos.html#cb1011-8" tabindex="-1"></a>                   <span class="at">legend =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb1011-9"><a href="métodos-não-paramétricos.html#cb1011-9" tabindex="-1"></a>                   <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb1011-10"><a href="métodos-não-paramétricos.html#cb1011-10" tabindex="-1"></a>                   <span class="at">xlab =</span> <span class="st">&quot;Presença de infecção&quot;</span> ,</span>
<span id="cb1011-11"><a href="métodos-não-paramétricos.html#cb1011-11" tabindex="-1"></a>                   <span class="at">ylab =</span> <span class="st">&quot;Tempo de hospitalização (dias)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1011-12"><a href="métodos-não-paramétricos.html#cb1011-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> rstatix<span class="sc">::</span><span class="fu">get_test_label</span>(teste, <span class="at">detailed =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bpres"></span>
<img src="bookdownproj_files/figure-html/bpres-1.png" alt="Impacto da infecção no tempo de hopsitalização." width="70%" height="70%" />
<p class="caption">
Figura 17.2: Impacto da infecção no tempo de hopsitalização.
</p>
</div>
</div>
</div>
<div id="teste-de-wilcoxon" class="section level2 hasAnchor" number="17.5">
<h2><span class="header-section-number">17.5</span> Teste de Wilcoxon<a href="métodos-não-paramétricos.html#teste-de-wilcoxon" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O <em>teste de Wilcoxon</em>, também conhecido como teste dos postos com sinais de Wilcoxon (<em>Wilcoxon Signed-Rank Test</em>), é um teste não paramétrico utilizado em situações em que existem dois conjuntos de dados emparelhados, ou seja, dados provenientes do mesmo participante. O teste não examina os dois grupos individualmente; em vez disso, ele se concentra na diferença existente entre cada par de observações. É um equivalente não paramétrico do teste <em>t</em> pareado.</p>
<div id="dados-usados-nesta-seção-12" class="section level3 hasAnchor" number="17.5.1">
<h3><span class="header-section-number">17.5.1</span> Dados usados nesta seção<a href="#dados-usados-nesta-se%C3%A7%C3%A3o-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pata verificar se a realização de exercícios aeróbicos modifica a função respiratória de 10 escolares asmáticos, foi medido o Pico de Fluxo Expiratório Máximo (<em>Peak Flow Meter</em>) no início e no final do programa, após 120 dias. O Pico de Fluxo Expiratório Máximo (PFE) serve como uma forma simples de avaliar a força e a velocidade de saída do ar de dentro dos pulmões. É medido em L/min. Os resultados do estudo tem apenas três variáveis, <code>id</code>, <code>basal</code> e <code>final</code>.</p>
<div class="sourceCode" id="cb1012"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1012-1"><a href="métodos-não-paramétricos.html#cb1012-1" tabindex="-1"></a>id <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb1012-2"><a href="métodos-não-paramétricos.html#cb1012-2" tabindex="-1"></a>basal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">200</span>, <span class="dv">140</span>, <span class="dv">200</span>, <span class="dv">110</span>, <span class="dv">240</span>, <span class="dv">150</span>, <span class="dv">120</span>, <span class="dv">250</span>, <span class="dv">190</span>)</span>
<span id="cb1012-3"><a href="métodos-não-paramétricos.html#cb1012-3" tabindex="-1"></a>final <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">220</span>, <span class="dv">300</span>, <span class="dv">230</span>, <span class="dv">180</span>, <span class="dv">300</span>, <span class="dv">330</span>, <span class="dv">230</span>, <span class="dv">250</span>, <span class="dv">300</span>, <span class="dv">200</span>)</span>
<span id="cb1012-4"><a href="métodos-não-paramétricos.html#cb1012-4" tabindex="-1"></a></span>
<span id="cb1012-5"><a href="métodos-não-paramétricos.html#cb1012-5" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">tibble</span>(id, basal, final)</span>
<span id="cb1012-6"><a href="métodos-não-paramétricos.html#cb1012-6" tabindex="-1"></a></span>
<span id="cb1012-7"><a href="métodos-não-paramétricos.html#cb1012-7" tabindex="-1"></a><span class="fu">head</span> (dados)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##      id basal final
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1   120   220
## 2     2   200   300
## 3     3   140   230
## 4     4   200   180
## 5     5   110   300
## 6     6   240   330</code></pre>
<p>A questão de pesquisa a ser respondida, portanto, é:</p>
<blockquote>
<p><font size=2>Existe diferença entre as medidas iniciais e finais do PFE dos escolares asmáticos que entraram em um programa de exercícios aeróbicos?</font></p>
</blockquote>
<div id="exploração-e-transformação-dos-dados-2" class="section level4 hasAnchor" number="17.5.1.1">
<h4><span class="header-section-number">17.5.1.1</span> Exploração e transformação dos dados<a href="#explora%C3%A7%C3%A3o-e-transforma%C3%A7%C3%A3o-dos-dados-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Os dados estão no formato amplo com as variáveis basal e final classificadas como númericas. Será transformado para o formato longo, usando a função <code>pivot_longer()</code> do pacote <code>tidyr</code>. Este processo é opcional, mas, como foi feito com o teste <em>t</em> pareado, será repetido aqui como treinamento:</p>
<div class="sourceCode" id="cb1014"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1014-1"><a href="métodos-não-paramétricos.html#cb1014-1" tabindex="-1"></a>dadosL <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb1014-2"><a href="métodos-não-paramétricos.html#cb1014-2" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="fu">c</span>(basal, final), </span>
<span id="cb1014-3"><a href="métodos-não-paramétricos.html#cb1014-3" tabindex="-1"></a>                      <span class="at">names_to =</span> <span class="st">&quot;momento&quot;</span>, </span>
<span id="cb1014-4"><a href="métodos-não-paramétricos.html#cb1014-4" tabindex="-1"></a>                      <span class="at">values_to =</span> <span class="st">&quot;medidas&quot;</span>)</span>
<span id="cb1014-5"><a href="métodos-não-paramétricos.html#cb1014-5" tabindex="-1"></a><span class="fu">str</span>(dadosL)</span></code></pre></div>
<pre><code>## tibble [20 × 3] (S3: tbl_df/tbl/data.frame)
##  $ id     : int [1:20] 1 1 2 2 3 3 4 4 5 5 ...
##  $ momento: chr [1:20] &quot;basal&quot; &quot;final&quot; &quot;basal&quot; &quot;final&quot; ...
##  $ medidas: num [1:20] 120 220 200 300 140 230 200 180 110 300 ...</code></pre>
</div>
<div id="medidas-resumidoras-3" class="section level4 hasAnchor" number="17.5.1.2">
<h4><span class="header-section-number">17.5.1.2</span> Medidas resumidoras<a href="métodos-não-paramétricos.html#medidas-resumidoras-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Como o número de participantes é de apenas 10, a medida de posição mais adequada para resumir os dados é mediana e a medida de dispersão é o intervalo interquartil (IIQ). Para isso, se fará uso das funções <code>group_by()</code> e <code>summarise()</code> do pacote <code>dplyr</code>:</p>
<div class="sourceCode" id="cb1016"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1016-1"><a href="métodos-não-paramétricos.html#cb1016-1" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> dadosL <span class="sc">%&gt;%</span> </span>
<span id="cb1016-2"><a href="métodos-não-paramétricos.html#cb1016-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(momento) <span class="sc">%&gt;%</span> </span>
<span id="cb1016-3"><a href="métodos-não-paramétricos.html#cb1016-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb1016-4"><a href="métodos-não-paramétricos.html#cb1016-4" tabindex="-1"></a>                   <span class="at">mediana =</span> <span class="fu">median</span> (medidas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1016-5"><a href="métodos-não-paramétricos.html#cb1016-5" tabindex="-1"></a>                   <span class="at">p25=</span><span class="fu">quantile</span>(medidas, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1016-6"><a href="métodos-não-paramétricos.html#cb1016-6" tabindex="-1"></a>                   <span class="at">p75=</span><span class="fu">quantile</span>(medidas, <span class="at">probs =</span> <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1016-7"><a href="métodos-não-paramétricos.html#cb1016-7" tabindex="-1"></a>                   <span class="at">media =</span> <span class="fu">mean</span> (medidas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1016-8"><a href="métodos-não-paramétricos.html#cb1016-8" tabindex="-1"></a>                   <span class="at">dp =</span> <span class="fu">sd</span> (medidas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1016-9"><a href="métodos-não-paramétricos.html#cb1016-9" tabindex="-1"></a>                   <span class="at">ep =</span> dp<span class="sc">/</span><span class="fu">sqrt</span>(n),</span>
<span id="cb1016-10"><a href="métodos-não-paramétricos.html#cb1016-10" tabindex="-1"></a>                   <span class="at">me =</span> ep <span class="sc">*</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>), n <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb1016-11"><a href="métodos-não-paramétricos.html#cb1016-11" tabindex="-1"></a>resumo</span></code></pre></div>
<pre><code>## # A tibble: 2 × 9
##   momento     n mediana   p25   p75 media    dp    ep    me
##   &lt;chr&gt;   &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 basal      10     170  125    200   172  50.9  16.1  36.4
## 2 final      10     240  222.   300   254  50.4  15.9  36.0</code></pre>
</div>
<div id="visualização-dos-dados-4" class="section level4 hasAnchor" number="17.5.1.3">
<h4><span class="header-section-number">17.5.1.3</span> Visualização dos dados<a href="#visualiza%C3%A7%C3%A3o-dos-dados-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Pode-se fazer visualização gráfica dos dados usando um boxplot (Figura <a href="métodos-não-paramétricos.html#fig:aero">17.3</a> ou um gráfico de linha (Figura <a href="métodos-não-paramétricos.html#fig:aero1">17.4</a>).</p>
<p><u>Boxplot</u></p>
<div class="sourceCode" id="cb1018"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1018-1"><a href="métodos-não-paramétricos.html#cb1018-1" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span>(dadosL,</span>
<span id="cb1018-2"><a href="métodos-não-paramétricos.html#cb1018-2" tabindex="-1"></a>                  <span class="at">x =</span> <span class="st">&quot;momento&quot;</span>,</span>
<span id="cb1018-3"><a href="métodos-não-paramétricos.html#cb1018-3" tabindex="-1"></a>                  <span class="at">y =</span> <span class="st">&quot;medidas&quot;</span>,</span>
<span id="cb1018-4"><a href="métodos-não-paramétricos.html#cb1018-4" tabindex="-1"></a>                  <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1018-5"><a href="métodos-não-paramétricos.html#cb1018-5" tabindex="-1"></a>                  <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>,</span>
<span id="cb1018-6"><a href="métodos-não-paramétricos.html#cb1018-6" tabindex="-1"></a>                  <span class="at">fill =</span> <span class="st">&quot;momento&quot;</span>,</span>
<span id="cb1018-7"><a href="métodos-não-paramétricos.html#cb1018-7" tabindex="-1"></a>                  <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">&quot;cyan4&quot;</span>, <span class="st">&quot;cyan3&quot;</span>),</span>
<span id="cb1018-8"><a href="métodos-não-paramétricos.html#cb1018-8" tabindex="-1"></a>                  <span class="at">legend =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb1018-9"><a href="métodos-não-paramétricos.html#cb1018-9" tabindex="-1"></a>                  <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb1018-10"><a href="métodos-não-paramétricos.html#cb1018-10" tabindex="-1"></a>                  <span class="at">xlab =</span> <span class="st">&quot;Momento&quot;</span> ,</span>
<span id="cb1018-11"><a href="métodos-não-paramétricos.html#cb1018-11" tabindex="-1"></a>                  <span class="at">ylab =</span> <span class="st">&quot;PEF (L/min) &quot;</span>)<span class="sc">+</span></span>
<span id="cb1018-12"><a href="métodos-não-paramétricos.html#cb1018-12" tabindex="-1"></a>  <span class="fu">theme</span> (<span class="at">text =</span> <span class="fu">element_text</span> (<span class="at">size =</span> <span class="dv">13</span>),</span>
<span id="cb1018-13"><a href="métodos-não-paramétricos.html#cb1018-13" tabindex="-1"></a>         <span class="at">axis.text.x=</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:aero"></span>
<img src="bookdownproj_files/figure-html/aero-1.png" alt="Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos." width="70%" height="70%" />
<p class="caption">
Figura 17.3: Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos.
</p>
</div>
<p><u>Gráfico de linha</u></p>
<div class="sourceCode" id="cb1019"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1019-1"><a href="métodos-não-paramétricos.html#cb1019-1" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggline</span>(dadosL,</span>
<span id="cb1019-2"><a href="métodos-não-paramétricos.html#cb1019-2" tabindex="-1"></a>               <span class="at">x =</span> <span class="st">&quot;momento&quot;</span>,</span>
<span id="cb1019-3"><a href="métodos-não-paramétricos.html#cb1019-3" tabindex="-1"></a>               <span class="at">y =</span> <span class="st">&quot;medidas&quot;</span>,</span>
<span id="cb1019-4"><a href="métodos-não-paramétricos.html#cb1019-4" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;cyan4&quot;</span>,</span>
<span id="cb1019-5"><a href="métodos-não-paramétricos.html#cb1019-5" tabindex="-1"></a>               <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>,</span>
<span id="cb1019-6"><a href="métodos-não-paramétricos.html#cb1019-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="fl">0.7</span>,</span>
<span id="cb1019-7"><a href="métodos-não-paramétricos.html#cb1019-7" tabindex="-1"></a>               <span class="at">add =</span> <span class="st">&quot;mean_ci&quot;</span>,</span>
<span id="cb1019-8"><a href="métodos-não-paramétricos.html#cb1019-8" tabindex="-1"></a>               <span class="at">point.size =</span> <span class="dv">2</span>,</span>
<span id="cb1019-9"><a href="métodos-não-paramétricos.html#cb1019-9" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">&quot;Momento&quot;</span> ,</span>
<span id="cb1019-10"><a href="métodos-não-paramétricos.html#cb1019-10" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="st">&quot;PEF (L/min) &quot;</span>,</span>
<span id="cb1019-11"><a href="métodos-não-paramétricos.html#cb1019-11" tabindex="-1"></a>               <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()) <span class="sc">+</span></span>
<span id="cb1019-12"><a href="métodos-não-paramétricos.html#cb1019-12" tabindex="-1"></a>  <span class="fu">theme</span> (<span class="at">text =</span> <span class="fu">element_text</span> (<span class="at">size =</span> <span class="dv">13</span>),</span>
<span id="cb1019-13"><a href="métodos-não-paramétricos.html#cb1019-13" tabindex="-1"></a>         <span class="at">axis.text.x=</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:aero1"></span>
<img src="bookdownproj_files/figure-html/aero1-1.png" alt="Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos." width="70%" height="70%" />
<p class="caption">
Figura 17.4: Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos.
</p>
</div>
</div>
<div id="criação-de-uma-variável-que-represente-a-diferença-entre-os-momentos" class="section level4 hasAnchor" number="17.5.1.4">
<h4><span class="header-section-number">17.5.1.4</span> Criação de uma variável que represente a diferença entre os momentos<a href="#cria%C3%A7%C3%A3o-de-uma-vari%C3%A1vel-que-represente-a-diferen%C3%A7a-entre-os-momentos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A diferença entre as média basal e final será atribuída ao nome <code>D</code>. Esta ação será realizada, utilizando o banco de dados amplo (<code>dados</code>):</p>
<div class="sourceCode" id="cb1020"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1020-1"><a href="métodos-não-paramétricos.html#cb1020-1" tabindex="-1"></a>dados<span class="sc">$</span>D <span class="ot">&lt;-</span> dados<span class="sc">$</span>basal <span class="sc">-</span> dados<span class="sc">$</span>final</span>
<span id="cb1020-2"><a href="métodos-não-paramétricos.html#cb1020-2" tabindex="-1"></a><span class="fu">head</span> (dados)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##      id basal final     D
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1   120   220  -100
## 2     2   200   300  -100
## 3     3   140   230   -90
## 4     4   200   180    20
## 5     5   110   300  -190
## 6     6   240   330   -90</code></pre>
<p><strong>Resumo da variável D</strong></p>
<p>Ao resumo será atribuído ao nome <code>resumo2</code>:</p>
<div class="sourceCode" id="cb1022"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1022-1"><a href="métodos-não-paramétricos.html#cb1022-1" tabindex="-1"></a>resumo2 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb1022-2"><a href="métodos-não-paramétricos.html#cb1022-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span> (),</span>
<span id="cb1022-3"><a href="métodos-não-paramétricos.html#cb1022-3" tabindex="-1"></a>                   <span class="at">mediana =</span> <span class="fu">median</span> (D, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1022-4"><a href="métodos-não-paramétricos.html#cb1022-4" tabindex="-1"></a>                   <span class="at">p25=</span><span class="fu">quantile</span>(D, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1022-5"><a href="métodos-não-paramétricos.html#cb1022-5" tabindex="-1"></a>                   <span class="at">p75=</span><span class="fu">quantile</span>(D, <span class="at">probs =</span> <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1022-6"><a href="métodos-não-paramétricos.html#cb1022-6" tabindex="-1"></a>resumo2</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##       n mediana   p25   p75
##   &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1    10     -90  -100 -57.5</code></pre>
<p>O sinal negativo demonstra que houve um aumento do PFM do momento basal para o final.</p>
</div>
</div>
<div id="definição-das-hipóteses-estatísticas-3" class="section level3 hasAnchor" number="17.5.2">
<h3><span class="header-section-number">17.5.2</span> Definição das hipóteses estatísticas<a href="#defini%C3%A7%C3%A3o-das-hip%C3%B3teses-estat%C3%ADsticas-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Da mesma maneira que o teste <em>t</em> pareado, as hipóteses estabelecidas comparam dois grupos dependentes.
O teste de Wilcoxon é usado para avaliar a hipótese nula de que a distribuição das diferenças entre os grupos tem uma diferença mediana igual a 0.</p>
<blockquote>
<p><font size=2> <strong><span class="math inline">\(H_{0}\)</span></strong>: <span class="math inline">\(D_{i} = 0\)</span> .<br />
<strong><span class="math inline">\(H_{A}\)</span></strong>: <span class="math inline">\(D_{i} \ne 0\)</span>. </font></p>
</blockquote>
<p>Note que a <span class="math inline">\(H_{A}\)</span> estabelece que a diferença pode aumentar ou diminuir. Logo, o teste é bicaudal.</p>
</div>
<div id="execução-do-teste-estatístico-2" class="section level3 hasAnchor" number="17.5.3">
<h3><span class="header-section-number">17.5.3</span> Execução do teste estatístico<a href="#execu%C3%A7%C3%A3o-do-teste-estat%C3%ADstico-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="lógica-do-teste-de-wilcoxon" class="section level4 hasAnchor" number="17.5.3.1">
<h4><span class="header-section-number">17.5.3.1</span> Lógica do teste de Wilcoxon<a href="#l%C3%B3gica-do-teste-de-wilcoxon" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>A ideia do teste é verificar se as diferenças positivas são maiores ou menores, em grandeza absoluta, que as diferenças negativas. Para isso, foi criada, anteriormente, a variável <code>D</code>. Agora, será criada outra variável, iguala a variável <code>D</code>, apenas ignorando o sinal, denominada <code>D_abs</code>, diferença absoluta entre as variáveis <code>final</code> e <code>basal</code>.</li>
</ol>
<div class="sourceCode" id="cb1024"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1024-1"><a href="métodos-não-paramétricos.html#cb1024-1" tabindex="-1"></a>dados<span class="sc">$</span>D_abs <span class="ot">&lt;-</span> <span class="fu">abs</span>(dados<span class="sc">$</span>basal <span class="sc">-</span> dados<span class="sc">$</span>final)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Excluir os casos com diferença igual a 0 (zero). Para isso, uma maneira possível é extrair um subconjunto de dados do conjunto principal (<code>dados</code>), criando um conjunto de dados com a função <code>filter()</code> do pacote <code>dplyr</code>, que receberá o nome de <code>dados1</code>. O argumento <code>D_absbs != 0</code> significa todas as diferenças absolutas diferentes de 0:</li>
</ol>
<div class="sourceCode" id="cb1025"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1025-1"><a href="métodos-não-paramétricos.html#cb1025-1" tabindex="-1"></a>dados1 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(D_abs <span class="sc">!=</span> <span class="dv">0</span>)</span></code></pre></div>
<p>Observe que como não há diferenças zeradas. Ou seja, o novo conjunto de dados continua o mesmo. O que pode ser confirmado, executando a função <code>str()</code>:</p>
<div class="sourceCode" id="cb1026"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1026-1"><a href="métodos-não-paramétricos.html#cb1026-1" tabindex="-1"></a><span class="fu">str</span> (dados1)</span></code></pre></div>
<pre><code>## tibble [10 × 5] (S3: tbl_df/tbl/data.frame)
##  $ id   : int [1:10] 1 2 3 4 5 6 7 8 9 10
##  $ basal: num [1:10] 120 200 140 200 110 240 150 120 250 190
##  $ final: num [1:10] 220 300 230 180 300 330 230 250 300 200
##  $ D    : num [1:10] -100 -100 -90 20 -190 -90 -80 -130 -50 -10
##  $ D_abs: num [1:10] 100 100 90 20 190 90 80 130 50 10</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Ordenar de forma crescente todos os valores da variável <code>D_abs</code> do banco de dados <code>dados1</code>, usando a função <code>arrange()</code> do pacote <code>dplyr</code>:</li>
</ol>
<div class="sourceCode" id="cb1028"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1028-1"><a href="métodos-não-paramétricos.html#cb1028-1" tabindex="-1"></a>dados1 <span class="ot">&lt;-</span> dados1 <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">arrange</span>(dados1<span class="sc">$</span>D_abs)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Estabelecer postos para os valores ordenados da variável <code>D_abs</code>, do conjunto de dados <code>dados1</code>, fazendo a média das ordens quando houver empate. A execução deste comando cria uma nova variável, chamada <code>postos</code>:</li>
</ol>
<div class="sourceCode" id="cb1029"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1029-1"><a href="métodos-não-paramétricos.html#cb1029-1" tabindex="-1"></a>dados1<span class="sc">$</span>postos <span class="ot">&lt;-</span> <span class="fu">rank</span>(dados1<span class="sc">$</span>D_abs)</span></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Estabelecer sinais para os postos, criando dois subconjuntos de dados do conjuntos dados1, um com os escolares com postos positivos (<code>pos</code>) e outros com postos negativos(<code>neg</code>):</li>
</ol>
<div class="sourceCode" id="cb1030"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1030-1"><a href="métodos-não-paramétricos.html#cb1030-1" tabindex="-1"></a>neg <span class="ot">&lt;-</span> dados1 <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(D <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb1030-2"><a href="métodos-não-paramétricos.html#cb1030-2" tabindex="-1"></a>pos <span class="ot">&lt;-</span> dados1 <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(D <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div>
<ol start="6" style="list-style-type: decimal">
<li>Somar todos os postos (variável <code>posto</code>) em cada um dos subconjuntos criados (<code>neg</code> e <code>pos</code>):</li>
</ol>
<div class="sourceCode" id="cb1031"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1031-1"><a href="métodos-não-paramétricos.html#cb1031-1" tabindex="-1"></a>soma_neg <span class="ot">&lt;-</span> <span class="fu">sum</span>(neg<span class="sc">$</span>postos)</span>
<span id="cb1031-2"><a href="métodos-não-paramétricos.html#cb1031-2" tabindex="-1"></a>soma_pos <span class="ot">&lt;-</span> <span class="fu">sum</span>(pos<span class="sc">$</span>postos)</span>
<span id="cb1031-3"><a href="métodos-não-paramétricos.html#cb1031-3" tabindex="-1"></a><span class="fu">print</span> (<span class="fu">c</span>(soma_neg, soma_pos))</span></code></pre></div>
<pre><code>## [1] 53  2</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Atribuir a menor soma à estatística do teste, denotada <em>T</em>:</li>
</ol>
<div class="sourceCode" id="cb1033"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1033-1"><a href="métodos-não-paramétricos.html#cb1033-1" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">min</span> (soma_neg <span class="sc">:</span> soma_pos)</span>
<span id="cb1033-2"><a href="métodos-não-paramétricos.html#cb1033-2" tabindex="-1"></a>T</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Para dados com tamanhos grandes (&gt; 20 pares), a significância de <em>T</em> pode ser determinada <span class="citation">(148)</span>, considerando que a distribuição de <em>T</em> tem aproximadamente distribuição normal com média igual a</li>
</ol>
<p><span class="math display">\[
\mu_{T} =\frac{n \times \left (n + 1  \right )}{4}
\]</span></p>
<p>onde <em>n</em> é o tamanho da amostra.</p>
<div class="sourceCode" id="cb1035"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1035-1"><a href="métodos-não-paramétricos.html#cb1035-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados<span class="sc">$</span>D)</span>
<span id="cb1035-2"><a href="métodos-não-paramétricos.html#cb1035-2" tabindex="-1"></a>mu_T <span class="ot">&lt;-</span> (n <span class="sc">*</span> (n <span class="sc">+</span> <span class="dv">1</span>))<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb1035-3"><a href="métodos-não-paramétricos.html#cb1035-3" tabindex="-1"></a>mu_T</span></code></pre></div>
<pre><code>## [1] 27.5</code></pre>
<p>E desvio padrão igual a:</p>
<p><span class="math display">\[
\sigma_{T}= \sqrt {\frac{n\left (n + 1  \right )\times \left (2n + 1  \right )}{24}}
\]</span></p>
<div class="sourceCode" id="cb1037"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1037-1"><a href="métodos-não-paramétricos.html#cb1037-1" tabindex="-1"></a>dp_T <span class="ot">&lt;-</span> <span class="fu">sqrt</span> ((n<span class="sc">*</span>(n <span class="sc">+</span> <span class="dv">1</span>)) <span class="sc">*</span> (<span class="dv">2</span> <span class="sc">*</span> n <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span><span class="dv">24</span>) </span>
<span id="cb1037-2"><a href="métodos-não-paramétricos.html#cb1037-2" tabindex="-1"></a>dp_T</span></code></pre></div>
<pre><code>## [1] 9.810708</code></pre>
<p>Os resultados da execução das equações fornecem os dados para calcular a estatística Z_T com correção de continuidade e, a partir dela, calcular o valor <em>P</em>.</p>
<p><span class="math display">\[
Z_{T}= \frac{\left |T - \mu_{T}  \right | - 0,5}{\sigma_{T}}
\]</span></p>
<div class="sourceCode" id="cb1039"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1039-1"><a href="métodos-não-paramétricos.html#cb1039-1" tabindex="-1"></a>Z_T <span class="ot">&lt;-</span> (<span class="fu">abs</span>(T <span class="sc">-</span> mu_T)<span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">/</span>dp_T</span>
<span id="cb1039-2"><a href="métodos-não-paramétricos.html#cb1039-2" tabindex="-1"></a>Z_T</span></code></pre></div>
<pre><code>## [1] 2.548236</code></pre>
<ol start="9" style="list-style-type: decimal">
<li><p>Concluindo, o valor da estatística de teste <em>T</em> é superior ao <span class="math inline">\(Z_{crítico} = 1,96\)</span>, para um <span class="math inline">\(\alpha = 0,05\)</span>. Dessa forma, a <span class="math inline">\(H_{0}\)</span> é rejeitada. Existe uma diferença significativa entre o PFE basal e o PFE final, neste grupo de escolares asmáticos.</p></li>
<li><p>O valor <em>P</em> pode ser obtido com a função <code>pnorm()</code> e multiplicando o resultado por 2, pois o teste é bilateral.</p></li>
</ol>
<div class="sourceCode" id="cb1041"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1041-1"><a href="métodos-não-paramétricos.html#cb1041-1" tabindex="-1"></a>P <span class="ot">&lt;-</span> <span class="fu">pnorm</span> (Z_T, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb1041-2"><a href="métodos-não-paramétricos.html#cb1041-2" tabindex="-1"></a>P</span></code></pre></div>
<pre><code>## [1] 0.01082692</code></pre>
<p>Como já dito anteriormente, na prática, não há necessidade de fazer todos esses cálculos, pois o R calcula facilmente o teste. Eles são apenas uma demonstração de como o teste funciona.</p>
</div>
<div id="cálculo-do-teste-de-wilcoxon-no-r" class="section level4 hasAnchor" number="17.5.3.2">
<h4><span class="header-section-number">17.5.3.2</span> Cálculo do teste de Wilcoxon no R<a href="#c%C3%A1lculo-do-teste-de-wilcoxon-no-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Usando o conjunto de dados no formato longo (<code>dadosL</code>), calcula-se o teste com a função <code>wilcox_test()</code> do pacote <code>rstatix</code>. É a mesma função utilizada para o teste de U de Mann-Whitney, mudando apenas o argumento <code>paired=FALSE</code> para <code>paired=TRUE</code>:</p>
<div class="sourceCode" id="cb1043"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1043-1"><a href="métodos-não-paramétricos.html#cb1043-1" tabindex="-1"></a>teste1 <span class="ot">&lt;-</span> dadosL <span class="sc">%&gt;%</span> </span>
<span id="cb1043-2"><a href="métodos-não-paramétricos.html#cb1043-2" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">wilcox_test</span>(medidas <span class="sc">~</span> momento, <span class="at">paired =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1043-3"><a href="métodos-não-paramétricos.html#cb1043-3" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">add_significance</span>()</span>
<span id="cb1043-4"><a href="métodos-não-paramétricos.html#cb1043-4" tabindex="-1"></a>teste1</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   .y.     group1 group2    n1    n2 statistic      p p.signif
##   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;   
## 1 medidas basal  final     10    10         2 0.0107 *</code></pre>
<p>Observe que o resultado é o mesmo calculado manualmente.</p>
</div>
</div>
<div id="tamanho-do-efeito-3" class="section level3 hasAnchor" number="17.5.4">
<h3><span class="header-section-number">17.5.4</span> Tamanho do efeito<a href="métodos-não-paramétricos.html#tamanho-do-efeito-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O tamanho do efeito pode ser calculado da mesma forma que para o teste de Mann-Whitney (Seção <a href="métodos-não-paramétricos.html#sec-tefMW">17.4.5</a>), usando a mesma equação e os dados obtidos acima, onde 2.548236 e <em>n</em> = 10 tem-se</p>
<p><span class="math display">\[
r = \frac {Z_{T}}{\sqrt{n}}
\]</span></p>
<p>Pode-se usar também a função <code>wilcox_effsize()</code> para calcular a estatística <em>r</em>. A Saída exibe junto a magnitude o efeito, que no caso é grande (&gt; 0,5 como mostra a Tabela <a href="métodos-não-paramétricos.html#tab:wilcoxef">17.3</a> do teste de Mann-Whitney).</p>
<div class="sourceCode" id="cb1045"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1045-1"><a href="métodos-não-paramétricos.html#cb1045-1" tabindex="-1"></a>dadosL <span class="sc">%&gt;%</span> </span>
<span id="cb1045-2"><a href="métodos-não-paramétricos.html#cb1045-2" tabindex="-1"></a>  <span class="fu">wilcox_effsize</span>(medidas <span class="sc">~</span> momento, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.     group1 group2 effsize    n1    n2 magnitude
## * &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;ord&gt;    
## 1 medidas basal  final    0.823    10    10 large</code></pre>
</div>
<div id="conclusão-8" class="section level3 hasAnchor" number="17.5.5">
<h3><span class="header-section-number">17.5.5</span> Conclusão<a href="#conclus%C3%A3o-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Assumindo um <span class="math inline">\(\alpha = 0,05\)</span>, se o valor <em>P</em>, obtido pelo teste, for menor do que 0,05, rejeita-se a hipótese nula (V = 2, <em>P</em> = 0,01, <em>n</em> = 10).</p>
<p>Pode-se concluir que existe diferença nas medidas do pico de fluxo expiratório máximo no início e no fim do programa de exercícios aeróbicos realizados pelos escolares asmáticos e a magnitude do efeito foi grande (<em>r</em> = 0,82).</p>
<p>Isto pode ser visualizado na Figura <a href="métodos-não-paramétricos.html#fig:aero2">17.5</a>:</p>
<div class="sourceCode" id="cb1047"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1047-1"><a href="métodos-não-paramétricos.html#cb1047-1" tabindex="-1"></a>bxp <span class="ot">&lt;-</span> ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span>(dadosL,</span>
<span id="cb1047-2"><a href="métodos-não-paramétricos.html#cb1047-2" tabindex="-1"></a>                         <span class="at">x =</span> <span class="st">&quot;momento&quot;</span>,</span>
<span id="cb1047-3"><a href="métodos-não-paramétricos.html#cb1047-3" tabindex="-1"></a>                         <span class="at">y =</span> <span class="st">&quot;medidas&quot;</span>,</span>
<span id="cb1047-4"><a href="métodos-não-paramétricos.html#cb1047-4" tabindex="-1"></a>                         <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1047-5"><a href="métodos-não-paramétricos.html#cb1047-5" tabindex="-1"></a>                         <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>,</span>
<span id="cb1047-6"><a href="métodos-não-paramétricos.html#cb1047-6" tabindex="-1"></a>                         <span class="at">fill =</span> <span class="st">&quot;momento&quot;</span>,</span>
<span id="cb1047-7"><a href="métodos-não-paramétricos.html#cb1047-7" tabindex="-1"></a>                         <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">&quot;cyan4&quot;</span>, <span class="st">&quot;cyan3&quot;</span>),</span>
<span id="cb1047-8"><a href="métodos-não-paramétricos.html#cb1047-8" tabindex="-1"></a>                         <span class="at">legend =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb1047-9"><a href="métodos-não-paramétricos.html#cb1047-9" tabindex="-1"></a>                         <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb1047-10"><a href="métodos-não-paramétricos.html#cb1047-10" tabindex="-1"></a>                         <span class="at">xlab =</span> <span class="st">&quot;Momento&quot;</span> ,</span>
<span id="cb1047-11"><a href="métodos-não-paramétricos.html#cb1047-11" tabindex="-1"></a>                         <span class="at">ylab =</span> <span class="st">&quot;PEF (L/min) &quot;</span>) <span class="sc">+</span></span>
<span id="cb1047-12"><a href="métodos-não-paramétricos.html#cb1047-12" tabindex="-1"></a>  <span class="fu">theme</span> (<span class="at">text =</span> <span class="fu">element_text</span> (<span class="at">size =</span> <span class="dv">13</span>),</span>
<span id="cb1047-13"><a href="métodos-não-paramétricos.html#cb1047-13" tabindex="-1"></a>         <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb1047-14"><a href="métodos-não-paramétricos.html#cb1047-14" tabindex="-1"></a></span>
<span id="cb1047-15"><a href="métodos-não-paramétricos.html#cb1047-15" tabindex="-1"></a>teste <span class="ot">&lt;-</span> dadosL <span class="sc">%&gt;%</span> </span>
<span id="cb1047-16"><a href="métodos-não-paramétricos.html#cb1047-16" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">wilcox_test</span> (medidas <span class="sc">~</span> momento, <span class="at">paired =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1047-17"><a href="métodos-não-paramétricos.html#cb1047-17" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">add_significance</span> ()</span>
<span id="cb1047-18"><a href="métodos-não-paramétricos.html#cb1047-18" tabindex="-1"></a>teste <span class="ot">&lt;-</span> teste <span class="sc">%&gt;%</span> rstatix<span class="sc">::</span><span class="fu">add_xy_position</span> ()</span>
<span id="cb1047-19"><a href="métodos-não-paramétricos.html#cb1047-19" tabindex="-1"></a></span>
<span id="cb1047-20"><a href="métodos-não-paramétricos.html#cb1047-20" tabindex="-1"></a>bxp <span class="sc">+</span> </span>
<span id="cb1047-21"><a href="métodos-não-paramétricos.html#cb1047-21" tabindex="-1"></a>  <span class="fu">stat_pvalue_manual</span> (teste, </span>
<span id="cb1047-22"><a href="métodos-não-paramétricos.html#cb1047-22" tabindex="-1"></a>                      <span class="at">tip.length =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb1047-23"><a href="métodos-não-paramétricos.html#cb1047-23" tabindex="-1"></a>  <span class="fu">labs</span> (<span class="at">subtitle =</span> <span class="fu">get_test_label</span> (<span class="at">stat.test =</span> teste, </span>
<span id="cb1047-24"><a href="métodos-não-paramétricos.html#cb1047-24" tabindex="-1"></a>                                   <span class="at">detailed =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:aero2"></span>
<img src="bookdownproj_files/figure-html/aero2-1.png" alt="Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos." width="70%" height="70%" />
<p class="caption">
Figura 17.5: Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos.
</p>
</div>
</div>
</div>
<div id="sec-kuskalwallis" class="section level2 hasAnchor" number="17.6">
<h2><span class="header-section-number">17.6</span> Teste de Kruskal-Wallis<a href="métodos-não-paramétricos.html#sec-kuskalwallis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Quando os pressupostos subjacentes a ANOVA não são atendidos, é possível usar o teste não paramétrico de Kruskal-Wallis (KW) para testar a hipótese de que os parâmetros de localização são iguais. Pode ser considerado uma extensão do teste de Wilcoxon-Mann-Whitney.</p>
<p>Enquanto a ANOVA depende da hipótese de que todas as populações são independentes e normalmente distribuídas, o teste de Kruskal-Wallis exige apenas amostras aleatórias independentes provenientes de suas respectivas populações. Entretanto, este teste somente deve ser aplicado se a amostra for pequena e/ou os pressupostos para a ANOVA forem seriamente violados.</p>
<p>O teste não usa diretamente medições de quantidade conhecida, utiliza, como outros testes não paramétricos, os postos dos valores analisados. Em função disso, é também conhecido como <em>análise de variância de um fator em postos</em>.</p>
<div id="dados-usados-nesta-seção-13" class="section level3 hasAnchor" number="17.6.1">
<h3><span class="header-section-number">17.6.1</span> Dados usados nesta seção<a href="#dados-usados-nesta-se%C3%A7%C3%A3o-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Um experimento foi realizado para verificar se o álcool ou o café afetam os tempos de reação ao dirigir <span class="citation">(149)</span>. O estudo tem três grupos diferentes de participantes: 10 bebendo água (controle), 10 bebendo cerveja contendo duas unidades de álcool e 10 bebendo café. O tempo de reação em uma simulação de direção foi medido para cada participante.</p>
<p>Os dados encontram-se no arquivo <code>dadosResposta.xlsx</code>. Clique <a href="https://github.com/petronioliveira/Arquivos/blob/main/dadosResposta.xlsx"><strong>aqui</strong></a> para baixar e, após, salve o mesmo no seu diretório de trabalho.</p>
<p>As variáveis são:</p>
<ul>
<li><em>id</em> <span class="math inline">\(\to\)</span> identificação do participante;</li>
<li><em>tempo</em> <span class="math inline">\(\to\)</span> tempo de reação na simulação de direção em segundos;</li>
<li><em>bebida</em> <span class="math inline">\(\to\)</span> três grupo: água, álcool e café.</li>
</ul>
<p>O estudo pretende verificar se existe diferença no tempo de reação dos participantes em um teste de direção com a ingesta de água, café e álcool.</p>
<div id="leitura-e-exploração-dos-dados-1" class="section level4 hasAnchor" number="17.6.1.1">
<h4><span class="header-section-number">17.6.1.1</span> Leitura e exploração dos dados<a href="#leitura-e-explora%C3%A7%C3%A3o-dos-dados-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Como o dados estão contidos em um arquivo Excel (<em>.xlsx</em>), serão lidos com a função <code>read_excel()</code> do pacote <code>readxl</code> e a sua estrutura será observada com função <code>str()</code>:</p>
<div class="sourceCode" id="cb1048"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1048-1"><a href="métodos-não-paramétricos.html#cb1048-1" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span> (<span class="st">&quot;Arquivos/dadosResposta.xlsx&quot;</span>)</span>
<span id="cb1048-2"><a href="métodos-não-paramétricos.html#cb1048-2" tabindex="-1"></a><span class="fu">str</span>(dados)</span></code></pre></div>
<pre><code>## tibble [30 × 3] (S3: tbl_df/tbl/data.frame)
##  $ id    : num [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ tempo : num [1:30] 0.37 0.38 0.61 0.78 0.83 0.86 0.9 0.95 1.63 1.97 ...
##  $ bebida: chr [1:30] &quot;agua&quot; &quot;agua&quot; &quot;agua&quot; &quot;agua&quot; ...</code></pre>
<p>O formato do arquivo é o longo. A variável bebida encontra-se como caracter e deve ser transformada em fator e as categorias na sequência: <code>agua</code>, <code>cafe</code> e <code>alcool</code>.</p>
<div class="sourceCode" id="cb1050"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1050-1"><a href="métodos-não-paramétricos.html#cb1050-1" tabindex="-1"></a>dados<span class="sc">$</span>bebida <span class="ot">&lt;-</span> <span class="fu">factor</span>(dados<span class="sc">$</span>bebida, </span>
<span id="cb1050-2"><a href="métodos-não-paramétricos.html#cb1050-2" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;agua&quot;</span>, <span class="st">&quot;cafe&quot;</span>, <span class="st">&quot;alcool&quot;</span>))</span></code></pre></div>
<p>Os dados serão observados visualmente através de boxplots (Figura <a href="métodos-não-paramétricos.html#fig:bebida">17.6</a>), usando a função <code>ggplot()</code> do pacote <code>ggplot2</code>, com cores do <code>nejm</code> (<em>New England Journal of Medicine</em>) o pacote <code>ggsci</code>.</p>
<div class="sourceCode" id="cb1051"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1051-1"><a href="métodos-não-paramétricos.html#cb1051-1" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span>(dados,</span>
<span id="cb1051-2"><a href="métodos-não-paramétricos.html#cb1051-2" tabindex="-1"></a>                   <span class="at">x =</span> <span class="st">&quot;bebida&quot;</span>,</span>
<span id="cb1051-3"><a href="métodos-não-paramétricos.html#cb1051-3" tabindex="-1"></a>                   <span class="at">y =</span> <span class="st">&quot;tempo&quot;</span>,</span>
<span id="cb1051-4"><a href="métodos-não-paramétricos.html#cb1051-4" tabindex="-1"></a>                   <span class="at">bxp.errorbar =</span> T,</span>
<span id="cb1051-5"><a href="métodos-não-paramétricos.html#cb1051-5" tabindex="-1"></a>                   <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>,</span>
<span id="cb1051-6"><a href="métodos-não-paramétricos.html#cb1051-6" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">&quot;bebida&quot;</span>,</span>
<span id="cb1051-7"><a href="métodos-não-paramétricos.html#cb1051-7" tabindex="-1"></a>                   <span class="at">palette =</span> <span class="st">&quot;nejm&quot;</span>,</span>
<span id="cb1051-8"><a href="métodos-não-paramétricos.html#cb1051-8" tabindex="-1"></a>                   <span class="at">legend =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb1051-9"><a href="métodos-não-paramétricos.html#cb1051-9" tabindex="-1"></a>                   <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb1051-10"><a href="métodos-não-paramétricos.html#cb1051-10" tabindex="-1"></a>                   <span class="at">xlab =</span> <span class="st">&quot;Tipo de bebida&quot;</span> ,</span>
<span id="cb1051-11"><a href="métodos-não-paramétricos.html#cb1051-11" tabindex="-1"></a>                   <span class="at">ylab =</span> <span class="st">&quot;Tempo de reação (seg)&quot;</span>) <span class="sc">+</span></span>
<span id="cb1051-12"><a href="métodos-não-paramétricos.html#cb1051-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bebida"></span>
<img src="bookdownproj_files/figure-html/bebida-1.png" alt="Impacto do tipo de bebida no tempo de reação ao dirigir." width="70%" height="70%" />
<p class="caption">
Figura 17.6: Impacto do tipo de bebida no tempo de reação ao dirigir.
</p>
</div>
<p>Os boxplots exibem dados com medianas visualmente diferentes, bigodes diferentes e grupos com presença de <em>outliers</em>. Para verificar o impacto desses achados, pode-se usar a função <code>identify_outliers()</code>, do pacote <code>rstatix</code> que confirma na sua Saída a presença de <em>outliers</em> no grupo agua e cafe, sendo dois extremos.</p>
<div class="sourceCode" id="cb1052"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1052-1"><a href="métodos-não-paramétricos.html#cb1052-1" tabindex="-1"></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb1052-2"><a href="métodos-não-paramétricos.html#cb1052-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(bebida) <span class="sc">%&gt;%</span> </span>
<span id="cb1052-3"><a href="métodos-não-paramétricos.html#cb1052-3" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">identify_outliers</span>(tempo)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   bebida    id tempo is.outlier is.extreme
##   &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
## 1 agua       9  1.63 TRUE       FALSE     
## 2 agua      10  1.97 TRUE       TRUE      
## 3 cafe      19  2.56 TRUE       FALSE     
## 4 cafe      20  3.07 TRUE       TRUE</code></pre>
<p>Para avaliar a normalidade será usado o teste de Shapiro-Wilk, com a função <code>shapiro_test()</code> e a função <code>group_by()</code> do pacote <code>dplyr</code>:</p>
<div class="sourceCode" id="cb1054"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1054-1"><a href="métodos-não-paramétricos.html#cb1054-1" tabindex="-1"></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb1054-2"><a href="métodos-não-paramétricos.html#cb1054-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span> (bebida) <span class="sc">%&gt;%</span> </span>
<span id="cb1054-3"><a href="métodos-não-paramétricos.html#cb1054-3" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">shapiro_test</span> (tempo) </span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   bebida variable statistic      p
##   &lt;fct&gt;  &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;
## 1 agua   tempo        0.863 0.0837
## 2 cafe   tempo        0.815 0.0220
## 3 alcool tempo        0.875 0.114</code></pre>
<p>A variável <code>cafe</code> tem uma distribuição que não se ajusta a distribuição normal.</p>
<p>Para completar a exploração dos dados, será solicitado, usando as funções <code>group_by ()</code> e <code>summarise</code>, do pacote <code>dplyr</code>, medidas de localização e dispersão adquadas para variáveis bem assimétricas.</p>
<div class="sourceCode" id="cb1056"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1056-1"><a href="métodos-não-paramétricos.html#cb1056-1" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb1056-2"><a href="métodos-não-paramétricos.html#cb1056-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(bebida) <span class="sc">%&gt;%</span> </span>
<span id="cb1056-3"><a href="métodos-não-paramétricos.html#cb1056-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb1056-4"><a href="métodos-não-paramétricos.html#cb1056-4" tabindex="-1"></a>                   <span class="at">mediana =</span> <span class="fu">median</span> (tempo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1056-5"><a href="métodos-não-paramétricos.html#cb1056-5" tabindex="-1"></a>                   <span class="at">p25=</span><span class="fu">quantile</span>(tempo, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1056-6"><a href="métodos-não-paramétricos.html#cb1056-6" tabindex="-1"></a>                   <span class="at">p75=</span><span class="fu">quantile</span>(tempo, <span class="at">probs =</span> <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1056-7"><a href="métodos-não-paramétricos.html#cb1056-7" tabindex="-1"></a>resumo</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   bebida     n mediana   p25   p75
##   &lt;fct&gt;  &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 agua      10   0.845 0.653 0.937
## 2 cafe      10   1.44  1.28  1.68 
## 3 alcool    10   2.25  1.77  2.85</code></pre>
</div>
</div>
<div id="hipóteses-estatísticas-7" class="section level3 hasAnchor" number="17.6.2">
<h3><span class="header-section-number">17.6.2</span> Hipóteses estatísticas<a href="#hip%C3%B3teses-estat%C3%ADsticas-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se não houver diferença entre os grupos, ou seja, os grupos são provenientes de uma mesma população, as somas dos postos em cada grupo devem ficar próximas. Desta forma,</p>
<blockquote>
<p><font size=2> <strong><span class="math inline">\(H_{0}\)</span></strong>: As populações são iguais.<br />
<strong><span class="math inline">\(H_{1}\)</span></strong>: Pelo menos uma das populações tende a exibir valores diferentes do que as outras populações. </font></p>
</blockquote>
</div>
<div id="pressupostos-do-teste-1" class="section level3 hasAnchor" number="17.6.3">
<h3><span class="header-section-number">17.6.3</span> Pressupostos do teste<a href="métodos-não-paramétricos.html#pressupostos-do-teste-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O teste de Kruskal-Wallis pressupõe as seguintes condições para o seu adequado uso:</p>
<ol style="list-style-type: decimal">
<li>As amostras são amostras aleatórias independentes de suas respectivas populações;</li>
<li>A escala de medição utilizada é pelo menos ordinal e, se houver apenas três grupos, deve haver pelo menos 5 casos em cada grupo;</li>
<li>As distribuições dos valores nas populações amostradas são idênticas, exceto pela possibilidade de que uma ou mais das populações sejam compostas por valores que tendem a ser maiores do que os das outras populações.</li>
</ol>
</div>
<div id="execução-do-teste-estatístico-3" class="section level3 hasAnchor" number="17.6.4">
<h3><span class="header-section-number">17.6.4</span> Execução do teste estatístico<a href="#execu%C3%A7%C3%A3o-do-teste-estat%C3%ADstico-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="lógica-do-teste-de-kruskall-wallis" class="section level4 hasAnchor" number="17.6.4.1">
<h4><span class="header-section-number">17.6.4.1</span> Lógica do teste de Kruskall-Wallis<a href="#l%C3%B3gica-do-teste-de-kruskall-wallis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A teoria do teste Kruskal-Wallis é semelhante à do teste de Mann-Whitney, ou seja, tem como base a soma dos postos. Em primeiro lugar, os escores são ordenados do menor para o maior, independentemente do grupo que pertençam.</p>
<p>O menor recebe o posto 1 e assim por diante. Após a atribuição dos postos, soma-se os postos por grupo. A soma dos postos de cada grupo é representada por <span class="math inline">\(R_{1}\)</span>, <span class="math inline">\(R_{2}\)</span>, <span class="math inline">\(R_{3}\)</span>, …, <span class="math inline">\(R_{i}\)</span>. A estatística do teste, <em>H</em>, é calculada com a equação <span class="citation">(150)</span>:</p>
<p><span class="math display">\[
H =\frac {12}{N \times \left (N + 1  \right )} \sum_{i=1}^{k} \frac {R_{i}^{2}}{n_{{i}}}-3 \times\left (N + 1\right)
\]</span></p>
<p>onde <span class="math inline">\(n_{i}\)</span> é o número de observações no grupo <em>i</em>, <span class="math inline">\(N = \sum_{i=1}^{k}\times n_{i}\)</span> (o número total de observações em todos os <em>k</em> grupos) e <span class="math inline">\(R_{i}\)</span> é a soma dos postos das <span class="math inline">\(n_{i}\)</span> observações no grupo <em>i</em>.</p>
<p>Uma boa verificação (mas não uma garantia) de que os postos foram atribuídos corretamente é ver se a soma de todos os postos é igual a <span class="math inline">\(\frac {N \times \left (N + 1\right )}{2}\)</span>.</p>
<ol style="list-style-type: decimal">
<li>Criar a variável <code>posto</code> com os postos ordenados de forma crescente, independente do grupo, como realizado no teste de Mann-Whitney:</li>
</ol>
<div class="sourceCode" id="cb1058"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1058-1"><a href="métodos-não-paramétricos.html#cb1058-1" tabindex="-1"></a>dados<span class="sc">$</span>posto <span class="ot">&lt;-</span> <span class="fu">rank</span>(dados<span class="sc">$</span>tempo, <span class="at">ties.method =</span> <span class="st">&quot;average&quot;</span>)</span>
<span id="cb1058-2"><a href="métodos-não-paramétricos.html#cb1058-2" tabindex="-1"></a><span class="fu">str</span>(dados)</span></code></pre></div>
<pre><code>## tibble [30 × 4] (S3: tbl_df/tbl/data.frame)
##  $ id    : num [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ tempo : num [1:30] 0.37 0.38 0.61 0.78 0.83 0.86 0.9 0.95 1.63 1.97 ...
##  $ bebida: Factor w/ 3 levels &quot;agua&quot;,&quot;cafe&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ posto : num [1:30] 1 2 3 4 5 6 7 8 16 22.5 ...</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Somar os postos de cada grupo separadamente:</li>
</ol>
<div class="sourceCode" id="cb1060"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1060-1"><a href="métodos-não-paramétricos.html#cb1060-1" tabindex="-1"></a>resumo1 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb1060-2"><a href="métodos-não-paramétricos.html#cb1060-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(bebida) <span class="sc">%&gt;%</span> </span>
<span id="cb1060-3"><a href="métodos-não-paramétricos.html#cb1060-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb1060-4"><a href="métodos-não-paramétricos.html#cb1060-4" tabindex="-1"></a>                   <span class="at">soma =</span> <span class="fu">sum</span>(posto))</span>
<span id="cb1060-5"><a href="métodos-não-paramétricos.html#cb1060-5" tabindex="-1"></a>resumo1</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   bebida     n  soma
##   &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt;
## 1 agua      10  74.5
## 2 cafe      10 157  
## 3 alcool    10 234.</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Cálculo da estatística do teste <em>H</em></li>
</ol>
<div class="sourceCode" id="cb1062"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1062-1"><a href="métodos-não-paramétricos.html#cb1062-1" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb1062-2"><a href="métodos-não-paramétricos.html#cb1062-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb1062-3"><a href="métodos-não-paramétricos.html#cb1062-3" tabindex="-1"></a>R_agua <span class="ot">&lt;-</span> resumo1[<span class="dv">1</span>,<span class="dv">3</span>]</span>
<span id="cb1062-4"><a href="métodos-não-paramétricos.html#cb1062-4" tabindex="-1"></a>R_alcool <span class="ot">&lt;-</span> resumo1[<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb1062-5"><a href="métodos-não-paramétricos.html#cb1062-5" tabindex="-1"></a>R_cafe <span class="ot">&lt;-</span> resumo1[<span class="dv">3</span>,<span class="dv">3</span>]</span>
<span id="cb1062-6"><a href="métodos-não-paramétricos.html#cb1062-6" tabindex="-1"></a></span>
<span id="cb1062-7"><a href="métodos-não-paramétricos.html#cb1062-7" tabindex="-1"></a>H <span class="ot">&lt;-</span> (<span class="dv">12</span><span class="sc">/</span>(N<span class="sc">*</span>(N<span class="sc">+</span><span class="dv">1</span>))) <span class="sc">*</span> ((R_agua<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n) <span class="sc">+</span> (R_alcool<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n) <span class="sc">+</span> (R_cafe<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n)) <span class="sc">-</span> (<span class="dv">3</span><span class="sc">*</span>(N<span class="sc">+</span><span class="dv">1</span>))</span>
<span id="cb1062-8"><a href="métodos-não-paramétricos.html#cb1062-8" tabindex="-1"></a>H</span></code></pre></div>
<pre><code>##       soma
## 1 16.31806</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Cálculo do Valor <em>P</em></li>
</ol>
<p>Se existir três grupos, com cinco ou menos participantes em cada grupo, há necessidade de usar a tabela especial para tamanhos de amostra pequenos <span class="citation">(151)</span>. Se você tiver mais de cinco participantes por grupo, trate <em>H</em> como qui-quadrado. A estatística <em>H</em> é estatisticamente significativo se for igual ou maior que o valor crítico qui-quadrado para o grau de liberdade específico, igual a <span class="math inline">\(k - 1\)</span>. Aqui, tem-se 10 participantes por grupo e, assumindo um <span class="math inline">\(\alpha = 0,05\)</span>, o <span class="math inline">\(H_{crítico}\)</span> é igual a:</p>
<div class="sourceCode" id="cb1064"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1064-1"><a href="métodos-não-paramétricos.html#cb1064-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb1064-2"><a href="métodos-não-paramétricos.html#cb1064-2" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb1064-3"><a href="métodos-não-paramétricos.html#cb1064-3" tabindex="-1"></a>gl <span class="ot">=</span> k <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb1064-4"><a href="métodos-não-paramétricos.html#cb1064-4" tabindex="-1"></a>H_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, gl)</span>
<span id="cb1064-5"><a href="métodos-não-paramétricos.html#cb1064-5" tabindex="-1"></a>H_critico</span></code></pre></div>
<pre><code>## [1] 5.991465</code></pre>
<p>Uma vez que o <span class="math inline">\(H_{calculado} = 16,3\)</span> é maior que <span class="math inline">\(H_{crítico} = 6,0\)</span> , rejeita-se a <span class="math inline">\(H_{0}\)</span>. O valor <em>P</em>é obtido através da função pchisq():</p>
<div class="sourceCode" id="cb1066"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1066-1"><a href="métodos-não-paramétricos.html#cb1066-1" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fl">16.32</span></span>
<span id="cb1066-2"><a href="métodos-não-paramétricos.html#cb1066-2" tabindex="-1"></a><span class="fu">pchisq</span>(H, <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.0002858624</code></pre>
<p>O R tem funções que fazem facilmente esses cálculos enfadonhos. Eles são colocados aqui apenas para ilustrar o raciocínio de como o teste de Kruskal-Wallis funciona. Sempre existem curiosos lendo o livro!</p>
</div>
<div id="teste-de-kruskal-wallis-no-r" class="section level4 hasAnchor" number="17.6.4.2">
<h4><span class="header-section-number">17.6.4.2</span> Teste de Kruskal-Wallis no R<a href="métodos-não-paramétricos.html#teste-de-kruskal-wallis-no-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>No R, pode-se calcular o teste, usando a função <code>kruskal_test()</code> do pacote <code>rstatix</code>, cujos argumentos podem ser consultados na ajuda do <em>RStudio</em>.</p>
<div class="sourceCode" id="cb1068"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1068-1"><a href="métodos-não-paramétricos.html#cb1068-1" tabindex="-1"></a>teste <span class="ot">&lt;-</span> rstatix<span class="sc">::</span><span class="fu">kruskal_test</span> (<span class="at">data =</span> dados, <span class="at">formula =</span> tempo <span class="sc">~</span> bebida)</span>
<span id="cb1068-2"><a href="métodos-não-paramétricos.html#cb1068-2" tabindex="-1"></a>teste</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##   .y.       n statistic    df        p method        
## * &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;         
## 1 tempo    30      16.3     2 0.000286 Kruskal-Wallis</code></pre>
</div>
</div>
<div id="tamanho-do-efeito-4" class="section level3 hasAnchor" number="17.6.5">
<h3><span class="header-section-number">17.6.5</span> Tamanho do efeito<a href="métodos-não-paramétricos.html#tamanho-do-efeito-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O eta quadrado (<span class="math inline">\(\eta^{2}\)</span>), com base na estatística <em>H</em>, pode ser usado como a medida do tamanho do efeito do teste de Kruskal-Wallis. É calculado pela equação:</p>
<p><span class="math display">\[
\eta_{H}^{2} = \frac {\left (H - k + 1 \right)}{\left (N - k\right)}
\]</span></p>
<p>onde <em>H</em> é a estatística obtida no teste de Kruskal-Wallis; <em>k</em> é o número de grupos; N é o número total de observações <span class="citation">(152)</span>.</p>
<p>A estimativa eta ao quadrado assume valores de 0 a 1 e, multiplicada por 100, indica a porcentagem de variância na variável dependente explicada pela variável independente. Pode ser obtido no R com a função <code>kruskal_effsize()</code> do pacote <code>rstatix:</code></p>
<div class="sourceCode" id="cb1070"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1070-1"><a href="métodos-não-paramétricos.html#cb1070-1" tabindex="-1"></a>dados <span class="sc">%&gt;%</span> <span class="fu">kruskal_effsize</span> (tempo<span class="sc">~</span>bebida)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   .y.       n effsize method  magnitude
## * &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 tempo    30   0.530 eta2[H] large</code></pre>
<p>Um efeito <span class="math inline">\(\ge 0,14\)</span> é considerado grande e <span class="math inline">\(&lt;0,06\)</span> é pequeno <span class="citation">(117)</span>.</p>
</div>
<div id="testes-post-hoc-3" class="section level3 hasAnchor" number="17.6.6">
<h3><span class="header-section-number">17.6.6</span> Testes post hoc<a href="métodos-não-paramétricos.html#testes-post-hoc-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A partir do resultado do teste de Kruskal-Wallis, sabe-se que há uma diferença significativa entre os grupos, mas não se sabe quais pares de grupos são diferentes.</p>
<p>Um teste de Kruskal-Wallis significativo é geralmente seguido pelo teste de Dunn <span class="citation">(153)</span> para identificar quais grupos são diferentes.</p>
<p>Para realizar as múltiplas comparações, no R, pode ser usada a função <code>dunn_test()</code>, incluído no pacote <code>rstatix</code>. O ajuste de <em>P</em> é feito pelo método de Bonferroni:</p>
<div class="sourceCode" id="cb1072"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1072-1"><a href="métodos-não-paramétricos.html#cb1072-1" tabindex="-1"></a>pwc <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb1072-2"><a href="métodos-não-paramétricos.html#cb1072-2" tabindex="-1"></a>  <span class="fu">dunn_test</span> (tempo <span class="sc">~</span> bebida, <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>) </span>
<span id="cb1072-3"><a href="métodos-não-paramétricos.html#cb1072-3" tabindex="-1"></a>pwc</span></code></pre></div>
<pre><code>## # A tibble: 3 × 9
##   .y.   group1 group2    n1    n2 statistic         p    p.adj p.adj.signif
## * &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       
## 1 tempo agua   cafe      10    10      2.10 0.0361    0.108    ns          
## 2 tempo agua   alcool    10    10      4.04 0.0000537 0.000161 ***         
## 3 tempo cafe   alcool    10    10      1.94 0.0520    0.156    ns</code></pre>
<p>A saída do teste de Dunn, mostra que existe uma diferença estatisticamente significativa apenas entre a água e o álcool.</p>
</div>
<div id="conclusão-9" class="section level3 hasAnchor" number="17.6.7">
<h3><span class="header-section-number">17.6.7</span> Conclusão<a href="#conclus%C3%A3o-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Um teste de Kruskal-Wallis foi realizado para comparar os tempos de reação em uma simulação de direção após beber água, café ou álcool. Houve evidência de uma diferença (<em>P</em> = 0,00029) de pelo menos um par de grupos (Figura <a href="métodos-não-paramétricos.html#fig:bebida1">17.7</a>).</p>
<p>O teste de comparações de pares, usando o teste de Dunn, foi realizado para os três pares de grupos. Houve evidencia de diferença entre o grupo que consumiu duas unidades de álcool e o grupo que ingeriu água (<em>P</em> ajustado (Bonferroni) = 0,00016). Entre os demais pares não houve diferença significativa. O tempo mediano de reação para o grupo que recebeu água foi de 0,84 (0,65 – 0,94) segundos, em comparação com 2,25(1,77 – 2,85) segundos no grupo que bebeu cerveja equivalente a duas unidades de álcool, enquanto para o café foi de 1,45(1,28 – 1,69) segundos.</p>
<div class="sourceCode" id="cb1074"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1074-1"><a href="métodos-não-paramétricos.html#cb1074-1" tabindex="-1"></a>pwc <span class="ot">&lt;-</span> pwc <span class="sc">%&gt;%</span> rstatix<span class="sc">::</span><span class="fu">add_xy_position</span>(<span class="at">x=</span> <span class="st">&quot;bebida&quot;</span>)</span>
<span id="cb1074-2"><a href="métodos-não-paramétricos.html#cb1074-2" tabindex="-1"></a></span>
<span id="cb1074-3"><a href="métodos-não-paramétricos.html#cb1074-3" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggboxplot</span>(dados,</span>
<span id="cb1074-4"><a href="métodos-não-paramétricos.html#cb1074-4" tabindex="-1"></a>                  <span class="at">x =</span> <span class="st">&quot;bebida&quot;</span>,</span>
<span id="cb1074-5"><a href="métodos-não-paramétricos.html#cb1074-5" tabindex="-1"></a>                  <span class="at">y =</span> <span class="st">&quot;tempo&quot;</span>,</span>
<span id="cb1074-6"><a href="métodos-não-paramétricos.html#cb1074-6" tabindex="-1"></a>                  <span class="at">bxp.errorbar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1074-7"><a href="métodos-não-paramétricos.html#cb1074-7" tabindex="-1"></a>                  <span class="at">bxp.errorbar.width =</span> <span class="fl">0.1</span>,</span>
<span id="cb1074-8"><a href="métodos-não-paramétricos.html#cb1074-8" tabindex="-1"></a>                  <span class="at">fill =</span> <span class="st">&quot;bebida&quot;</span>,</span>
<span id="cb1074-9"><a href="métodos-não-paramétricos.html#cb1074-9" tabindex="-1"></a>                  <span class="at">palette =</span> <span class="st">&quot;nejm&quot;</span>,</span>
<span id="cb1074-10"><a href="métodos-não-paramétricos.html#cb1074-10" tabindex="-1"></a>                  <span class="at">legend =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb1074-11"><a href="métodos-não-paramétricos.html#cb1074-11" tabindex="-1"></a>                  <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>())<span class="sc">+</span></span>
<span id="cb1074-12"><a href="métodos-não-paramétricos.html#cb1074-12" tabindex="-1"></a>  ggpubr<span class="sc">::</span><span class="fu">stat_pvalue_manual</span> (pwc,</span>
<span id="cb1074-13"><a href="métodos-não-paramétricos.html#cb1074-13" tabindex="-1"></a>                              <span class="at">label =</span> <span class="st">&quot;p = {scales::pvalue(p.adj)}&quot;</span>,</span>
<span id="cb1074-14"><a href="métodos-não-paramétricos.html#cb1074-14" tabindex="-1"></a>                              <span class="at">label.size =</span> <span class="fl">3.2</span>,</span>
<span id="cb1074-15"><a href="métodos-não-paramétricos.html#cb1074-15" tabindex="-1"></a>                              <span class="at">hide.ns =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb1074-16"><a href="métodos-não-paramétricos.html#cb1074-16" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de bebida&quot;</span>, </span>
<span id="cb1074-17"><a href="métodos-não-paramétricos.html#cb1074-17" tabindex="-1"></a>                <span class="at">y =</span> <span class="st">&quot;Tempo de reação (seg)&quot;</span>,</span>
<span id="cb1074-18"><a href="métodos-não-paramétricos.html#cb1074-18" tabindex="-1"></a>                <span class="at">subtitle =</span> <span class="fu">get_test_label</span> (teste, <span class="at">detailed =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1074-19"><a href="métodos-não-paramétricos.html#cb1074-19" tabindex="-1"></a>                <span class="at">caption =</span> <span class="fu">get_pwc_label</span>(pwc))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bebida1"></span>
<img src="bookdownproj_files/figure-html/bebida1-1.png" alt="Impacto do tipo de bebida no tempo de reação ao dirigir." width="70%" height="70%" />
<p class="caption">
Figura 17.7: Impacto do tipo de bebida no tempo de reação ao dirigir.
</p>
</div>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="66">
<li id="fn66"><p>O cálculo pode também ser realizado, usando a função <code>wilcox.test()</code> do pacote <code>stats</code>, incluído no R base.<a href="métodos-não-paramétricos.html#fnref66" class="footnote-back">↩︎</a></p></li>
<li id="fn67"><p>Para maiores detalhes consulte a ajuda da função.<a href="métodos-não-paramétricos.html#fnref67" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análise-de-dados-categóricos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sec-cap18.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/petronioliveira/bookR/edit/main/17-testes_naoParametricos.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/petronioliveira/bookR/blob/main/17-testes_naoParametricos.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
